### ISSUE TITLE
Error: Assertion failed (minxd >= 0 && minyd >= 0 && maxxd <= dest.rows && maxyd <= dest.cols)

### ISSUE THREAD

**Issue by ZeroCool22** [opencv/opencv#10498]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => Windows 10 / INTEL-BASED PYTHON 3
- Compiler => :grey_question:

##### Detailed description

Error: Assertion failed (minxd >= 0 && minyd >= 0 && maxxd <= dest.rows && maxyd <= dest.cols)

##### Steps to reproduce

```
73%|█████████████████████████████████████████████████████████                     | 2458/3357 [01:28<00:32, 27.82it/s]OpenCV Error: Assertion failed (minxd >= 0 && minyd >= 0 && maxxd <= dest.rows && maxyd <= dest.cols) in cv::seamlessClone, file C:\projects\opencv-python\opencv\modules\photo\src\seamless_cloning.cpp, line 94
Traceback (most recent call last):
  File "merge_faces_masked.py", line 132, in <module>
    main( parser.parse_args() )
  File "merge_faces_masked.py", line 106, in main
    new_image = convert_one_image( autoencoder, image, mat, facepoints, erosion_kernel, args.blurSize, args.seamlessClone, args.maskType)
  File "merge_faces_masked.py", line 59, in convert_one_image
    outimage = cv2.seamlessClone(new_image.astype(numpy.uint8),base_image.astype(numpy.uint8),(image_mask*255).astype(numpy.uint8),(masky,maskx) , cv2.NORMAL_CLONE )
cv2.error: C:\projects\opencv-python\opencv\modules\photo\src\seamless_cloning.cpp:94: error: (-215) minxd >= 0 && minyd >= 0 && maxxd <= dest.rows && maxyd <= dest.cols in function cv::seamlessClone
```
-->

**Comment by lysukhin** [comment]
Had this issue when used wrong ordering of arguments (passed `dst` as `src` and vice versa).

**Comment by lysukhin** [comment]
Also, I had this one when the position of the center was outside the image borders (i.e. < 0 or > width/height).
