### ISSUE TITLE
Android Java test fail: MatOfByteTest

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#10680]
```
$ python <opencv_src>/modules/ts/misc/run.py -v -a -t java
```

Failed:
```
org.opencv.test.core.MatOfByteTest:
Error in testMatOfSubByteArray:
java.lang.UnsatisfiedLinkError: Native method not found: org.opencv.core.Mat.nPutBwOffset:(JIIII[B)I
	at org.opencv.core.Mat.nPutBwOffset(Native Method)
	at org.opencv.core.Mat.put(Mat.java:1028)
	at org.opencv.core.MatOfByte.fromArray(MatOfByte.java:67)
	at org.opencv.core.MatOfByte.<init>(MatOfByte.java:40)
	at org.opencv.test.core.MatOfByteTest.testMatOfSubByteArray(MatOfByteTest.java:20)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at org.opencv.test.OpenCVTestCase.runTest(OpenCVTestCase.java:197)
	at org.opencv.test.OpenCVTestCase.runBare(OpenCVTestCase.java:217)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
	at org.opencv.test.OpenCVTestRunner.onStart(OpenCVTestRunner.java:111)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

Related: #10489

**Comment by asmorkalov** [comment]
Cannot reproduce with current 4.x (4.10-dev).
