### ISSUE TITLE
Install via cocoapod failing

### ISSUE THREAD

**Issue by EMart86** [opencv/opencv#10696]
##### System information (version)
- OpenCV => 3.2.4
- Operating System / Platform => iOS 
- Compiler => Xcode

##### Detailed description

When installing this dependency via cocoa-pod command, it catches some scripting errors:

Installing OpenCV-Dynamic (3.2.4)
```
[!] /bin/bash -c 
set -e
git submodule init
git submodule update
python opencv/platforms/ios/build_framework.py ios --dynamic
cp -a ./ios/opencv2.framework ./opencv2.framework

Submodule path 'opencv': checked out 'a8aff6f64330a0ab2c9d71033412af892dd9b710'
Submodule 'opencv' (https://github.com/opencv/opencv.git) registered for path 'opencv'
Cloning into '/Users/meb/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/opencv'...
Executing: ['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_SHARED_LIBS=ON', '-DCMAKE_MACOSX_BUNDLE=ON', '-DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO', '-DIOS_ARCH=armv7;armv7s;arm64', '-DCMAKE_TOOLCHAIN_FILE=/Users/meb/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/opencv/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/meb/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/opencv', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode'] in /Users/meb/Library/Caches/CocoaPods/Pods/Release/OpenCV-Dynamic/3.2.4-8d4c9/ios/build/build-iphoneos
============================================================
ERROR: [Errno 2] No such file or directory
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 112, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 104, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 197, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "opencv/platforms/ios/build_framework.py", line 36, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

##### Steps to reproduce

Prerequirements: MacOSX (high sierra, 10.13.2 ), latest CocoaPods installed (https://guides.cocoapods.org/using/getting-started.html)
1) Check out SwiftEyes Project (https://github.com/oaleeapp/SwiftEyes/tree/master/Example) Tag 0.1.4
2) In the project cmd into Example folder (/SwiftEyes-master/Example) 
3) in the cmd window, execute cmd 'pod install'

**Comment by doctorcolinsmith** [comment]
I got a similar error.  The cause was that cmake was not installed.
