### ISSUE TITLE
OpenCV Error: Assertion failed when running camera calibration sample for Android

### ISSUE THREAD

**Issue by SamTew** [opencv/opencv#11070]
##### System information (version)

- OpenCV => :OpenCV Error: Assertion failed after clicking calibration for Android camera calibration sample:
- Operating System / Platform => :Windows 8.1 64 Bit:
- Compiler => :Android Studio 3.0.1:

##### Detailed description

<E/cv::error(): OpenCV Error: Assertion failed (_tvec.total() * _tvec.channels() == 3 && (_tvec.depth() == CV_32F || _tvec.depth() == CV_64F)) in void cv::fisheye::projectPoints(cv::InputArray, cv::OutputArray, cv::InputArray, cv::InputArray, cv::InputArray, cv::InputArray, double, cv::OutputArray), file /home/maksim/workspace/android-pack/opencv/modules/calib3d/src/fisheye.cpp, line 77
E/org.opencv.calib3d: calib3d::projectPoints_11() caught cv::Exception: /home/maksim/workspace/android-pack/opencv/modules/calib3d/src/fisheye.cpp:77: error: (-215) _tvec.total() * _tvec.channels() == 3 && (_tvec.depth() == CV_32F || _tvec.depth() == CV_64F) in function void cv::fisheye::projectPoints(cv::InputArray, cv::OutputArray, cv::InputArray, cv::InputArray, cv::InputArray, cv::InputArray, double, cv::OutputArray)
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: org.opencv.samples.cameracalibration, PID: 27057
                  java.lang.RuntimeException: An error occured while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: CvException [org.opencv.core.CvException: cv::Exception: /home/maksim/workspace/android-pack/opencv/modules/calib3d/src/fisheye.cpp:77: error: (-215) _tvec.total() * _tvec.channels() == 3 && (_tvec.depth() == CV_32F || _tvec.depth() == CV_64F) in function void cv::fisheye::projectPoints(cv::InputArray, cv::OutputArray, cv::InputArray, cv::InputArray, cv::InputArray, cv::InputArray, double, cv::OutputArray)
                  ]
                      at org.opencv.calib3d.Calib3d.projectPoints_1(Native Method)
                      at org.opencv.calib3d.Calib3d.projectPoints(Calib3d.java:1152)
                      at org.opencv.samples.cameracalibration.CameraCalibrator.computeReprojectionErrors(CameraCalibrator.java:110)
                      at org.opencv.samples.cameracalibration.CameraCalibrator.calibrate(CameraCalibrator.java:72)
                      at org.opencv.samples.cameracalibration.CameraCalibrationActivity$2.doInBackground(CameraCalibrationActivity.java:169)
                      at org.opencv.samples.cameracalibration.CameraCalibrationActivity$2.doInBackground(CameraCalibrationActivity.java:154)
                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      	... 3 more

I tried to check this condition _tvec.total() * _tvec.channels() == 3 && (_tvec.depth() == CV_32F || _tvec.depth() == CV_64F) but with the variable tvec instead of _tvec and it is a true condition>

##### Steps to reproduce

< I did not change the original code >

**Comment by alalek** [comment]
Please check that you doesn't have other versions of OpenCV on build machine and target Android device.

**Comment by alalek** [comment]
I have build OpenCV & sample from the current master branch and I can't reproduce this issue - camera calibration application works well:
```
I/OCVSample::CameraCalibrator(17330): Average re-projection error: 0,175461
I/OCVSample::CameraCalibrator(17330): Camera matrix: [782.2378781774491, 0, 480;
I/OCVSample::CameraCalibrator(17330):  0, 782.2378781774491, 360;
I/OCVSample::CameraCalibrator(17330):  0, 0, 1]
I/OCVSample::CameraCalibrator(17330): Distortion coefficients: [0.1181866334625733;
I/OCVSample::CameraCalibrator(17330):  -0.3074546516354468;
I/OCVSample::CameraCalibrator(17330):  0;
I/OCVSample::CameraCalibrator(17330):  0;
I/OCVSample::CameraCalibrator(17330):  0]
I/OCVSample::CalibrationResult(17330): Saved camera matrix: [782.2378781774491, 0, 480;
I/OCVSample::CalibrationResult(17330):  0, 782.2378781774491, 360;
I/OCVSample::CalibrationResult(17330):  0, 0, 1]
I/OCVSample::CalibrationResult(17330): Saved distortion coefficients: [0.1181866334625733;
I/OCVSample::CalibrationResult(17330):  -0.3074546516354468;
I/OCVSample::CalibrationResult(17330):  0;
I/OCVSample::CalibrationResult(17330):  0;
I/OCVSample::CalibrationResult(17330):  0]
```

**Comment by SamTew** [comment]
May I know the opencv module version you used? I am getting the same error with current master branch using version 3.4.1

**Comment by alalek** [comment]
I used 7e9578789b8f01cabf92d2c57691dbe65d6ee5df master commit.

Your OpenCV binaries looks like misplaced, OpenCV 3.4.1 [must dump](https://github.com/opencv/opencv/blob/3.4.1/modules/core/src/system.cpp#L896-L904) current OpenCV version in messages:

Instead of this message

> OpenCV Error: Assertion failed

you should have something like this

> OpenCV(3.4.1-dev) Error: Assertion failed

Remove "OpenCV Manager for Android" from your device if you have it (and never install it again - it is deprecated)

These 3 components must have the same version:
- OpenCV Java API code
- OpenCV JNI code
- OpenCV itself

Last 2 components are located in "libopencv_java3.so".

Check "adb logcat" to catch problems.

**Comment by SamTew** [comment]
I use Android Studio in Windows and import the module into project. Am I doing in a wrong way? Should I use Ubuntu Android Studio instead?

**Comment by alalek** [comment]
You should put libopencv_java3.so into .apk file to keep versions synchronized and avoid loading of wrong version.
This tracker is for issues and bugs that needs fix in OpenCV. Usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

Android Studio should work too. I wrote some notes in [this file](https://github.com/opencv/opencv/blob/3.4.1/modules/java/android_sdk/build.gradle.in) how to use OpenCV with gradle apps.

**Comment by SamTew** [comment]
So, is it using static initialization?

`   static {
        if (!OpenCVLoader.initDebug()) {
            // Handle initialization error
        }
    }`
