### ISSUE TITLE
Python fisheye.stereoCalibrate: Assertion failed objectPoints.type()

### ISSUE THREAD

**Issue by philipptrenz** [opencv/opencv#11085]
##### System information

- opencv-python '3.4.0.12' (installed via pip)
- opencv-contrib-python '3.4.0.12' (installed via pip)
- Windows 64 Bit
- Python 3.6.4 :: Anaconda, Inc.

##### Detailed description

While `cv2.fisheye.calibrate()` works with both versions of objp as intented, `cv2.fisheye.stereoCalibrate()` throws errors. Curiously different ones, `in function cv::internal::projectPoints`  and `in function cv::fisheye::stereoCalibrate`.

This could be related to #5534

##### Steps to reproduce

**Case 1**
```python
objp = np.zeros((1, CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
...

K_left = np.zeros((3, 3))
D_left = np.zeros((4, 1))

K_right = np.zeros((3, 3))
D_right = np.zeros((4, 1))

R = np.zeros((1, 1, 3), dtype=np.float64)
T = np.zeros((1, 1, 3), dtype=np.float64)

rms, _, _, _, _, _, _ = \
        cv2.fisheye.stereoCalibrate(
            [objp]*len(imgpoints_left),
            imgpoints_left,
            imgpoints_right,
            K_left,
            D_left,
            K_right,
            D_right,
            (1280,800),
            R,
            T,
            flags,
            (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
        )
```
```
OpenCV Error: Assertion failed (!objectPoints.empty() && objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3))) in cv::internal::projectPoints, file C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp, line 1168
Traceback (most recent call last):
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 239, in <module>
    calibrate(reader, cam_ids, CHECKERBOARD, SQUARE_SIZE)
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 206, in calibrate
    (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp:1168: error: (-215) !objectPoints.empty() && objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3)) in function cv::internal::projectPoints
```

**Case 2**

```python
objp = np.zeros((CHECKERBOARD[0]*CHECKERBOARD[1],3), np.float32)
objp[:,:2] = np.mgrid[0:CHECKERBOARD[0],0:CHECKERBOARD[1]].T.reshape(-1,2)
```
```
OpenCV Error: Assertion failed (objectPoints.type() == (((5) & ((1 << 3) - 1)) + (((3)-1) << 3)) || objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3))) in cv::fisheye::stereoCalibrate, file C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp, line 844
Traceback (most recent call last):
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 239, in <module>
    calibrate(reader, cam_ids, CHECKERBOARD, SQUARE_SIZE)
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 206, in calibrate
    (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: C:\projects\opencv-python\opencv\modules\calib3d\src\fisheye.cpp:844: error: (-215) objectPoints.type() == (((5) & ((1 << 3) - 1)) + (((3)-1) << 3)) || objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3)) in function cv::fisheye::stereoCalibrate
```

**Comment by philipptrenz** [comment]
Meanwhile also tested with OpenCV 3.4.1 via `conda install -c conda-forge opencv`


## Case 1

```
OpenCV(3.4.1) Error: Assertion failed (!objectPoints.empty() && objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3))) in cv::internal::projectPoints, file C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp, line 1176
Traceback (most recent call last):
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 244, in <module>
    calibrate(reader, cam_ids, CHECKERBOARD, SQUARE_SIZE)
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 208, in calibrate
    (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: OpenCV(3.4.1) C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp:1176: error: (-215) !objectPoints.empty() && objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3)) in function cv::internal::projectPoints
```


## Case 2

```
OpenCV(3.4.1) Error: Assertion failed (objectPoints.type() == (((5) & ((1 << 3) - 1)) + (((3)-1) << 3)) || objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3))) in cv::fisheye::stereoCalibrate, file C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp, line 852
Traceback (most recent call last):
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 244, in <module>
    calibrate(reader, cam_ids, CHECKERBOARD, SQUARE_SIZE)
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 208, in calibrate
    (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: OpenCV(3.4.1) C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp:852: error: (-215) objectPoints.type() == (((5) & ((1 << 3) - 1)) + (((3)-1) << 3)) || objectPoints.type() == (((6) & ((1 << 3) - 1)) + (((3)-1) << 3)) in function cv::fisheye::stereoCalibrate
```

**Comment by philipptrenz** [comment]
I got around the checks in `projectPoints` and `stereoCalibrate` and they seem to have the right shape by using
```
objp = np.zeros( (CHECKERBOARD[0]*CHECKERBOARD[1], 1, 3) , np.float64)
objp[:,0, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
objp = objp * SQUARE_SIZE;      # SQUARE_SIZE in mm

objpoints = np.array([objp]*len(imgpoints_left), dtype=np.float64)

imgpoints_left = np.asarray(imgpoints_left, dtype=np.float64)
imgpoints_right = np.asarray(imgpoints_right, dtype=np.float64)
```

which results in 

* objpoints shape:  (5, 48, 1, 3)
* imgpoints_left shape:  (5, 48, 1, 2) 
* imgpoints_right shape:  (5, 48, 1, 2)

Now I get the following error. As I am dealing with cameras having 190° FOV I'm not sure if this is associated with the array formats or my setup.

```
OpenCV(3.4.1) Error: Assertion failed (abs_max < threshold) in cv::fisheye::stereoCalibrate, file C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp, line 1021
Traceback (most recent call last):
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 276, in <module>
    calibrate(reader, cam_ids, CHECKERBOARD, SQUARE_SIZE)
  File "C:/Users/treph/pycamdriver/stereo_calibration.py", line 240, in calibrate
    (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-6)
cv2.error: OpenCV(3.4.1) C:\bld\opencv_1520732670222\work\opencv-3.4.1\modules\calib3d\src\fisheye.cpp:1021: error: (-215) abs_max < threshold in function cv::fisheye::stereoCalibrate
```

**Comment by philipptrenz** [comment]
Also tried the suggested workaround in #5534

```
N_OK = len(imgpoints_left)

objp = np.zeros( (CHECKERBOARD[0]*CHECKERBOARD[1], 1, 3) , np.float64)
objp[:,0, :2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)

objpoints = np.array([objp]*len(imgpoints_left), dtype=np.float64)
imgpoints_left = np.asarray(imgpoints_left, dtype=np.float64)
imgpoints_right = np.asarray(imgpoints_right, dtype=np.float64)

objpoints = np.reshape(objpoints, (N_OK, 1, CHECKERBOARD[0]*CHECKERBOARD[1], 3))
imgpoints_left = np.reshape(imgpoints_left, (N_OK, 1, CHECKERBOARD[0]*CHECKERBOARD[1], 2))
imgpoints_right = np.reshape(imgpoints_right, (N_OK, 1, CHECKERBOARD[0]*CHECKERBOARD[1], 2))	
```

for the format
* objpoints shape:  (<num of calibration images>, 1, <num points in set>, 3)
* imgpoints_left shape:  (<num of calibration images>, 1, <num points in set>, 2)
* imgpoints_right shape:  (<num of calibration images>, 1, <num points in set>, 2)

**Comment by rajattiwari111** [comment]
how to define imgpoints_left and right please tell??

**Comment by AleksandrPanov** [comment]
@philipptrenz, as I understand it, a modified example is used from [here](https://medium.com/@kennethjiang/calibrate-fisheye-lens-using-opencv-333b05afa0b0). The images you are using are missing, as well as the complete code.
Could you provide full code to reproduce the issue?

**Comment by AleksandrPanov** [comment]
As I understand it, the problem is the extra dimension of the arrays `objpoints`, `imgpoints_left` and `imgpoints_right`. You can try using cv.Mat wrapper #20558. Then you don't have to use extra dimension. The code will look like this:
```
objPoints = cv.Mat(objPoints)
imgPointsLeft = cv.Mat(imgPointsLeft)
...
```
Also, I noticed that regardless of the input data type, stereoCalibrate works with `double` (np.float64).

**Comment by AleksandrPanov** [comment]
checked cv.Mat wrapper #20558
You can write code like this:

```
objPoints = np.array([objPoint]*N_OK, dtype=np.float64)
objPoints = cv.Mat(np.reshape(objPoints, (N_OK, -1, 3)), wrap_channels=3)

imgPointsLeft = np.asarray(imgPointsLeft, dtype=np.float64)
imgPointsLeft = cv.Mat(np.reshape(imgPointsLeft, (N_OK, -1, 2)), wrap_channels=2)

imgPointsRight = np.asarray(imgPointsRight, dtype=np.float64)
imgPointsRight = cv.Mat(np.reshape(imgPointsRight, (N_OK, -1, 2)), wrap_channels=2)

```
Here is all the code:
[repr_cv_mat.py.txt](https://github.com/opencv/opencv/files/7100756/repr_cv_mat.py.txt)

**Comment by AleksandrPanov** [comment]
@alalek I think it might be closed.
