### ISSUE TITLE
Error when compiling on Ubuntu

### ISSUE THREAD

**Issue by tonyrulez** [opencv/opencv#11153]
##### System information (version)

- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 16.04.4 LTS

##### Detailed description

Trying to install latest build on Ubuntu. Before compiling I installed all of these: https://pastebin.com/raw/DhKkF0Da

This is where it stops after sudo make. What am I missing?

[ 90%] Generate files for Java bindings
Traceback (most recent call last):
  File "/home/tonyrulez/Letöltések/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 1093, in <module>
    copy_java_files(java_files_dir, target_path)
  File "/home/tonyrulez/Letöltések/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 1032, in copy_java_files
    src = checkFileRemap(java_file)
  File "/home/tonyrulez/Letöltések/opencv-3.4.1/modules/java/generator/../generator/gen_java.py", line 25, in checkFileRemap
    assert path[-3:] != '.in', path
AssertionError: /home/tonyrulez/Letöltések/opencv-3.4.1/modules/java/generator/src/java/org/opencv/osgi/OpenCVNativeLoader.java.in
modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/build.make:357: recipe for target 'CMakeFiles/dephelper/gen_opencv_java_source' failed
make[2]: *** [CMakeFiles/dephelper/gen_opencv_java_source] Error 1
CMakeFiles/Makefile2:2547: recipe for target 'modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all' failed
make[1]: *** [modules/java_bindings_generator/CMakeFiles/gen_opencv_java_source.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alalek** [comment]
> assert path[-3:] != '.in', path
AssertionError: /home/tonyrulez/Letöltések/opencv-3.4.1/modules/java/generator/src/java/org/opencv/osgi/OpenCVNativeLoader.java.in

I have no idea that is "wrong" with your environment: '.in' suffix is present and this assertion should not fail.
Try to dump more information from Python script, start from `pprint(path[-3:])`.

We don't help with remote investigation of problems which we are not able to reproduce on our side (because it is very time consuming and usually configuration problem without any following fix into OpenCV), but we can take a look on **the clear reason of the problem** and suggest some fix/workaround.

**Comment by tengerye** [comment]
I have a similar problem. But the error arises at different place.

`[ 51%] Linking CXX executable ../../bin/opencv_visualisation
[ 51%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_gtest.cpp.o
[ 51%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze/KAZEFeatures.cpp.o
/usr/bin/ld: warning: libgfortran.so.3, needed by //home/yetengqi/anaconda3/lib/libopenblas.so.0, not found (try using -rpath or -rpath-link)
//home/yetengqi/anaconda3/lib/libopenblas.so.0: undefined reference to `_gfortran_pow_i4_i4@GFORTRAN_1.0'
//home/yetengqi/anaconda3/lib/libopenblas.so.0: undefined reference to `_gfortran_compare_string@GFORTRAN_1.0'
//home/yetengqi/anaconda3/lib/libopenblas.so.0: undefined reference to `_gfortran_etime@GFORTRAN_1.0'
//home/yetengqi/anaconda3/lib/libopenblas.so.0: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
collect2: error: ld returned 1 exit status
apps/visualisation/CMakeFiles/opencv_visualisation.dir/build.make:101: recipe for target 'bin/opencv_visualisation' failed
make[2]: *** [bin/opencv_visualisation] Error 1
CMakeFiles/Makefile2:4060: recipe for target 'apps/visualisation/CMakeFiles/opencv_visualisation.dir/all' failed
make[1]: *** [apps/visualisation/CMakeFiles/opencv_visualisation.dir/all] Error 2
[ 51%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_perf.cpp.o
[ 51%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ts_func.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/evaluation.cpp.o
[ 52%] Building CXX object modules/ts/CMakeFiles/opencv_ts.dir/src/ocl_perf.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/matchers.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/mser.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/draw.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/feature2d.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/bagofwords.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/dynamic.cpp.o
[ 52%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/blobdetector.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/orb.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/agast_score.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/main.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast_score.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/brisk.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/keypoint.cpp.o
[ 53%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/gftt.cpp.o
[ 54%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/opencl_kernels_features2d.cpp.o
[ 54%] Building CXX object modules/features2d/CMakeFiles/opencv_features2d.dir/src/fast.avx2.cpp.o
[ 54%] Linking CXX shared library ../../lib/libopencv_features2d.so
[ 54%] Built target opencv_features2d
[ 54%] Linking CXX static library ../../lib/libopencv_ts.a
[ 54%] Built target opencv_ts
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by alalek** [comment]
@tengerye What part of error message says that problem is related to this Java/Python issue?

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

P.S. I will remove these two last messages from this issue tomorrow.

**Comment by tengerye** [comment]
@alalek My question is merely about building which I could not find answers at OpenCV forum.

**Comment by alalek** [comment]
This tracker is for issues and bugs that needs fix in OpenCV.
You have a configuration problem with BLAS installation in your custom build environment:

> warning: libgfortran.so.3, needed by //home/yetengqi/anaconda3/lib/libopenblas.so.0, not found (try using -rpath or -rpath-link) //home/yetengqi/anaconda3/lib/libopenblas.so.0: undefined reference to_gfortran_pow_i4_i4@GFORTRAN_1.0'

We don't help with remote investigation of problems **which we are not able to reproduce on our side** (because it is very time consuming and usually configuration problem without any following fix into OpenCV).

Current workaround for your problem is disabling BLAS support in OpenCV (via CMake flags).
