### ISSUE TITLE
failed to build OpenCV Android SDK

### ISSUE THREAD

**Issue by andyli** [opencv/opencv#11185]
Trying to run `python build_sdk.py --sdk_path=/home/andy/Android/Sdk/ --ndk_path=/home/andy/Android/Sdk/ndk-bundle --config=ndk-16.config.py build`, it gave me the error:

```
[601/903] Generating OpenCV Android library project. SDK target:
FAILED: cd /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk && /home/andy/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E remove /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/build.xml /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/local.properties /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/proguard-project.txt /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/project.properties && /home/andy/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E copy_if_different /home/andy/Documents/opencv/platforms/android/build/o4a/modules/java/android_sdk/AndroidManifest.xml /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/AndroidManifest.xml && /home/andy/Android/Sdk/tools/android --silent create lib-project --path "/home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk" --target "android_sdk_target-NOTFOUND" --name OpenCV --package org.opencv 2>"/home/andy/Documents/opencv/platforms/android/build/o4a/modules/java/android_sdk/create_lib_project.log" && /home/andy/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E copy_if_different /home/andy/Documents/opencv/platforms/android/build/o4a/modules/java/android_sdk/AndroidManifest.xml /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk/AndroidManifest.xml
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "--silent create lib-project --path /home/andy/Documents/opencv/platforms/android/build/o4a/android_sdk --target android_sdk_target-NOTFOUND --name OpenCV --package org.opencv"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
ninja: build stopped: subcommand failed.
Package configuration:
================================================================================
ABIs = [
    ABI("2", "armeabi-v7a", "arm-linux-androideabi-4.9", cmake_vars=dict(ANDROID_ABI='armeabi-v7a with NEON')),
    ABI("1", "armeabi",     "arm-linux-androideabi-4.9", cmake_vars=dict(WITH_TBB='OFF')),
    ABI("3", "arm64-v8a",   "aarch64-linux-android-4.9"),
    ABI("5", "x86_64",      "x86_64-4.9"),
    ABI("4", "x86",         "x86-4.9"),
]
================================================================================
Traceback (most recent call last):
  File "build_sdk.py", line 363, in <module>
    builder.build_library(abi, do_install)
  File "build_sdk.py", line 187, in build_library
    execute(["ninja"])
  File "build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1
```

The full log can be found at https://gist.github.com/andyli/f9575566d774d605043e04558cd291ad.
FYI, I'm building OpenCV 3.4.1, on a Ubuntu 16.04 machine.

I believe the usage of the "android" command has to be replaced with the equivalent "sdkmanager" and "avdmanager" commands as suggested by the log.

In the mean time, it would be great if you can suggest a simply workaround, like using a particular version of the Android SDK instead of the latest one.

**Comment by alalek** [comment]
OpenCV doesn't support Android gradle builds at this moment.
You need older version of Android SDK / Build Tools to build OpenCV: #8460
