### ISSUE TITLE
... does not support `vmsr fpscr,r3' in Thumb mode. Error on OpenCv 3.4.1 to Android compilation

### ISSUE THREAD

**Issue by ansanders** [opencv/opencv#11258]
During my custom compilation of opencv from source to android with contrib support, following error messages appeared when building armeabi ABI: 
```
/tmp/ccySUHHy.s: Assembler messages:
/tmp/ccySUHHy.s:1780: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode
/tmp/ccySUHHy.s:8961: Error: selected processor does not support `vmrs r3,fpscr' in Thumb mode
/tmp/ccySUHHy.s:9053: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode
/tmp/ccySUHHy.s:9254: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode

```
or 

```
/tmp/ccOnnaxO.s: Assembler messages:
/tmp/ccOnnaxO.s:701: Error: selected processor does not support `vmrs r3,fpscr' in Thumb mode
/tmp/ccOnnaxO.s:821: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode
/tmp/ccOnnaxO.s:947: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode
/tmp/ccOnnaxO.s:1015: Error: selected processor does not support `vmsr fpscr,r3' in Thumb mode

```

My aim is to build OpenCV 3.4.1 for Android on all ABI's with use of the new JavaCamera2View

##### System information (version)

- OpenCV => 3.4.1
- Android SDK 25.2.5
- Android NDK 16b
- Operating System / Platform => Ubuntu 16.04
- Compiler => build_sdk.py android cmake

#### things I already tried to build OpenCv 3.4.1 with contrib for android: 

- downgraded to android tools 25.2.5 to resolve android command error 
- use android NDK 16 since i saw the patch of Erikman  https://github.com/opencv/opencv/pull/10288 on this discussion
- i tried different combinations of android SDK and NDK versions. Downgraded until revision 11c . 
Every revision leads to different errors with OpenCv 3.4.1 so I dont think downgrading is an option for me. 

I am very thankful for any kind of fast help since I really need to get this work 

##### Update 1: 
- same Error with NDK r15c:

```
18_U1/src/tbb/scheduler.cpp.o -c 3rdparty/tbb/tbb-2018_U1/src/tbb/scheduler.cpp
/tmp/ccyILxs0.s: Assembler messages:
/tmp/ccyILxs0.s:1473: Error: selected processor does not support Thumb mode `vmrs r3,fpscr'
/tmp/ccyILxs0.s:1516: Error: selected processor does not support Thumb mode `vmsr fpscr,r3'
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build_sdk.py", line 363, in <module>
    builder.build_library(abi, do_install)
  File "build_sdk.py", line 191, in build_library
    execute(["ninja", "install/strip"])
  File "build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1


```

##### Update 2: 
- error with NDK 14b: 
`FAILED: lib/armeabi/libopencv_java3.so 
`
... 
```
/usr/local/google/buildbot/src/android/ndk-r14-release/out/build/tmp/build-25995/build-gnustl/static-armeabij4.9/build/include/ext/concurrence.h:219: error: relocation overflow in R_ARM_THM_CALL
/usr/local/google/buildbot/src/android/ndk-r14-release/out/build/tmp/build-25995/build-gnustl/static-armeabij4.9/build/include/bits/basic_string.h:249: error: relocation overflow in R_ARM_THM_CALL
/usr/local/google/buildbot/src/android/ndk-r14-release/out/build/tmp/build-25995/build-gnustl/static-armeabij4.9/build/include/bits/basic_string.h:249: error: relocation overflow in R_ARM_THM_CALL

```

### Solution provided by Alalek worked: specified ndk-16.config.py with disabled TBB in build_sdk and now it works!

**Comment by ansanders** [comment]
Ty for your fast answer again. 
I meant the new JavaCamera2View. I have a full functional opencv 3.4.0 android port but need to build newer version for that .

Where can i explicity set the DFlags when i use the build_sdk.py? Then i try to disable TBB

**Comment by ansanders** [comment]
Ty man!!! that ndk-16.config.py with disabled TBB did the trick! 
I hope you get your earnings mate! 
We can close this issue now
