### ISSUE TITLE
cv2.error: OpenCV(3.4.1) /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/modules/dnn/src/caffe/caffe_io.cpp:1145: error: (-2) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: openpose_pose_coco.prototxt in function ReadNetParamsFromTextFileOrDie

### ISSUE THREAD

**Issue by monajalal** [opencv/opencv#11432]
Can you please suggest how to fix this?

```
[jalal@goku opencv]$ ls
COCO_val2014_000000000589.jpg  openpose_pose_coco.prototxt  openpose.py  pose_iter_440000.caffemodel
[jalal@goku opencv]$ python openpose.py --input=COCO_val2014_000000000589.jpg --proto=openpose_pose_coco.prototxt --model=pose_iter_440000.caffemodel --dataset=COCO
[libprotobuf ERROR /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format opencv_caffe.NetParameter: 7:1: Expected identifier, got: <
OpenCV(3.4.1) Error: Unspecified error (FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: openpose_pose_coco.prototxt) in ReadNetParamsFromTextFileOrDie, file /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/modules/dnn/src/caffe/caffe_io.cpp, line 1145
Traceback (most recent call last):
  File "openpose.py", line 51, in <module>
    net = cv.dnn.readNetFromCaffe(args.proto, args.model)
cv2.error: OpenCV(3.4.1) /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/modules/dnn/src/caffe/caffe_io.cpp:1145: error: (-2) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse NetParameter file: openpose_pose_coco.prototxt in function ReadNetParamsFromTextFileOrDie
```
I already followed https://github.com/opencv/opencv/issues/11077 to download the necessary files.

```
[jalal@goku opencv]$ which python
/scratch/sjn/anaconda/bin/python
[jalal@goku opencv]$ python -V
Python 3.6.3 :: Anaconda custom (64-bit)
[jalal@goku opencv]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core
[jalal@goku opencv]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)
```

**Comment by berak** [comment]
mona, can you try to *look* into the prototxt you downloaded ? like 

     head -c 3000 openpose_pose_coco.prototxt

downloads *can* go wrong. maybe this does not have an actual prototxt, but a html error msg

**Comment by dkurt** [comment]
@monajalal, Have you solved this problem? Can we close an issue?

**Comment by ironllamagirl** [comment]
@dkurt  I have the same issue, redownloaded the files, they are not damaged. 

How can I fix this?

**Comment by parvathy90** [comment]
I have the same issue:
 2020-06-11 06:44:33.947738: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
[INFO] loading face detector model...
/content/gdrive/My\ Drive/face-mask-detector/face-mask-detector/face_detector/deploy.prototxt
/content/gdrive/My\ Drive/face-mask-detector/face-mask-detector/face_detector/res10_300x300_ssd_iter_140000.caffemodel
Traceback (most recent call last):
  File "/content/gdrive/My Drive/face-mask-detector/face-mask-detector/detect_mask_video.py", line 96, in <module>
    faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/content/gdrive/My\ Drive/face-mask-detector/face-mask-detector/face_detector/deploy.prototxt" in function 'ReadProtoFromTextFile'

**Comment by berak** [comment]
> "/content/gdrive/My\ Drive/face-mask-detector/face-mask-detector/face_detector/deploy.prototxt"

please remove backslash in `My\ Drive`

**Comment by harshdhamecha** [comment]
Kindly refer [this](https://stackoverflow.com/questions/62223161/colab-face-mask-implementation) question on stackoverflow
