### ISSUE TITLE
imwrite produces segfault with matrix expressions

### ISSUE THREAD

**Issue by petercheng00** [opencv/opencv#11545]
##### System information (version)
- OpenCV => 3.4.1
- Operating System / Platform => Ubuntu 18.04 64 Bit
- Compiler => gcc 7.3.0

##### Detailed description
imwrite produces a segfault if the provided input array is an expression involving an operation on a mat, such as 2 * x or x + y. It occurs for me with both jpg and png output, and with 8U and 32F types. The problem does not occur on OpenCV 3.0.0, other versions untested.

##### Steps to reproduce
```
cv::Mat1b m = cv::Mat1b::zeros(10, 10);
cv::imwrite("works.png", cv::Mat(m * 2));
cv::imwrite("fails.png", m * 2);
```

**Comment by alalek** [comment]
> segfault

Stack trace?

**Comment by petercheng00** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff0bd2c0b in cv::PngEncoder::write (this=0x555555831450, img=..., params=std::vector of length 0, capacity 0)
    at /home/pcheng/opencv-3.4.1/modules/imgcodecs/src/grfmt_png.cpp:344
344	    int y, width = img.cols, height = img.rows;
(gdb) bt
#0  0x00007ffff0bd2c0b in cv::PngEncoder::write(cv::Mat const&, std::vector<int, std::allocator<int> > const&) (this=0x555555831450, img=..., params=std::vector of length 0, capacity 0)
    at /home/pcheng/opencv-3.4.1/modules/imgcodecs/src/grfmt_png.cpp:344
#1  0x00007ffff0bb45a1 in cv::imwrite_(cv::String const&, std::vector<cv::Mat, std::allocator<cv::Mat> > const&, std::vector<int, std::allocator<int> > const&, bool) (filename=..., img_vec=std::vector of length 0, capacity 0, params=std::vector of length 0, capacity 0, flipv=false) at /home/pcheng/opencv-3.4.1/modules/imgcodecs/src/loadsave.cpp:706
#2  0x00007ffff0bb47de in cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&) (filename=..., _img=..., params=std::vector of length 0, capacity 0)
    at /home/pcheng/opencv-3.4.1/modules/imgcodecs/src/loadsave.cpp:725

```

**Comment by berak** [comment]
latest master:
```
[OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.0.0-pre) Error: Bad argument (Unknown/unsupported input encountered) in imwrite, file C:\p\opencv\modules\imgcodecs\src\loadsave.cpp, line 725
```

and indeed:

```
void f(InputArray in) {
    cout << in.isMat() << endl;
    cout << in.isUMat() << endl;
}

cv::Mat m = cv::Mat::zeros(10, 10, CV_8U);
f(m*2);

0
0
```
