### ISSUE TITLE
FileStorage JSON 0. float not supported by Python json module

### ISSUE THREAD

**Issue by pierriko** [opencv/opencv#11889]
##### System information (version)

- OpenCV : 3.2
- Operating System / Platform : Fedora 26

##### Detailed description

FileStorage JSON serialize 0 float as `0.` which is not supported by Python json module.
```python
>>> import json
>>> json.loads("0.0")
0.0
>>> json.loads("0.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 2 - line 1 column 3 (char 1 - 2)
```

##### Steps to reproduce

```cpp
cv::FileStorage file("/tmp/raster.json", cv::FileStorage::WRITE);
file << "raster" << raster;
```

##### Workaround

Use `.replace(".,", ".0,").replace(". ", ".0 ")` to JSON string before parsing, as:

```python
def read_mat(filename):
    with open(filename) as f:
        txt = f.read().replace(".,", ".0,").replace(". ", ".0 ")  # Fix CV json
    dat = json.loads(txt).values()[0]  # Get first node
    arr = numpy.array(dat["data"])
    # TODO use dat['dt'] = '7f' : for both data-type and depth
    dep = arr.size / dat["rows"] / dat["cols"]
    return arr.reshape(dat["rows"], dat["cols"], dep)

```

**Comment by pierriko** [comment]
Duplicate
https://github.com/opencv/opencv/issues/7951
https://github.com/opencv/opencv/pull/7952
