### ISSUE TITLE
Unknown exception occurs randomly when executing Mat.clone()

### ISSUE THREAD

**Issue by cluze** [opencv/opencv#11914]
##### System information (version)
OpenCV 3.4.1
OS Windows 10 Home Edition 64 Bit
Java 8 with OpenCV java binding

##### Detailed description
Unknown exception occurs randomly when executing Mat.clone() method, we also use Mat.empty() method to check whether the Mat is empty. Here is the detail stacktrace, we did not find the location of OpenCV native log file to find out what is the reason of this issue.

java.lang.Exception: unknown exception
	at org.opencv.core.Mat.n_clone(Native Method) ~[opencv-3.4.1.jar:3.4.1]
	at org.opencv.core.Mat.clone(Mat.java:219) ~[opencv-3.4.1.jar:3.4.1]
	at com.scsmait.preprocessor.services.SurveillanceService$2.onNext(SurveillanceService.java:127) [classes/:na]
	at com.scsmait.preprocessor.services.SurveillanceService$2.onNext(SurveillanceService.java:1) [classes/:na]
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58) [rxjava-2.1.14.jar:na]
	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:113) [rxjava-2.1.14.jar:na]
	at io.reactivex.internal.operators.observable.ObservableThrottleFirstTimed$DebounceTimedObserver.onNext(ObservableThrottleFirstTimed.java:82) [rxjava-2.1.14.jar:na]
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200) [rxjava-2.1.14.jar:na]
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252) [rxjava-2.1.14.jar:na]
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) [rxjava-2.1.14.jar:na]
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) [rxjava-2.1.14.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_141]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_141]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_141]」

Any suggestion is welcome. Thank you.

**Comment by ydsmait** [comment]
This is cluze, here is the code snippet which produce this exception,
```
Observable.create(new ObservableOnSubscribe<Mat>() {
                @Override
                public void subscribe(final ObservableEmitter<Mat> emitter) throws Exception {
                    try {
                        while (videoCapture.read(frame)) {
                            captureSubscriber.setFrame(frame);
                            emitter.onNext(frame);
                        }
                    } catch (final Exception ex) {
                        LOGGER.warn("Error occurs when fetching frame from camera: " + ex.getMessage(), ex);
                    }
                }
            }).observeOn(Schedulers.io()).throttleFirst(INTERVAL, TimeUnit.MILLISECONDS).subscribeOn(Schedulers.newThread()).subscribe(new Observer<Mat>() {
                private Disposable d;

                @Override
                public void onSubscribe(final Disposable d) {
                    this.d = d;
                }

                @Override
                public void onNext(final Mat t) {
                    try {
                        if (!recording) {
                            d.dispose();
                        }
                        if (t.empty()) {
                            return;
                        }
                        **handleDetect(t.clone()); // Where exception occurs**
                        renderImageView(t, imageView);
                        // A new video output stream per hour, that means older video will be overwritten
                        final LocalDateTime now = LocalDateTime.now();
                        final long currentTime = now.toInstant(ZoneOffset.UTC).toEpochMilli();
                        if (ONE_HOUR < currentTime - time.get()) {
                            LOGGER.debug("A new video file will be created");
                            time.set(currentTime);
                            videoWriter.release();
                            videoWriter.open(getVideoFilename(camera, now), FOURCC, FPS - 5d, size);
                        }
                        videoWriter.write(frame);
                    } catch (final Exception ex) {
                        LOGGER.warn("Error occurs when processing frame: " + ex.getMessage(), ex);
                    }
                }

                @Override
                public void onError(final Throwable e) {
                    LOGGER.error(e.getMessage(), e);
                }

                @Override
                public void onComplete() {
                    // Not used
                }
            });
        }
```

**Comment by alalek** [comment]
**Complete** and stable reproducers can be used to find issue.

1. Track memory usage. JVM is not able to track properly native objects (it is just few bytes for JVM instead of underlying several megabytes), so JVM don't want to trigger GC collector and release them.
There are several hacks for this, like manual calling of `System.gc()` after each frame processing.
2. Try to attach JVM crash dumps (like `hs_err_pidXXXXX.log` files) if they are generated.
3. Ensure that passed Mat is not empty. Cloning of empty Mat may throw exceptions in the future version of OpenCV (but exception should not be "unknown").

**Comment by pwnorbitals** [comment]
This is an old issue. @cluze, is thus still reproducible with recent releases ? 
If so, please follow @alalek ’s instructions to help the developpers find the bug :)
