### ISSUE TITLE
run ./build_sdk.py to compile lib for Android occur error!

### ISSUE THREAD

**Issue by MRYangY** [opencv/opencv#12013]
##### System information (version)

- OpenCV => 3.4.2
- Operating System / Platform => Ubuntu 14
- Compiler => cmake
##### Detailed description
my command line:

> root@tvu-OptiPlex-7050:/home/tvu/opencv_build_two/opencv/platforms/android# **./build_sdk.py --ndk_path ../../../android-ndk-r10d/ --sdk_path ../../../../../../opt/andorid_sdk/adt-bundle-linux-x86-20131030/sdk/ --extra_modules_path ../../../opencv_contrib/modules/ ../../../opencv/build/ ../../../opencv**

than occur error below:

```
Args: Namespace(build_doc=False, config='ndk-10.config.py', extra_modules_path='../../../opencv_contrib/modules/', extra_pack=None, force_copy=False, force_opencv_toolchain=False, ndk_path='../../../android-ndk-r10d/', no_ccache=False, opencv_dir='../../../opencv', sdk_path='../../../../../../opt/andorid_sdk/adt-bundle-linux-x86-20131030/sdk/', sign_with=None, work_dir='../../../opencv/build/')
Package configuration:
================================================================================
ABIs = [
    ABI("2", "armeabi-v7a", "arm-linux-androideabi-4.8", cmake_vars=dict(ANDROID_ABI='armeabi-v7a with NEON')),
    ABI("1", "armeabi",     "arm-linux-androideabi-4.8"),
    ABI("3", "arm64-v8a",   "aarch64-linux-android-4.9"),
    ABI("5", "x86_64",      "x86_64-4.9"),
    ABI("4", "x86",         "x86-4.8"),
    ABI("7", "mips64",      "mips64el-linux-android-4.9"),
    ABI("6", "mips",        "mipsel-linux-android-4.8")
]
================================================================================
Android NDK path: ../../../android-ndk-r10d/
Android SDK path: ../../../../../../opt/andorid_sdk/adt-bundle-linux-x86-20131030/sdk/
Check dir /home/tvu/opencv_build_two/opencv/build (create: True, clean: False)
Check dir /home/tvu/opencv_build_two/opencv (create: False, clean: False)
Check dir /home/tvu/opencv_build_two/opencv/build/o4a (create: True, clean: True)
Check dir /home/tvu/opencv_build_two/opencv/build/OpenCV-android-sdk (create: True, clean: True)
Check dir /home/tvu/opencv_build_two/opencv/build/OpenCV-android-sdk/sdk/java/javadoc (create: True, clean: True)
Detected OpenCV version: 3.4.2-dev
Detected Engine version: 3.42
Check dir /home/tvu/opencv_build_two/opencv/build/build_service_armeabi-v7a (create: True, clean: True)
=====
===== Building library for armeabi-v7a (arm-linux-androideabi-4.8)
=====
Executing: ['cmake', '-GNinja', "-DOPENCV_EXTRA_MODULES_PATH='/home/tvu/opencv_build_two/opencv_contrib/modules'", '-DNDK_CCACHE=ccache', '-DBUILD_TESTS=ON', '-DINSTALL_TESTS=ON', "-DBUILD_ANDROID_EXAMPLES='ON'", "-DINSTALL_ANDROID_EXAMPLES='ON'", "-DBUILD_DOCS='OFF'", "-DBUILD_TESTS='OFF'", "-DANDROID_TOOLCHAIN_NAME='arm-linux-androideabi-4.8'", "-DANDROID_ABI='armeabi-v7a with NEON'", "-DANDROID_PLATFORM_ID='2'", "-DBUILD_PERF_TESTS='OFF'", "-DBUILD_EXAMPLES='OFF'", "-DWITH_TBB='ON'", "-DANDROID_STL='gnustl_static'", "-DWITH_OPENCL='OFF'", "-DCMAKE_TOOLCHAIN_FILE='/home/tvu/opencv_build_two/opencv/platforms/android/android.toolchain.cmake'", "-DWITH_IPP='OFF'", '/home/tvu/opencv_build_two/opencv']
Executing: cmake -GNinja -DOPENCV_EXTRA_MODULES_PATH='/home/tvu/opencv_build_two/opencv_contrib/modules' -DNDK_CCACHE=ccache -DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DBUILD_ANDROID_EXAMPLES='ON' -DINSTALL_ANDROID_EXAMPLES='ON' -DBUILD_DOCS='OFF' -DBUILD_TESTS='OFF' -DANDROID_TOOLCHAIN_NAME='arm-linux-androideabi-4.8' -DANDROID_ABI='armeabi-v7a with NEON' -DANDROID_PLATFORM_ID='2' -DBUILD_PERF_TESTS='OFF' -DBUILD_EXAMPLES='OFF' -DWITH_TBB='ON' -DANDROID_STL='gnustl_static' -DWITH_OPENCL='OFF' -DCMAKE_TOOLCHAIN_FILE='/home/tvu/opencv_build_two/opencv/platforms/android/android.toolchain.cmake' -DWITH_IPP='OFF' /home/tvu/opencv_build_two/opencv
**CMake Error at platforms/android/android.toolchain.cmake:628 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.11/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:127 (project)**


**CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!**
Traceback (most recent call last):
  File "./build_sdk.py", line 368, in <module>
    builder.build_library(abi, do_install)
  File "./build_sdk.py", line 184, in build_library
    execute(cmd)
  File "./build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1
```

please help me ,thanks!

**Comment by MRYangY** [comment]
i installed ninja locate /usr/bin

**Comment by MRYangY** [comment]
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
See also "/home/tvu/opencv_build_two/opencv/build/o4a/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "./build_sdk.py", line 368, in <module>
    builder.build_library(abi, do_install)
  File "./build_sdk.py", line 184, in build_library
    execute(cmd)
  File "./build_sdk.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

**Comment by alalek** [comment]
You still need properly installed ninja-build tool (cmake should be able to find it) and Android NDK ("Could not find any working toolchain in the NDK").
Cleanup build directory and start from scratch every time then external configuration is changed.

This is not a support forum. This tracker is for issues and bugs that needs fix in OpenCV.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

**Comment by sturkmen72** [comment]
outdated common question can be closed down.
