### ISSUE TITLE
Nightly: test_imgproc(Imgproc_InitUndistortMap.accuracy) failure

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#12083]
[The first failed build](http://pullrequest.opencv.org/buildbot/builders/3_4_coverage-lin64-debug/builds/102/steps/test_imgproc/logs/stdio):

```
[  RUN      ] Imgproc_InitUndistortMap.accuracy
/build/3_4_coverage-lin64-debug/opencv/modules/ts/src/ts.cpp:549: Failure
Failed

	failure reason: Arithmetic exception
	test case #12
	seed: 09491e2273330ddc
-----------------------------------
	LOG:
General failure:
	Arithmetic exception (-6)

-----------------------------------
	CONSOLE: .
-----------------------------------

[  FAILED  ] Imgproc_InitUndistortMap.accuracy (71 ms)
```

**Comment by alalek** [comment]
<details>

<summary>Stack trace</summary>

Thread 1 "opencv_test_img" received signal SIGSEGV, Segmentation fault.
0x00007faafa6e0605 in _mm256_stream_si256(long long __vector(4)*, long long __vector(4)) (__B=..., __A=0x55c20a94a388) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:1009
1009	  __builtin_ia32_movntdq256 ((__v4di *)__A, (__v4di)__B);
(gdb) bt
#0  0x00007faafa6e0605 in _mm256_stream_si256(long long __vector(4)*, long long __vector(4)) (__B=..., __A=0x55c20a94a388) at /usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:1009
#1  cv::hal_baseline::v_store_interleave (ptr=0x55c20a94a388, x=..., y=..., mode=cv::hal::STORE_ALIGNED_NOCACHE)
    at /build/3_4_coverage-lin64-debug/opencv/modules/core/include/opencv2/core/hal/intrin_avx.hpp:1980
#2  0x00007faafa6e6fd4 in cv::hal_baseline::v_store_interleave (ptr=0x55c20a94a388, a0=..., b0=..., mode=cv::hal::STORE_ALIGNED_NOCACHE)
    at /build/3_4_coverage-lin64-debug/opencv/modules/core/include/opencv2/core/hal/intrin_avx.hpp:2403
#3  0x00007faafa6ea4d0 in cv::hal::vecmerge_<int, cv::hal_baseline::v_int32x8> (src=0x7fff418e3a98, dst=0x55c20a94a368, len=162, cn=2)
    at /build/3_4_coverage-lin64-debug/opencv/modules/core/src/merge.cpp:58
#4  0x00007faafa6e7a76 in cv::hal::merge32s (src=0x7fff418e3a98, dst=0x55c20a94a368, len=162, cn=2) at /build/3_4_coverage-lin64-debug/opencv/modules/core/src/merge.cpp:192
#5  0x00007faafa6e871c in cv::merge (mv=0x7fff418e3fb0, n=2, _dst=...) at /build/3_4_coverage-lin64-debug/opencv/modules/core/src/merge.cpp:349
#6  0x000055c209ad17ba in opencv_test::(anonymous namespace)::CV_UndistortMapTest::prepare_to_validation (this=0x7fff418f4270)
    at /build/3_4_coverage-lin64-debug/opencv/modules/imgproc/test/test_imgwarp.cpp:1117
#7  0x000055c209b38036 in cvtest::ArrayTest::validate_test_results (this=0x7fff418f4270, test_case_idx=12) at /build/3_4_coverage-lin64-debug/opencv/modules/ts/src/ts_arrtest.cpp:288
#8  0x000055c209b30be1 in cvtest::BaseTest::run (this=0x7fff418f4270, start_from=0) at /build/3_4_coverage-lin64-debug/opencv/modules/ts/src/ts.cpp:330

</details>

related #12063
