### ISSUE TITLE
test_js has failed tests (master branch)

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#12436]
[Build](http://pullrequest.opencv.org/buildbot/builders/master_javascript-emscripten-lin64/builds/287).

<details>

<summary>Errors:</summary>

```
Module: Image Processing Test: test_imgProc
Died on test #5     at Object.global.test.QUnit.test (/build/master_javascript-emscripten-lin64/build/bin/node_modules/node-qunit/lib/child.js:133:21)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:78:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3): Cannot convert "undefined" to int
TypeError: Cannot convert "undefined" to int
    at Object.toWireType (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1685156)
    at Object.cvtColor (eval at new_ (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1675299), <anonymous>:9:26)
    at Object.proto.(anonymous function) [as cvtColor] (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1796598)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:120:12)

Module: Image Processing Test: test_segmentation
Died on test #1     at Object.global.test.QUnit.test (/build/master_javascript-emscripten-lin64/build/bin/node_modules/node-qunit/lib/child.js:133:21)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:152:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3): Cannot convert "undefined" to int
TypeError: Cannot convert "undefined" to int
    at Object.toWireType (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1685156)
    at Object.threshold (eval at new_ (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1675299), <anonymous>:11:26)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:166:12)

Module: Image Processing Test: test_filter
Died on test #1     at Object.global.test.QUnit.test (/build/master_javascript-emscripten-lin64/build/bin/node_modules/node-qunit/lib/child.js:133:21)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:251:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3): Cannot convert "undefined" to int
TypeError: Cannot convert "undefined" to int
    at Object.toWireType (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1685156)
    at Object.blur (eval at new_ (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1675299), <anonymous>:11:26)
    at Object.proto.(anonymous function) [as blur] (/build/master_javascript-emscripten-lin64/build/bin/opencv.js:21:1796598)
    at Object.<anonymous> (/build/master_javascript-emscripten-lin64/build/bin/test_imgproc.js:257:12)
```

</details>

Related: ~~#12269~~ #12303

**Comment by alalek** [comment]
There is missing generation of updated enums in embindgen.py.

**Comment by cv3d** [comment]
@alalek I am on it.
BTW: it is rather related to #12303

**Comment by cv3d** [comment]
@alalek Could you please setup the builders to test the patch proposed in #12469?
I am afraid I was not able to verify locally since I have not enough privileges on the current PC.
