### ISSUE TITLE
Darknet-Yolo: java.lang.Exception: unknown exception (org.opencv.dnn.Net.forward_4)

### ISSUE THREAD

**Issue by leekwunfung817** [opencv/opencv#12441]
In OpenCV-Yolo

I use the following function to use the (.cfg) and (.weights) file for object detection in Java

`net = Dnn.readNetFromDarknet(cfg, weights);`

Java code:
```
        float scale = 1.0F / 255.0F;
        Mat inputBlob = Dnn.blobFromImage(resized, scale, sz, new Scalar(0), false, false);
        net.setInput(inputBlob, "data");

        System.out.println("Detect Classes: " + classes_names.length);

        java.util.List<Mat> result = new java.util.ArrayList<Mat>(2);
        java.util.List<java.lang.String> outBlobNames = new java.util.ArrayList<java.lang.String>(2);
        outBlobNames.add(0, "yolo_16");
        outBlobNames.add(1, "yolo_23");
        net.forward(result, outBlobNames);

        Mat result_1 = result.get(0);
        Mat result_2 = result.get(1);

        for (Mat mat : result) {
            ExtractBeanFromMat(mat, im, frame, im_copy);
        }

```

The following is the exception log:
```

    Detect Classes: 2
    
    java.lang.Exception: unknown exception
    	at org.opencv.dnn.Net.forward_4(Native Method)
    	at org.opencv.dnn.Net.forward(Net.java:333)
    	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:134)
    	at DetectionCar.DetectCar.detect(DetectCar.java:26)
    	at InheritClass.ObjectDetectionHelper.detect(ObjectDetectionHelper.java:94)
    	at InheritClass.ObjectDetectionHelper.detect_directory(ObjectDetectionHelper.java:227)
    	at DetectionCar.DetectCar.main(DetectCar.java:31)
```
I use Yolo Model
1. tiny-yolov3.cfg
2. tiny-yolov3_45600.weights

How to fix the exception?

**Comment by dkurt** [comment]
@leekwunfung817, please provide references to `tiny-yolov3.cfg` and `tiny-yolov3_45600.weights` if you want to make it more reproducible.

Have you tried to run this model in C++/Python? How did you get `yolo_16` and `yolo_23` output names?

**Comment by sharived** [comment]
@leekwunfung817 - I'm having a similar issue with Java using any model (including tiny-yolov3).  My issue is specifically when passing a list of output layers.  I am able to run with a single output_layer which uses forward_2 instead of forward_4.   So in your case try net.forward(result, "yolo_16") or just net.forward(result) to see if those work for you.  To have complete results, you will need all output layers though.

I'm using OpenCV3.4.3 and my error is   
A/zygote64: java_vm_ext.cc:523] JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.NoSuchMethodError: no non-static method "Ljava/util/ArrayList;.get((I)Ljava/lang/Object;"
    java_vm_ext.cc:523]   at void org.opencv.dnn.Net.forward_4(long, long, java.util.List) (Net.java:-2)
    java_vm_ext.cc:523]   at void org.opencv.dnn.Net.forward(java.util.List, java.util.List) (Net.java:334)

As noted, all other combinations of forward work, but I really want to use multiple output layers as needed by yolo.

**Comment by dkurt** [comment]
@sharived, Could you please provide a minimal working example? I cannot reproduce it at least for another model with multiple outputs.

**Comment by sharived** [comment]
You can use [yolov3.cfg.txt](https://github.com/opencv/opencv/files/2489723/yolov3.cfg.txt)
 and weights https://pjreddie.com/media/files/yolov3.weights, but I don't think it would be specific to the model.  Its seems more like a JNI issue.

Here is my Java code:
```
        List<String> layers = getOutputsNames(); // function gets list of output names
        List<Mat> outputs = new ArrayList<>();
        for (int i=0; i<layers.size(); i++)
            outputs.add(new Mat());
        net.forward(outputs,layers);

```
Note my NDK version is 15.2.4203891

I will put together a sample app shortly.

**Comment by sharived** [comment]
I put together a simple example.  Let me know if you have any issues using it.  https://www.dropbox.com/s/1awphzh816x52el/example.zip?dl=0

**Comment by sharived** [comment]
@dkurt - I don't use the OpenCV Manager.  I just load the library directly 
```
System.loadLibrary("opencv_java3");
OpenCVLoader.initDebug();
```

and yes I'm using opencv3.4.3 - which is a fork I built, however I have the same issue with the prebuilts - see my logcat info below

```
I/OpenCV/Sample/DarkNet: Library opencv_java3 loaded
D/OpenCV/StaticHelper: Trying to get library list
E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper: Library list: ""
    First attempt to load libs
    Trying to init OpenCV libs
    Trying to load library opencv_java3
D/OpenCV/StaticHelper: Library opencv_java3 loaded
    First attempt to load libs is OK
I/OpenCV/StaticHelper: General configuration for OpenCV 3.4.3 =====================================
      Version control:               3.4.0-134-g639e3f85d-dirty
I/OpenCV/StaticHelper:   Extra modules:
        Location (extra):            /Users/ten/10imaging/opencv_contrib/modules
        Version control (extra):     3.4.3
      Platform:
        Timestamp:                   2018-10-04T15:51:36Z
        Host:                        Darwin 16.7.0 x86_64
        Target:                      Android 1 aarch64
        CMake:                       3.12.0
        CMake generator:             Unix Makefiles
        CMake build tool:            /usr/bin/make
        Configuration:               Release
      CPU/HW features:
        Baseline:                    NEON FP16
          required:                  NEON
          disabled:                  VFPV3
      C/C++:
        Built as dynamic libs?:      NO
        C++11:                       YES
        C++ Compiler:                /Users/ten/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  (ver 3.8)
        C++ flags (Release):         -isystem /Users/ten/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O2 -DNDEBUG   -DNDEBUG
        C++ flags (Debug):           -isystem /Users/ten/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG
        C Compiler:                  /Users/ten/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
        C flags (Release):           -isystem /Users/ten/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O2 -DNDEBUG   -DNDEBUG
        C flags (Debug):             -isystem /Users/ten/Library/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Winconsistent-missing-override -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments    -fvisibility=hidden -fvisibility-inlines-hidden -O0 -fno-limit-debug-info   -DDEBUG -D_DEBUG
        Linker flags (Release):      -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /Users/ten/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/Users/ten/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now    
I/OpenCV/StaticHelper:     Linker flags (Debug):        -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /Users/ten/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/Users/ten/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now    
        ccache:                      YES
        Precompiled headers:         NO
        Extra dependencies:          z dl m log
        3rdparty dependencies:       tbb libcpufeatures libprotobuf libjpeg-turbo libpng libtiff libjasper IlmImf tegra_hal
      OpenCV modules:
        To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann fuzzy hfs highgui img_hash imgcodecs imgproc java java_bindings_generator line_descriptor ml objdetect optflow phase_unwrapping photo plot python_bindings_generator reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
        Disabled:                    js world
        Disabled by dependency:      -
        Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf matlab ovis python2 python3 sfm ts viz
        Applications:                -
        Documentation:               NO
        Non-free algorithms:         NO
      Android NDK:                   /Users/ten/Library/Android/sdk/ndk-bundle (ver 17.1.4828580)
        Android ABI:                 arm64-v8a
        NDK toolchain:               aarch64-linux-android-clang
        STL type:                    c++_shared
        Native API level:            21
      Android SDK:                   /Users/ten/Library/Android/sdk (tools: 25.2.5 build tools: 28.0.2)
        android tool:                /Users/ten/Library/Android/sdk/tools/android
        SDK target:                  android-21
        Projects build scripts:      Ant/Eclipse compatible
      GUI: 
      Media I/O: 
        ZLib:                        z (ver 1.2.3)
        JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
        PNG:                         build (ver 1.6.34)
        TIFF:                        build (ver 42 - 4.0.9)
        JPEG 2000:                   build (ver 1.900.1)
        OpenEXR:                     build (ver 1.7.1)
I/OpenCV/StaticHelper:     HDR:                         YES
        SUNRASTER:                   YES
        PXM:                         YES
      Video I/O:
      Parallel framework:            TBB (ver 2018.0 interface 10001)
      Trace:                         YES (built-in)
      Other third-party libraries:
        Custom HAL:                  YES (carotene (ver 0.0.1))
        Protobuf:                    build (3.5.1)
      OpenCL:                        YES (no extra features)
        Include path:                /Users/ten/10imaging/opencv/3rdparty/include/opencl/1.2
        Link libraries:              Dynamic load
      Python (for build):            /usr/local/bin/python2.7
      Java:                          export all functions
        ant:                         /usr/local/bin/ant (ver 1.10.1)
        Java wrappers:               YES
        Java tests:                  NO
      Install to:                    /Users/ten/10imaging/opencv/build/android/release/arm8/install
    -----------------------------------------------------------------
I/zygote64: Clamp target GC heap from 261MB to 256MB
A/zygote64: java_vm_ext.cc:523] JNI DETECTED ERROR IN APPLICATION: JNI CallIntMethodV called with pending exception java.lang.NoSuchMethodError: no non-static method "Ljava/util/ArrayList;.get((I)Ljava/lang/Object;"
    java_vm_ext.cc:523]   at void org.opencv.dnn.Net.forward_4(long, long, java.util.List) (Net.java:-2)
    java_vm_ext.cc:523]   at void org.opencv.dnn.Net.forward(java.util.List, java.util.List) (Net.java:334)
    java_vm_ext.cc:523]   at void org.opencv.samples.opencv_mobilenet.MainActivity.runInference(java.lang.String) (MainActivity.java:110)
    java_vm_ext.cc:523]   at void org.opencv.samples.opencv_mobilenet.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:48)
    java_vm_ext.cc:523]   at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6984)
```

**Comment by dkurt** [comment]
@sharived, could you please try the latest state of OpenCV's [3.4](https://github.com/opencv/opencv/tree/3.4) or [master](https://github.com/opencv/opencv/tree/master) branch? @berak already fixed that in https://github.com/opencv/opencv/issues/12324. The following code works fine for me:

```java
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.dnn.Net;
import org.opencv.dnn.Dnn;
import org.opencv.core.Size;
import org.opencv.core.Scalar;

public class Main {

  public static void main(String[] args) {
    System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    Net net = Dnn.readNet("yolov3.cfg", "yolov3.weights");

    Mat img = Mat.eye(416, 416, CvType.CV_8UC3);
    Mat inputBlob = Dnn.blobFromImage(img, 1.0, new Size(416, 416), new Scalar(0), false, false);
    net.setInput(inputBlob, "data");

    java.util.List<Mat> result = new java.util.ArrayList<Mat>(2);
    java.util.List<java.lang.String> outBlobNames = new java.util.ArrayList<java.lang.String>(2);
    outBlobNames.add(0, "yolo_94");
    outBlobNames.add(1, "yolo_106");
    net.forward(result, outBlobNames);
  }
}
```

```bash
javac -cp .:/path/to/opencv/build/bin/opencv-343.jar Main.java && java -cp .:/path/to/opencv/build/bin/opencv-343.jar -Djava.library.path=/path/to/opencv/build/lib Main
```

**Comment by sharived** [comment]
Great.  Thanks!  Tried 3.4 and it worked for me.  Looks like the change was made the day after 3.4.3 was released.  This issue can be closed for me.

**Comment by dkurt** [comment]
@sharived, Thank you for your help and quick responses! 😄

**Comment by berak** [comment]
@sharivad -- great too hear that ! (and indeed, it was just one day too late ..)
