### ISSUE TITLE
Missing writeTextGraph in dnn module

### ISSUE THREAD

**Issue by alperenkirimer** [opencv/opencv#12442]
I try the tutorial at [https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API](url) with OpenCV 3.4.2 using Python. I used `tf_text_graph_ssd.py` to get pbtxt for my own tf model but I here is what I get:

`python tf_text_graph_ssd.py --input uav_model/frozen_inference_graph.pb --config uav_model/pipeline.config --output uav_model/graph.pbtxt`

`Number of classes: 1
Number of layers: 6
Scale: [0.200000-0.950000]
Aspect ratios: [1.0, 2.0, 0.5, 3.0, 0.333299994469]
Reduce boxes in the lowest layer: True
box predictor: convolutional
Input image size: 300x300
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 277, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 55, in createSSDGraph
    cv.dnn.writeTextGraph(modelPath, outputPath)
AttributeError: 'module' object has no attribute 'writeTextGraph'`

Version: 

```
python3
>>> import cv2
>>> cv2.__version__
'3.4.2'
```

And when I try `help(cv2.dnn)` all the listed functions are:

```

FUNCTIONS
    NMSBoxes(...)
        NMSBoxes(bboxes, scores, score_threshold, nms_threshold[, eta[, top_k]]) -> indices
        .   @brief Performs non maximum suppression given boxes and corresponding scores.
        .   
        .   * @param bboxes a set of bounding boxes to apply NMS.
        .   * @param scores a set of corresponding confidences.
        .   * @param score_threshold a threshold used to filter boxes by score.
        .   * @param nms_threshold a threshold used in non maximum suppression.
        .   * @param indices the kept indices of bboxes after NMS.
        .   * @param eta a coefficient in adaptive threshold formula: \f$nms\_threshold_{i+1}=eta\cdot nms\_threshold_i\f$.
        .   * @param top_k if `>0`, keep at most @p top_k picked indices.
    
    Net_readFromModelOptimizer(...)
        Net_readFromModelOptimizer(xml, bin) -> retval
        .   @brief Create a network from Intel's Model Optimizer intermediate representation.
        .   *  @param[in] xml XML configuration file with network's topology.
        .   *  @param[in] bin Binary file with trained weights.
        .   *  Networks imported from Intel's Model Optimizer are launched in Intel's Inference Engine
        .   *  backend.
    
    blobFromImage(...)
        blobFromImage(image[, scalefactor[, size[, mean[, swapRB[, crop]]]]]) -> retval
        .   @brief Creates 4-dimensional blob from image. Optionally resizes and crops @p image from center,
        .   *  subtract @p mean values, scales values by @p scalefactor, swap Blue and Red channels.
        .   *  @param image input image (with 1-, 3- or 4-channels).
        .   *  @param size spatial size for output image
        .   *  @param mean scalar with mean values which are subtracted from channels. Values are intended
        .   *  to be in (mean-R, mean-G, mean-B) order if @p image has BGR ordering and @p swapRB is true.
        .   *  @param scalefactor multiplier for @p image values.
        .   *  @param swapRB flag which indicates that swap first and last channels
        .   *  in 3-channel image is necessary.
        .   *  @param crop flag which indicates whether image will be cropped after resize or not
        .   *  @details if @p crop is true, input image is resized so one side after resize is equal to corresponding
        .   *  dimension in @p size and another one is equal or larger. Then, crop from the center is performed.
        .   *  If @p crop is false, direct resize without cropping and preserving aspect ratio is performed.
        .   *  @returns 4-dimensional Mat with NCHW dimensions order.
    
    blobFromImages(...)
        blobFromImages(images[, scalefactor[, size[, mean[, swapRB[, crop]]]]]) -> retval
        .   @brief Creates 4-dimensional blob from series of images. Optionally resizes and
        .   *  crops @p images from center, subtract @p mean values, scales values by @p scalefactor,
        .   *  swap Blue and Red channels.
        .   *  @param images input images (all with 1-, 3- or 4-channels).
        .   *  @param size spatial size for output image
        .   *  @param mean scalar with mean values which are subtracted from channels. Values are intended
        .   *  to be in (mean-R, mean-G, mean-B) order if @p image has BGR ordering and @p swapRB is true.
        .   *  @param scalefactor multiplier for @p images values.
        .   *  @param swapRB flag which indicates that swap first and last channels
        .   *  in 3-channel image is necessary.
        .   *  @param crop flag which indicates whether image will be cropped after resize or not
        .   *  @details if @p crop is true, input image is resized so one side after resize is equal to corresponding
        .   *  dimension in @p size and another one is equal or larger. Then, crop from the center is performed.
        .   *  If @p crop is false, direct resize without cropping and preserving aspect ratio is performed.
        .   *  @returns 4-dimansional Mat with NCHW dimensions order.
    
imagesFromBlob(...)
        imagesFromBlob(blob_[, images_]) -> images_
        .   @brief Parse a 4D blob and output the images it contains as 2D arrays through a simpler data structure
        .   *  (std::vector<cv::Mat>).
        .   *  @param[in] blob_ 4 dimensional array (images, channels, height, width) in floating point precision (CV_32F) from
        .   *  which you would like to extract the images.
        .   *  @param[out] images_ array of 2D Mat containing the images extracted from the blob in floating point precision
        .   *  (CV_32F). They are non normalized neither mean added. The number of returned images equals the first dimension
        .   *  of the blob (batch size). Every image has a number of channels equals to the second dimension of the blob (depth).
    
    readNet(...)
        readNet(model[, config[, framework]]) -> retval
        .   * @brief Read deep learning network represented in one of the supported formats.
        .   * @param[in] model Binary file contains trained weights. The following file
        .   *                  extensions are expected for models from different frameworks:
        .   *                  * `*.caffemodel` (Caffe, http://caffe.berkeleyvision.org/)
        .   *                  * `*.pb` (TensorFlow, https://www.tensorflow.org/)
        .   *                  * `*.t7` | `*.net` (Torch, http://torch.ch/)
        .   *                  * `*.weights` (Darknet, https://pjreddie.com/darknet/)
        .   *                  * `*.bin` (DLDT, https://software.intel.com/openvino-toolkit)
        .   * @param[in] config Text file contains network configuration. It could be a
        .   *                   file with the following extensions:
        .   *                  * `*.prototxt` (Caffe, http://caffe.berkeleyvision.org/)
        .   *                  * `*.pbtxt` (TensorFlow, https://www.tensorflow.org/)
        .   *                  * `*.cfg` (Darknet, https://pjreddie.com/darknet/)
        .   *                  * `*.xml` (DLDT, https://software.intel.com/openvino-toolkit)
        .   * @param[in] framework Explicit framework name tag to determine a format.
        .   * @returns Net object.
        .   *
        .   * This function automatically detects an origin framework of trained model
        .   * and calls an appropriate function such @ref readNetFromCaffe, @ref readNetFromTensorflow,
        .   * @ref readNetFromTorch or @ref readNetFromDarknet. An order of @p model and @p config
        .   * arguments does not matter.
    
    readNetFromCaffe(...)
        readNetFromCaffe(prototxt[, caffeModel]) -> retval
        .   @brief Reads a network model stored in <a href="http://caffe.berkeleyvision.org">Caffe</a> framework's format.
        .   * @param prototxt   path to the .prototxt file with text description of the network architecture.
        .   * @param caffeModel path to the .caffemodel file with learned network.
        .   * @returns Net object.
    
    readNetFromDarknet(...)
        readNetFromDarknet(cfgFile[, darknetModel]) -> retval
        .   @brief Reads a network model stored in <a href="https://pjreddie.com/darknet/">Darknet</a> model files.
        .   *  @param cfgFile      path to the .cfg file with text description of the network architecture.
        .   *  @param darknetModel path to the .weights file with learned network.
        .   *  @returns Network object that ready to do forward, throw an exception in failure cases.
        .   *  @returns Net object.
    
    readNetFromModelOptimizer(...)
        readNetFromModelOptimizer(xml, bin) -> retval
        .   @brief Load a network from Intel's Model Optimizer intermediate representation.
        .   *  @param[in] xml XML configuration file with network's topology.
        .   *  @param[in] bin Binary file with trained weights.
        .   *  @returns Net object.
        .   *  Networks imported from Intel's Model Optimizer are launched in Intel's Inference Engine
        .   *  backend.
  
    readNetFromTensorflow(...)
        readNetFromTensorflow(model[, config]) -> retval
        .   @brief Reads a network model stored in <a href="https://www.tensorflow.org/">TensorFlow</a> framework's format.
        .   * @param model  path to the .pb file with binary protobuf description of the network architecture
        .   * @param config path to the .pbtxt file that contains text graph definition in protobuf format.
        .   *               Resulting Net object is built by text graph using weights from a binary one that
        .   *               let us make it more flexible.
        .   * @returns Net object.
    readNetFromTorch(...)
        readNetFromTorch(model[, isBinary]) -> retval
        .   *  @brief Reads a network model stored in <a href="http://torch.ch">Torch7</a> framework's format.
        .   *  @param model    path to the file, dumped from Torch by using torch.save() function.
        .   *  @param isBinary specifies whether the network was serialized in ascii mode or binary.
        .   *  @returns Net object.
        .   *
        .   *  @note Ascii mode of Torch serializer is more preferable, because binary mode extensively use `long` type of C language,
        .   *  which has various bit-length on different systems.
        .   *
        .   * The loading file must contain serialized <a href="https://github.com/torch/nn/blob/master/doc/module.md">nn.Module</a> object
        .   * with importing network. Try to eliminate a custom objects from serialazing data to avoid importing errors.
        .   *
        .   * List of supported layers (i.e. object instances derived from Torch nn.Module class):
        .   * - nn.Sequential
        .   * - nn.Parallel
        .   * - nn.Concat
        .   * - nn.Linear
        .   * - nn.SpatialConvolution
        .   * - nn.SpatialMaxPooling, nn.SpatialAveragePooling
        .   * - nn.ReLU, nn.TanH, nn.Sigmoid
        .   * - nn.Reshape
        .   * - nn.SoftMax, nn.LogSoftMax
        .   *
        .   * Also some equivalents of these classes from cunn, cudnn, and fbcunn may be successfully imported.
    readTorchBlob(...)
        readTorchBlob(filename[, isBinary]) -> retval
        .   @brief Loads blob which was serialized as torch.Tensor object of Torch7 framework.
        .   *  @warning This function has the same limitations as readNetFromTorch().
    
    shrinkCaffeModel(...)
        shrinkCaffeModel(src, dst[, layersTypes]) -> None
        .   @brief Convert all weights of Caffe network to half precision floating point.
        .   * @param src Path to origin model from Caffe framework contains single
        .   *            precision floating point weights (usually has `.caffemodel` extension).
        .   * @param dst Path to destination model with updated weights.
        .   * @param layersTypes Set of layers types which parameters will be converted.
        .   *                    By default, converts only Convolutional and Fully-Connected layers'
        .   *                    weights.
        .   *
        .   * @note Shrinked model has no origin float32 weights so it can't be used
        .   *       in origin Caffe framework anymore. However the structure of data
        .   *       is taken from NVidia's Caffe fork: https://github.com/NVIDIA/caffe.
        .   *       So the resulting model may be used there.

```

**Comment by dkurt** [comment]
@alperenkirimer, please use corresponding script from the same version of OpenCV: https://github.com/opencv/opencv/tree/3.4.2/samples/dnn.

**Comment by alperenkirimer** [comment]
@dkurt Thanks for the quick reply, the sample script worked. However I think the tutorial I mentioned above requires a little update since the script at the tutorial and this one are not exactly the same.

**Comment by zjbabylove** [comment]
@alperenkirimer 
Hi，I get an same error as you, and I download the corresponding script:  https://github.com/opencv/opencv/tree/3.4.2/samples/dnn
Then I use frozen_inference_graph.pb file and tf_text_graph_ssd.py script ，generate a graph.pbtxt file, and use graph.pbtxt file and frozen_inference_graph.pb file to test in opencv, and the detection accracy is very low。but if i use the origional graph.pbtxt， the accracy is ok。why？ Am I wrong？
Very appreciate for your reply!!!~~~

**Comment by alperenkirimer** [comment]
@zjbabylove Hello, you may want to read [this post](http://answers.opencv.org/question/195906/dnn-low-accuracy-on-tensorflow-mobilenet-model/). You need to set a scale factor to your detection code according to the model you have used. If memory serves right, it was 1/127.5 for ssd models. Otherwise you are very likely to get low accuracy.
