### ISSUE TITLE
Failed to install opencv (Mac brew) 

### ISSUE THREAD

**Issue by unionTime** [opencv/opencv#12557]
OpenCV => 3.1
Operating System / Platform => Mac OS 10.13.5
Compiler => cmake

Error messages:
```
==> Installing dependencies for opencv: python, numpy, tbb
==> Installing opencv dependency: python
Warning: Building python from source:
  The bottle needs the Apple Command Line Tools to be installed.
  You can install them, if desired, with:
    xcode-select --install

==> Downloading https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz

Already downloaded: /Users/union/Library/Caches/Homebrew/python-3.7.0.tar.xz
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:102:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:140:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1097:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/usr/local/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:111:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:108:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:189:in `<main>'
```
How can I solve this problem? thanks

**Comment by alalek** [comment]
This is wrong issue tracker: there is no homebrew support.
