### ISSUE TITLE
I got a CvException when I called Utils.bitmapToMat

### ISSUE THREAD

**Issue by wuyajun19900627** [opencv/opencv#12915]
##### System information (version)

- OpenCV => 3.4
- Operating System / Platform => Windows 64 Bit
- Compiler =>Android Studio 2.3.3

##### Detailed description

I got a CvException when I called Utils.bitmapToMat.
Here is the log:
CvException [org.opencv.core.CvException: /Volumes/Linux/builds/master_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:33: error: (-215) info.format == ANDROID_BITMAP_FORMAT_RGBA_8888 || info.format == ANDROID_BITMAP_FORMAT_RGB_565 in function void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean)
]
	at org.opencv.android.Utils.nBitmapToMat2(Native Method)
	at org.opencv.android.Utils.bitmapToMat(:93)
	at org.opencv.android.Utils.bitmapToMat(:102)
	at com.hmct.ai.library.spacemanager.b.la(:191)
	at com.hmct.ai.library.spacemanager.b.lc(:79)
	at com.hmct.ai.library.spacemanager.f.run(:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

My codes are as follows:
            Bitmap bitmap = null;
            float srcWidth = 0;
            float srcHeight = 0;
            try {
                FileInputStream fis = new FileInputStream(image.data);
                BitmapFactory.Options options = new BitmapFactory.Options();
                options.inJustDecodeBounds = true;
                BitmapFactory.decodeFileDescriptor(fis.getFD(), null, options);
                srcWidth = options.outWidth;
                srcHeight = options.outHeight;
                int inSampleSize = 1;
                options.inJustDecodeBounds = false;

                if (srcHeight > 850 || srcWidth > 850) {
                    if (srcWidth > srcHeight) {
                        inSampleSize = Math.round(srcHeight / 850);
                    } else {
                        inSampleSize = Math.round(srcWidth / 850);
                    }
                }
                Log.i("1024","inSampleSize = " + inSampleSize);
                options.inSampleSize = inSampleSize;
                bitmap = BitmapFactory.decodeFileDescriptor(fis.getFD(), null, options);
                saveBitmap(bitmap);
            } catch (Exception e) {
                e.printStackTrace();
            }
            Mat matGrey = new Mat();
            Mat matSrc = new Mat(bitmap.getHeight(),bitmap.getWidth(),CV_8UC4);
            Utils.bitmapToMat(bitmap,matSrc);

##### Steps to reproduce

This CvException  appears randomly

**Comment by wuyajun19900627** [comment]
Can somebody help me please? It is an emergency.
