### ISSUE TITLE
python: gen2.py generates constructors for abstract interfaces 

### ISSUE THREAD

**Issue by berak** [opencv/opencv#13022]
- OpenCV => 3.4 / master (probably all 3.x versions)
- Operating System / Platform => Windows 64 Bit
- Compiler => python3.5, opencv3.4.3 (from pip here)

##### Detailed description
we *should* use `XXX_create()` functions, but folks will try to use `XXX()` instead , 
leading to cryptic errors:

```
>>> img = np.array((2,2),np.uint8) # a dummy img, just for demo purpose
>>> o = cv2.ORB()                  # this should not be possible, but it is !
>>> o.detect(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Incorrect type of self (must be 'Feature2D' or its derivative)
>>> type(o)                        # python thinks, everything is ok here ;(
<class 'cv2.ORB'>
>>> isinstance(o, cv2.Feature2D)   # same delusion
True
>>>
>>> s = cv2.xfeatures2d.SIFT()     # proper error.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2.xfeatures2d' has no attribute 'SIFT'
>>> s = cv2.xfeatures2d_SIFT()     # but uhhh !
>>> s.detect(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Incorrect type of self (must be 'Feature2D' or its derivative)
>>> 
>>> c = cv2.CLAHE()                # here, too !
>>> c.apply(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Incorrect type of self (must be 'CLAHE' or its derivative)

```

**Comment by LaurentBerger** [comment]
> we _should_ use `XXX_create()` functions, but folks will try to use `XXX()`

yes but we can use too 
```
o = cv.ORB.create(500)
img=cv.imread('g:/lib/opencv/samples/data/lena.jpg')
x=o.detect(img)
# OR with kaze
o = cv.KAZE.create(500)
img=cv.imread('g:/lib/opencv/samples/data/lena.jpg')
x=o.detect(img)
# but not with surf
o = cv.xfeatures2d.SURF.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cv2.xfeatures2d' has no attribute 'SURF'
```
Can we use safely ORB.create  ?
