### ISSUE TITLE
HoughCircles: Unknown exception

### ISSUE THREAD

**Issue by BullyWiiPlaza** [opencv/opencv#13039]
I'm using [`4.0.0-beta`](https://opencv.org/releases.html) using the Java bindings. A user has reported the following exception when using the `HoughCircles` method:

```
Caused by: java.lang.Exception: unknown exception
	at org.opencv.imgproc.Imgproc.HoughCircles_0(Native Method)
	at org.opencv.imgproc.Imgproc.HoughCircles(Imgproc.java:1422)
        ...
```

This is the first and only time it happened so it's probably not reproducible since my code using Hough circles generally works:
```
public static Mat detectCircles(String imageFilePath, boolean showImage) throws InvocationTargetException, InterruptedException
{
	val sourceImage = imread(imageFilePath, IMREAD_COLOR);

	// Convert the image to gray
	val gray = new Mat();
	cvtColor(sourceImage, gray, COLOR_BGR2GRAY);

	// Apply a median blur to reduce noise and avoid false circle detection
	medianBlur(gray, gray, 5);

	val circles = getCircles(gray);
	drawRedCircles(sourceImage, circles);

	if (showImage)
	{
		invokeAndWait(() -> imshow("Detected Circles", sourceImage));
		waitKey();
	}

	return circles;
}

private static void drawRedCircles(Mat sourceImage, Mat circles)
{
	for (var columnIndex = 0; columnIndex < circles.cols(); columnIndex++)
	{
		val rectangles = circles.get(0, columnIndex);
		val center = new Point(round(rectangles[0]), round(rectangles[1]));

		// circle center
		circle(sourceImage, center, 1, new Scalar(0, 100, 100), 3, 8, 0);

		// circle outline
		val radius = (int) round(rectangles[2]);
		circle(sourceImage, center, radius, new Scalar(255, 0, 255), 3, 8, 0);
	}
}

private static Mat getCircles(Mat image)
{
	val circles = new Mat();
	HoughCircles(image, circles, HOUGH_GRADIENT, 1.0,
			(double) image.rows() / 16,
			100.0, 30.0, 10, 30);
	return circles;
}
```

Can someone tell me more about this issue and if it's a bug which could be fixed?
Thank you!

**Comment by BullyWiiPlaza** [comment]
The same user got a similar exception by the same piece of code as follows:

```
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.0.0-beta) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\canny.cpp:1059: error: (-215:Assertion failed) _dx.sameSize(_dy) in function 'cv::Canny'
]
	at org.opencv.imgproc.Imgproc.HoughCircles_0(Native Method)
	at org.opencv.imgproc.Imgproc.HoughCircles(Imgproc.java:1422)
```

Again I assume this falsely triggered since he's running the same tasks as me and other users. I never got that exception nor do I know any other bug reports in that regard. It could be related to an out of memory error since he only has 4GB RAM but again, I would expect a more fitting error message if that's the cause.
