### ISSUE TITLE
4.0-beta Stack guard error when using the library inside a jar running under docker openjdk

### ISSUE THREAD

**Issue by blackholegalaxy** [opencv/opencv#13048]
##### System information (version)

- OpenCV => 4.0-beta
- Operating System / Platform => Debian jessie
- Compiler => using maven compiled version from Clojure dependencies

##### Detailed description

We tried to run a small clojure program requiring opencv as dependencies:

```
 :dependencies [               
    [opencv/opencv "4.0.0-beta"]
    [opencv/opencv-native "4.0.0-beta"]
    ...
```

Building our jar is ok. 
Trying to run the jar from docker using `openjdk` breaks:

```
OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/nativelib-loader_8850658391695168/libopencv_java400.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5697)
        at clojure.core$load_one.invoke(core.clj:5692)
        at clojure.core$load_lib$fn__5626.invoke(core.clj:5737)
        at clojure.core$load_lib.invokeStatic(core.clj:5736)
        at clojure.core$load_lib.doInvoke(core.clj:5717)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$load_libs.invokeStatic(core.clj:5774)
        at clojure.core$load_libs.doInvoke(core.clj:5758)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:648)
        at clojure.core$require.invokeStatic(core.clj:5796)
        at clojure.core$require.doInvoke(core.clj:5796)
        at clojure.lang.RestFn.invoke(RestFn.java:457)
        at indexation.image_processing$loading__5569__auto____36.invoke(image_processing.clj:1)
        at indexation.image_processing__init.load(Unknown Source)
        at indexation.image_processing__init.<clinit>(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at clojure.lang.RT.classForName(RT.java:2168)
        at clojure.lang.RT.classForName(RT.java:2177)
        at clojure.lang.RT.loadClassForName(RT.java:2196)
        at clojure.lang.RT.load(RT.java:443)
        at clojure.lang.RT.load(RT.java:419)
        at clojure.core$load$fn__5677.invoke(core.clj:5893)
        at clojure.core$load.invokeStatic(core.clj:5892)
        at clojure.core$load.doInvoke(core.clj:5876)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.Util.loadWithClass(Util.java:250)
        at indexation.image_processing.<clinit>(Unknown Source)
Caused by: java.io.IOException: Couldn't load library library opencv_java400
        at org.scijava.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
        at opencv4.core__init.load(Unknown Source)
        at opencv4.core__init.<clinit>(Unknown Source)
        ... 42 more
```

**Comment by alalek** [comment]
Please attach used:
- CMake options
- CMake stdout
- or docker file with reproducer

**Comment by blackholegalaxy** [comment]
Resolved by itself after pulling my dependencies again.
