### ISSUE TITLE
Installation of javascript version with build_js.py fails to make opencv.js

### ISSUE THREAD

**Issue by edward-ij** [opencv/opencv#13099]
#### System information (version)

- OpenCV => 3.4.3
- Operating System / Platform => Windows 64 Bit
- emcc => 1.38.18

##### Detailed description

In the master version downloaded from Github and Version 3.4 from https://opencv.org/releases.html the build_js.py script fails after calling  `execute(cmd)` in `builder.config()` with the error `the system cannot find the file specified`. The file in question is already running which explains why it can't find it but I am not sure why it should be looking for it in the first place.
 
##### Steps to reproduce

Download opencv from github and unzip
locate `build_js.py` and type into the command prompt `python "<opencv_source_location>\platforms\js\build_js.py" build_js`

I have also tried

    cd <opencv_source_location>
    python platforms/js/build_js.py" build_js`

which fails every time as well.

The version on https://opencv.org/releases.html has some other issues which have been sorted on the github release but when fixed that version doesn't work either.

``` .sh    
python "D:\Program Files\opencv\platforms\js\build_js.py" build_js
Args: Namespace(build_dir='build_js', build_doc=False, build_test=False, build_wasm=False, clean_build_dir=False, config_only=False, disable_wasm=False, emscripten_dir='D:/Program Files/emsdk/emscripten/1.38.18', enable_exception=False, opencv_dir='D:\\Program Files\\opencv', skip_config=False)
Check dir D:\Program Files\opencv\build_js (create: True, clean: False)
Check dir D:\Program Files\opencv (create: False, clean: False)
Check dir D:\Program Files\emsdk\emscripten\1.38.18 (create: False, clean: False)
=====
===== Config OpenCV.js build for default target
=====
Executing: ['cmake', '-DCMAKE_BUILD_TYPE=Release', "- 
DCMAKE_TOOLCHAIN_FILE='D:\\Program 
Files\\emsdk\\emscripten\\1.38.18\\cmake\\Modules\\Platform\\Emscripten.cmake'", "-DCPU_BASELINE=''", "-DCPU_DISPATCH=''", '-DCV_TRACE=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DWITH_1394=OFF', '-DWITH_ADE=OFF', '-DWITH_VTK=OFF', '-DWITH_EIGEN=OFF', '-DWITH_FFMPEG=OFF', '-DWITH_GSTREAMER=OFF', '-DWITH_GTK=OFF', '-DWITH_GTK_2_X=OFF', '-DWITH_IPP=OFF', '-DWITH_JASPER=OFF', '-DWITH_JPEG=OFF', '-DWITH_WEBP=OFF', '-DWITH_OPENEXR=OFF', '-DWITH_OPENGL=OFF', '-DWITH_OPENVX=OFF', '-DWITH_OPENNI=OFF', '-DWITH_OPENNI2=OFF', '-DWITH_PNG=OFF', '-DWITH_TBB=OFF', '-DWITH_PTHREADS_PF=OFF', '-DWITH_TIFF=OFF', '-DWITH_V4L=OFF', '-DWITH_OPENCL=OFF', '-DWITH_OPENCL_SVM=OFF', '-DWITH_OPENCLAMDFFT=OFF', '-DWITH_OPENCLAMDBLAS=OFF', '-DWITH_GPHOTO2=OFF', '-DWITH_LAPACK=OFF', '-DWITH_ITT=OFF', '-DBUILD_ZLIB=ON', '-DBUILD_opencv_apps=OFF', '-DBUILD_opencv_calib3d=ON', '-DBUILD_opencv_dnn=ON', '-DBUILD_opencv_features2d=ON', '-DBUILD_opencv_flann=ON', '-DBUILD_opencv_gapi=OFF', '-DBUILD_opencv_ml=OFF', '-DBUILD_opencv_photo=OFF', '-DBUILD_opencv_imgcodecs=OFF', '-DBUILD_opencv_shape=OFF', '-DBUILD_opencv_videoio=OFF', '-DBUILD_opencv_videostab=OFF', '-DBUILD_opencv_highgui=OFF', '-DBUILD_opencv_superres=OFF', '-DBUILD_opencv_stitching=OFF', '-DBUILD_opencv_java=OFF', '-DBUILD_opencv_js=ON', '-DBUILD_opencv_python2=OFF', '-DBUILD_opencv_python3=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_PACKAGE=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', 'D:\\Program Files\\opencv']
Traceback (most recent call last):
File "D:\Program Files\opencv\platforms\js\build_js.py", line 224, in <module>
builder.config()
File "D:\Program Files\opencv\platforms\js\build_js.py", line 164, in config
execute(cmd)
File "D:\Program Files\opencv\platforms\js\build_js.py", line 25, in execute
raise Fail("Execution failed: %d / %s" % (e.errno, e.strerror))
__main__.Fail: Execution failed: 2 / The system cannot find the file specified
```

**Comment by alalek** [comment]
> Executing: 'cmake'

> The system cannot find the file specified

Message is clear enough. You must install `cmake` build tool and properly add it into PATH.
