### ISSUE TITLE
Input layer not found when run DNN object detection tutorial with SSD model

### ISSUE THREAD

**Issue by ChiFang** [opencv/opencv#13246]
##### System information (version)
- OpenCV => 3.4.3
- Operating System / Platform => Ubuntu 16
- Compiler => install by pip

##### Detailed description

I try to run the tutorial with python in this official [link](https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API)

I use [MobileNet-SSD v1(2017_11_17)](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz) downloaded from the wiki page

when I load the .pb graph error shows as following:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cvNet = cv.dnn.readNet('opt_graph.pb')
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: Preprocessor/map/while/NextIteration_1 in function 'connect'
```

I have tried to optimize my .pb like  Troubleshooting with following code but still crash with same error:
```
python ~/tensorflow/tensorflow/python/tools/optimize_for_inference.py \
  --input frozen_inference_graph.pb \
  --output opt_graph.pb \
  --input_names image_tensor \
  --output_names "num_detections,detection_scores,detection_boxes,detection_classes" \
  --placeholder_type_enum 4 \
  --frozen_graph
```
any suggestion?

##### Steps to reproduce
```
import cv2 as cv

# cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'ssd_mobilenet_v1_coco_2017_11_17.pbtxt')
# cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb')
cvNet = cv.dnn.readNet('opt_graph.pb')

img = cv.imread('dog.jpg')
rows = img.shape[0]
cols = img.shape[1]
cvNet.setInput(cv.dnn.blobFromImage(img, size=(300, 300), swapRB=True, crop=False))
cvOut = cvNet.forward()

for detection in cvOut[0,0,:,:]:
    score = float(detection[2])
    if score > 0.3:
        left = detection[3] * cols
        top = detection[4] * rows
        right = detection[5] * cols
        bottom = detection[6] * rows
        cv.rectangle(img, (int(left), int(top)), (int(right), int(bottom)), (23, 230, 210), thickness=2)

cv.imshow('img', img)
cv.waitKey()
```
-->

**Comment by dkurt** [comment]
@ChiFang, Cannot reproduce it using both `.pb` and `.pbtxt` files in `readNet`.

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cvNet = cv.dnn.readNet('opt_graph.pb')
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_importer.cpp:495: error: (-2:Unspecified error) Input layer not found: Preprocessor/map/while/NextIteration_1 in function 'connect'
```

Which error do you have with
```python
cvNet = cv.dnn.readNetFromTensorflow('frozen_inference_graph.pb', 'ssd_mobilenet_v1_coco_2017_11_17.pbtxt')
```
?

**Comment by ChiFang** [comment]
Hi @dkurt 
if I use 
```
cvNet = cv.dnn.readNetFromTensorflow('opt_graph.pb', 'ssd_mobilenet_v1_coco_2017_11_17.pbtxt')
```
instead of 
```
cvNet = cv.dnn.readNet('opt_graph.pb')
```

the error msg change into
```
[libprotobuf ERROR /io/opencv/3rdparty/protobuf/src/google/protobuf/text_format.cc:288] Error parsing text-format tensorflow.GraphDef: 7:1: Expected identifier, got: <
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    cvNet = cv.dnn.readNetFromTensorflow('opt_graph.pb', 'ssd_mobilenet_v1_coco_2017_11_17.pbtxt')
cv2.error: OpenCV(3.4.3) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:56: error: (-2:Unspecified error) FAILED: ReadProtoFromTextFile(param_file, param). Failed to parse GraphDef file: ssd_mobilenet_v1_coco_2017_11_17.pbtxt in function 'ReadTFNetParamsFromTextFileOrDie'
```

**Comment by ChiFang** [comment]
sorry @dkurt  I found that ssd_mobilenet_v1_coco_2017_11_17.pbtxt crash when I use wget...
after fix .pbtxt, it work fine with "readNetFromTensorflow"

**Comment by dkurt** [comment]
@ChiFang, because it's designed in this way. TensorFlow graphs consist from simple nodes and for such custom procedures as prior boxes generation or non maximum suppression it takes about 3000 nodes. However OpenCV deep learning module manages the same ops by several layers.

Please close an issue if there is no problem anymore.
