### ISSUE TITLE
VideoCapture::read() returns success when camera disconnected

### ISSUE THREAD

**Issue by fogelton** [opencv/opencv#14044]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description

When a camera is unplugged the first time it returns false and empty frame, but the second time it returns success and a not empty frame. My desire was to handle cheap cameras which can deliver empty frames. I would expect to get false and empty frame even for further read calls.

##### Steps to reproduce
...
m_camera.open(0);
bool success=m_camera.read(m_originalFrame);
    if(!success || m_originalFrame.empty())
    {
        success=m_camera.read(m_originalFrame);
        if(!success || m_originalFrame.empty())
        {
          m_camera.release();
...

**Comment by LaurentBerger** [comment]
I cannot reproduce using your sample  (windows 10 win 64 in debug)
there is no camera plug on my computer 

```
        VideoCapture m_camera;
        Mat m_originalFrame;

        m_camera.open(0);
        bool success = m_camera.read(m_originalFrame);
        if (!success || m_originalFrame.empty())
        {
            cout << "First non success\n";
            success = m_camera.read(m_originalFrame);
            if (!success || m_originalFrame.empty())
            {
                cout << "second non success\n";
                m_camera.release();
            }
        }

```

```
[ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); GSTREAMER(990); MSMF(980); DSHOW(970); CV_IMAGES(960); CV_MJPEG(950)
[ INFO:0] VideoIO pluigin (GSTREAMER): glob is 'opencv_videoio_gstreamer*.dll', 1 location(s)
[ INFO:0]     - G:\Lib\install\opencv\x64\vc15\bin: 0
[ INFO:0] Found 0 plugin(s) for GSTREAMER
First non success
second non success

```

**Comment by fogelton** [comment]
Please plug int your camera, start some app to receive and show frames and then disconnect your camera to reproduce the bug.

**Comment by fogelton** [comment]
my camera backend is MSMF

**Comment by LaurentBerger** [comment]
May be a good example can help to reproduce your problem : 

```
void main()
{
    {
        VideoCapture m_camera;
        Mat m_originalFrame;

        m_camera.open(0+CAP_MSMF);
        bool success = m_camera.read(m_originalFrame);
        if (success )
        {
            cout << "Success\n";
            cout << "Please unplugged your camera \n";
            imshow("UNplugged your camera", m_originalFrame);
            waitKey();
            success = m_camera.read(m_originalFrame);
            if (!success || m_originalFrame.empty())
            {
                cout << "second non success\n";
                m_camera.release();
            }
            else
            {
                cout << "If camera is unplugged you shouldn't read this message";
            }
        }
    }
    return;

``` 

Results when I activate "UNplugged your camera" window
```

[ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); GSTREAMER(990); MSMF(980); DSHOW(970); CV_IMAGES(960); CV_MJPEG(950)
Success
Please unplugged your camera
[ WARN:1] videoio(MSMF): OnReadSample() is called with error status: -1072873822
[ WARN:1] videoio(MSMF): async ReadSample() call is failed with error status: -1072873822
[ WARN:0] videoio(MSMF): can't grab frame. Error: -1072873822
second non success
[ WARN:0] terminating async callback
```
when window is not activate (console window is active) : 

```
[ INFO:0] VIDEOIO: Enabled backends(6, sorted by priority): FFMPEG(1000); GSTREAMER(990); MSMF(980); DSHOW(970); CV_IMAGES(960); CV_MJPEG(950)
Success
Please unplugged your camera
If camera is unplugged you shouldn't read this message[ WARN:0] terminating async callback

C:\Users\Laurent\Documents\Visual Studio 2013\ANN_REGRESSION\build\Debug\ANN_Regression.exe (process 11540) exited with code 0.
Press any key to close this window . . .
```

**Comment by fogelton** [comment]
Thanks for sample, I adjusted it, for the bug I report
void main()
{
    {
        VideoCapture m_camera;
        Mat m_originalFrame;

        m_camera.open(0+CAP_MSMF);
        bool success = m_camera.read(m_originalFrame);
        if (success )
        {
            cout << "Success\n";
            cout << "Please unplugged your camera \n";
            imshow("UNplugged your camera", m_originalFrame);
            waitKey();
            success = m_camera.read(m_originalFrame);
            if (!success || m_originalFrame.empty())
            {
                cout << "second non success\n";
		success = m_camera.read(m_originalFrame);
		if (!success || m_originalFrame.empty())
            	{
			cout << "second non success\n";
                	m_camera.release();
 	        }
		else
            	{
                	cout << "this message is shown, but it should not be (at least I would assumed).";
            	}
            }
            else
            {
                cout << "If camera is unplugged you shouldn't read this message";
            }
        }
    }
    return;
}

**Comment by Wtcheesecakes** [comment]
im having an issue with opencv also it seems to try and reach my original directory
```

C:\Users\admin\AppData\Local>rat.exe
Traceback (most recent call last):
  File "rat.py", line 2, in <module>
  File "c:\users\thetr\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\cv2\__init__.py", line 3, in <module>
ImportError: DLL load failed: The specified module could not be found.
[1292] Failed to execute script rat
```

**Comment by vrozin** [comment]
Hello, may I take a look at this?

**Comment by mshabunin** [comment]
Can not reproduce with latest _master_ branch version. Is this issue still valid?

**Comment by LaurentBerger** [comment]
today : 

```
[ INFO:0] global G:\Lib\opencv\modules\videoio\src\videoio_registry.cpp (187) cv::`anonymous-namespace'::VideoBackendRegistry::VideoBackendRegistry VIDEOIO: Enabled backends(7, sorted by priority): FFMPEG(1000); GSTREAMER(990); INTEL_MFX(980); MSMF(970); DSHOW(960); CV_IMAGES(950); CV_MJPEG(940)
Success
Please unplugged your camera
If camera is unplugged you shouldn't read this message[ WARN:0] global G:\Lib\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback

C:\Users\Laurent\Documents\Visual Studio 2013\test100000\build\Debug\test100000.exe (process 10980) exited with code 0.
Press any key to close this window . . .
```

with 
```
General configuration for OpenCV 4.2.0-dev =====================================
  Version control:               4.1.2-610-g57c9991413

```
