### ISSUE TITLE
_emval_take_value has unknown type N10emscripten11memory_viewIhEE

### ISSUE THREAD

**Issue by anshkumar** [opencv/opencv#14119]
`OpenCV.js` is throwing me following exception on reading an image object :

```
Uncaught BindingError {name: "BindingError", message: "_emval_take_value has unknown type N10emscripten11memory_viewIhEE", stack: "BindingError: _emval_take_value has unknown type N…129f2c92.js?body=1:24:7962387), <anonymous>:4:12)"}

message: "_emval_take_value has unknown type N10emscripten11memory_viewIhEE"

name: "BindingError"

stack: "BindingError: _emval_take_value has unknown type N10emscripten11memory_viewIhEE↵    at BindingError.<anonymous> (http://localhost:3000/assets/opencv.js:24:7943408)↵    at new BindingError (eval at createNamedFunction (http://localhost:3000/assets/opencv.js:24:7943114), <anonymous>:4:34)↵    at throwBindingError (http://localhost:3000/assets/opencv.js:24:7948577)↵    at requireRegisteredType (http://localhost:3000/assets/opencv.js:24:7986052)↵    at __emval_take_value (http://localhost:3000/assets/opencv.js:24:7988959)↵    at wasm-function[132]:145↵    at wasm-function[788]:35↵    at wasm-function[911]:15↵    at http://localhost:3000/assets/opencv.js:24:8020653↵    at dynCall_iii_421 (eval at makeDynCaller (http://localhost:3000/assets/opencv.self-b5be1de1d706ad106aca95693fe410ba68894a41259a42fd2580f6cd129f2c92.js?body=1:24:7962387), <anonymous>:4:12)


throwBindingError | @ | opencv.js:24
-- | -- | --
  | requireRegisteredType | @ | opencv.js:24
  | __emval_take_value | @ | opencv.js:24
  | wasm-function[132] | @ | wasm-0165c052-132:77
  | wasm-function[788] | @ | wasm-0165c052-788:19
  | wasm-function[911] | @ | wasm-0165c052-911:9
  | (anonymous) | @ | opencv.js:24
  | dynCall_iii_421 | @ | VM81946:4
  | get | @ | opencv.self-b5be1de1…9f2c92.js?body=1:24
  | (anonymous) | @ | opencv.js:24
  | (anonymous) | @ | opencv.js:24
  | (anonymous) | @ | VM84114:1


"
```
Why am I getting this error ?

**Comment by BhavitChhatralia** [comment]
@anshkumar did you manage to fix this issue?

**Comment by anshkumar** [comment]
I was using Ruby on Rails(ROR) for my usecase. I was loading the library in a wrong way. To load `OpenCV.js` in ROR, adding `//= require opencv` in the file `app/assets/javascripts/application.js` fixed it.
