### ISSUE TITLE
Request to change the test code(or interface?)

### ISSUE THREAD

**Issue by tegusi** [opencv/opencv#14204]
Hello! I just submitted a [pr](https://github.com/opencv/opencv/pull/14189), and the robot reports errors on *modules/python/test/test_facedetect.py**, as

> Traceback (most recent call last):
  File "/build/precommit_linux64/opencv/modules/python/test/test_facedetect.py", line 55, in test_facedetect
    rects = detect(gray, cascade)
  File "/build/precommit_linux64/opencv/modules/python/test/test_facedetect.py", line 18, in detect
    rects[:,2:] += rects[:,:2]
TypeError: list indices must be integers or slices, not tuple

and the source file is

https://github.com/opencv/opencv/blob/360758e8ae5ebaf94c62f739d37892eae4222df4/modules/python/test/test_facedetect.py#L13-L19

Since the C++ version of this code provides vector<Rect>, the python version should return  LIST OF TUPLES instead of  NUMPY 2D ARRAY as above, which satisfy the consistency of vector convertion between Python and C as well.

https://github.com/opencv/opencv/blob/360758e8ae5ebaf94c62f739d37892eae4222df4/modules/objdetect/src/cascadedetect.cpp#L1351-L1356

Which can be fixed by convert it to numpy array
`rects = np.array(rects)`

##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

**Comment by alalek** [comment]
> should return LIST OF TUPLES

Tuples are almost not usable for future processing (including math-based), so we using `np.array` instead of tuples whenever possible.
So we don't asking users to do this: `rects = np.array(rects)`

**Comment by tegusi** [comment]
However, the reverse conversion(numpy array to vector) doesn't work well(pyopencv_to). In this [issue](https://github.com/opencv/opencv_contrib/issues/1661), after my final pr the original code still fails because of python binding:

`terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0-pre) /home/tegusi/opencv-master/modules/core/src/copy.cpp:254: error: (-215:Assertion failed) channels() == CV_MAT_CN(dtype) in function 'copyTo'
`

corresponds to this:

https://github.com/opencv/opencv/blob/066c074b66c9bdefde1971e099560b164706522e/modules/python/src2/cv2.cpp#L1174-L1176

I've tried my best to solve this problem but failed...I wonder if you know how to solve this problem :(
