### ISSUE TITLE
build_js.py — can't build wasm

### ISSUE THREAD

**Issue by chiboreache** [opencv/opencv#14680]
##### System information (version)
Arch Linux
Everything is bleeding edge

##### Steps to reproduce

```sh
↪ python build_js.py /home --emscripten_dir="/usr/lib/emscripten/" --build_wasm
```

##### Got

```python
Args: Namespace(build_dir='/home', build_doc=False, build_test=False, build_wasm=True, clean_build_dir=False, config_only=False, emscripten_dir='/usr/lib/emscripten/', enable_exception=False, opencv_dir='.../opencv_js/opencv', skip_config=False)
Check dir /home (create: True, clean: False)
Check dir .../opencv_js/opencv (create: False, clean: False)
Check dir /usr/lib/emscripten (create: False, clean: False)
Traceback (most recent call last):
  File ".../opencv_js/opencv/platforms/js/build_js.py", line 220, in <module>
    builder = Builder(args)
  File ".../opencv_js/opencv/platforms/js/build_js.py", line 84, in __init__
    self.emcc_version = determine_emcc_version(self.emscripten_dir)
  File ".../opencv_js/opencv/platforms/js/build_js.py", line 63, in determine_emcc_version
    m = re.match(r'^emcc.*(\d+\.\d+\.\d+)', ret, flags=re.IGNORECASE)
  File "/usr/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by cancerberoSgx** [comment]
Are you using emsdk or arch linux emscripten package  ?  I'm using docker container as documented at the bottom of https://docs.opencv.org/master/d4/da1/tutorial_js_setup.html

It doesn't use --emscripten_dir, just environment variables (see below)

Also I find strange passing /home as build destination folder. I would try giving a non existing folder 

And finally, it actually won't generate .wasm but a .js file with the .wasm embedded as base64 because it¡s using SINGLE_FILE setting. see https://github.com/opencv/opencv/issues/13356 and https://github.com/opencv/opencv/issues/12417

```
docker run --rm --workdir /code -v "$PWD":/code opencv.js printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bcef6cdce7f8
EMSDK=/emsdk_portable
EMSCRIPTEN=/emsdk_portable/sdk
EM_DATA=/emsdk_portable/data
EM_CONFIG=/emsdk_portable/data/.config
EM_CACHE=/emsdk_portable/data/.cache
EM_PORTS=/emsdk_portable/data/.ports
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
HOME=/root
```
