### ISSUE TITLE
MatOfPoint3f fromArray ArrayIndexOutOfBoundsException: length=12; index=24

### ISSUE THREAD

**Issue by goren74** [opencv/opencv#14699]
##### System information (version)
- OpenCV => 3.4.2
- Operating System / Platform => Android (Java) / bug occuring in multiple Android versions

##### Detailed description
App crashing and get following errors when using OpenCV on a specific device (Android 5.1.1, Api22  armeabi-v7a)

`Caused by: java.lang.ArrayIndexOutOfBoundsException: length=12; index=24
        at org.opencv.core.MatOfPoint3f.fromArray(MatOfPoint3f.java:51)
        at org.opencv.core.MatOfPoint3f.<init>(MatOfPoint3f.java:35)`

This is the method in the MatOfPoint3f.java 
`public void fromArray(Point3...a) {
        if(a==null || a.length==0)
            return;
        int num = a.length;
        alloc(num);
        float buff[] = new float[num * _channels];
        for(int i=0; i<num; i++) {
            Point3 p = a[i];
            buff[_channels*i+0] = (float) p.x; <-- crash here
            buff[_channels*i+1] = (float) p.y;
            buff[_channels*i+2] = (float) p.z;
        }
        put(0, 0, buff); //TODO: check ret val!
    }`

##### Steps to reproduce
Crash is happening as soon as I call the fromArray method. Here is my implementation 

`float lSize = 100;
m3FPoints = new MatOfPoint3f(new Point3(-lSize, lSize, 0), new Point3(lSize, lSize, 0));`

**Comment by alalek** [comment]
> 3.4.2

Please try latest code from 3.4 branch.

Please provide minimal reproducer (see [Java tests as example](https://github.com/opencv/opencv/tree/3.4.6/modules/core/misc/java/test)).

**Comment by goren74** [comment]
Thank for the reply, I have done what you have said : 
- Create a Android Test : 
```java
@Test
public void testMatOfPoint3f() {
  float lSize = 100;
  new MatOfPoint3f(new Point3(-lSize, lSize, 0), new Point3(lSize, lSize, 0));
  assertTrue(true);
}

- Downloaded the latest version of OpenCV (3.4.6) and import it on my project. 

Still have the issue.

**Comment by alalek** [comment]
Can't reproduce:
- test: https://github.com/alalek/opencv/commit/issue_14699
- build `opencv_test_java`
- run: `./setup_vars.sh python <opencv_src>/modules/ts/misc/run.py -a -t java --package=core`
- message of intentional failure:
```
expected:<3> but was:<2> 

junit.framework.AssertionFailedError: expected:<3> but was:<2>
at org.opencv.test.core.Point3Test.testMatOfPoint3f(Point3Test.java:110)
at org.opencv.test.OpenCVTestCase.runTest(OpenCVTestCase.java:229)
at org.opencv.test.OpenCVTestCase.runBare(OpenCVTestCase.java:249)
```

**Comment by goren74** [comment]
It is also working with my code on almost all my devices. It is failing only when I run this code on a specific device. I can provide as much information as you need to understand the issue. As said in the first post, my device is running on Android 5.1.1, Api22 armeabi-v7a.

**Comment by alalek** [comment]
Did you try to run OpenCV java tests on that device? Android emulator?
Do you monitor memory consumption? (JVM+native)

**Comment by goren74** [comment]
Yes, all the error I got are obtained only on that device. The test I have mentionned just before was also ran on that device.
I did not try to run on Android Emulator. I have never used JVM but Android Studio allow me to monitor the memory consumption

**Comment by alalek** [comment]
Thank you for updates!
Unfortunately, without a reproducer on our side, we can't investigate this.

"Priority => low" due device-specific issue.
