### ISSUE TITLE
Attribute Error, cv2.dnn

### ISSUE THREAD

**Issue by kat-mcg-lin** [opencv/opencv#14706]
##### System information (version)

- OpenCV => 3.2.0
- Operating System / Platform => ubunto 18.04 
- Compiler => pycharm

##### Detailed description

I have been trying to use cv2 for quite some time now, and it keeps throwing different issues and errors. Originally I had to import via openCV but that wasn't working, and now it somewhat works when importing cv2
The code will say there is no module cv2 but won't throw an error when running- however it will throw an error later on when trying to use a function from cv2

Is this an installation issue? improper library recognition? outdated version?

##### Steps to reproduce

attached is the code i am trying to use
[DistanceToObject.txt](https://github.com/opencv/opencv/files/3248051/DistanceToObject.txt)
line 81 throws this error:
```
Traceback (most recent call last):
  File "/home/ihub/documents/projects_pycharm/DistanceToObject.py", line 81, in <module>
    net = cv2.dnn.readNetFromCAFFE("MobileNetSSD_deploy.prototxt", "MobileNetSSD_deploy.caffemodel")
AttributeError: module 'cv2.dnn' has no attribute 'readNetFromCAFFE'

```

**Comment by dkurt** [comment]
Python is case sensitive. There is no `readNetFromCAFFE` in OpenCV. There is `readNetFromCaffe`.

Please use a forum for usage questions: http://answers.opencv.org/

**Comment by kat-mcg-lin** [comment]
I just changed the cases in the code, and now it throws a very different error:

 ```
OpenCV Error: Unspecified error (FAILED: fs.is_open(). Can't open "MobileNetSSD_deploy.prototxt") in ReadProtoFromTextFile, file /home/nvidia/build_opencv/opencv/modules/dnn/src/caffe/caffe_io.cpp, line 1113
Traceback (most recent call last):
  File "/home/ihub/documents/projects_pycharm/DistanceToObject.py", line 81, in <module>
    net = cv2.dnn.readNetFromCaffe("MobileNetSSD_deploy.prototxt", "MobileNetSSD_deploy.caffemodel")
cv2.error: /home/nvidia/build_opencv/opencv/modules/dnn/src/caffe/caffe_io.cpp:1113: error: (-2) FAILED: fs.is_open(). Can't open "MobileNetSSD_deploy.prototxt" in function ReadProtoFromTextFile
```

also already posted in forum, no responses yet so I thought I might as well try here too...

**Comment by kat-mcg-lin** [comment]
Why did you close the issue??

**Comment by alalek** [comment]
This tracker is for issues and bugs that needs fix in OpenCV.
Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org

---

> fs.is_open(). Can't open "MobileNetSSD_deploy.prototxt"

Are you sure that you need OpenCV developers help to pass file path properly?

**Comment by kat-mcg-lin** [comment]
a little rude, but i understand, sorry for taking up your time

**Comment by dkurt** [comment]
> a little rude, but i understand, sorry for taking up your time

There are some basic rules which we also expect from issues authors (at lest from issue's template). A lot of "How to" issues just make it more complicated for users to solve real problems.

```
Please:

* Read the documentation to test with the latest developer build.
```
> readNetFromCAFFE - well documented method
