### ISSUE TITLE
setNumThreads not honored

### ISSUE THREAD

**Issue by expntly** [opencv/opencv#15277]
##### System information (version)

- OpenCV => 4.1.0
- Operating System / Platform => Linux 4.4.0
- Compiler => See below

##### Detailed description

On a multi-core system, `setNumThreads` doesn't seem to be taken into account.  No matter what I try, my code and dependencies will spawn N threads whenever I call `cv2` functions, where N is the number of cores on the machine.

We're already taking care of parallelism by creating as many processes as we have cores (python code), so we don't need OpenCV to spawn threads on top of that in the background, it only creates more CPU contention.

##### Steps to reproduce

```
>>> import cv2
>>> cv2.setNumThreads(1)
>>> c = cv2.VideoCapture('/path/to/video/file')
```

At this point a `ps -eLf` in another terminal will show as many python threads as there are cores on the machine, instead of only 1 as per `setNumThreads(1)`.

So for instance on a machine with 64 cores, creating 64 processes (e.g. with `multiprocessing.Process`) will create 4096 threads in the background.  Definitely not what we want.  Creating only 1 process and 64 threads results in very poor performance as we have higher level work we need to parallelize.

NB: I've tried `export OMP_NUM_THREADS=1`, it doesn't seem to help either.

---

** SYSTEM AND BUILD INFO (this is a Deep Learning AMI on EC2)**

```bash
$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> print(cv2.getBuildInformation())

General configuration for OpenCV 4.1.0 =====================================
  Version control:               4.1.0

  Extra modules:
    Location (extra):            /io/opencv_contrib/modules
    Version control (extra):     4.1.0

  Platform:
    Timestamp:                   2019-04-11T17:07:54Z
    Host:                        Linux 4.4.0-101-generic x86_64
    CMake:                       3.9.0
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (13 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (27 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2

  C/C++:
    Built as dynamic libs?:      NO
    C++ Compiler:                /usr/lib/ccache/compilers/c++  (ver 4.8.2)
    C++ flags (Release):         -Wl,-strip-all   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -Wl,-strip-all   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Winit-self -Wno-delete-non-virtual-dtor -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/lib/ccache/compilers/cc
    C flags (Release):           -Wl,-strip-all   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -Wl,-strip-all   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wuninitialized -Winit-self -Wno-comment -Wno-missing-field-initializers -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -L/root/ffmpeg_build/lib  -Wl,--gc-sections  
    Linker flags (Debug):        -L/root/ffmpeg_build/lib  -Wl,--gc-sections  
    ccache:                      YES
    Precompiled headers:         NO
    Extra dependencies:          ade /opt/Qt4.8.7/lib/libQtGui.so /opt/Qt4.8.7/lib/libQtTest.so /opt/Qt4.8.7/lib/libQtCore.so /lib64/libz.so /opt/libjpeg-turbo/lib64/libjpeg.a dl m pthread rt
    3rdparty dependencies:       ittnotify libprotobuf libwebp libpng libtiff libjasper IlmImf quirc

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf java js matlab ovis python2 sfm ts viz
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI: 
    QT:                          YES (ver 4.8.7 EDITION = OpenSource)
      QT OpenGL support:         NO
    GTK+:                        NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /lib64/libz.so (ver 1.2.3)
    JPEG:                        /opt/libjpeg-turbo/lib64/libjpeg.a (ver 62)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         build (ver 1.6.36)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 1.7.1)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES
      avcodec:                   YES (58.47.106)
      avformat:                  YES (58.26.101)
      avutil:                    YES (56.26.100)
      swscale:                   YES (5.4.100)
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      NO
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (no extra features)
    Include path:                /io/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /opt/python/cp36-cp36m/bin/python (ver 3.6.8)
    Libraries:                   libpython3.6m.a (ver 3.6.8)
    numpy:                       /opt/python/cp36-cp36m/lib/python3.6/site-packages/numpy/core/include (ver 1.11.3)
    install path:                python

  Python (for build):            /opt/python/cp36-cp36m/bin/python

  Java:                          
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /io/_skbuild/linux-x86_64-3.6/cmake-install
-----------------------------------------------------------------


```

**Comment by alalek** [comment]
> multiprocessing.Process

Forking is not supported and buggy.

> setNumThreads
> cv2.VideoCapture

`setNumThreads()` specifies only number of threads of OpenCV thread pool. Thread pools from underlying libraries FFmpeg/GStreamer/etc are not controlled.

**Comment by expntly** [comment]
@alalek 

> Forking is not supported and buggy.

Fork is the default but I tried `multiprocessing.set_start_method('spawn')` and that didn't help.  Can you clarify what you mean?

> `setNumThreads()` specifies only number of threads of OpenCV thread pool. Thread pools from underlying libraries FFmpeg/GStreamer/etc are not controlled.

Is there a way to tell where those threads are coming from?  Off the top of my head it wasn't just `cv2.VideoCapture` but also `cv2.cvtColor` etc.

It seems strange to spawn all these threads given Python's GIL with CPU-bound tasks.  Unless what's spawning those threads is doing so in non-bytecode land and outside of the GIL's reach obviously.

**Comment by alalek** [comment]
I mean this bug: #5150
`fork()` doesn't care about synchronization primitives, so process state becomes not consistent.


> where those threads are coming from?

`gdb` may help:
```
gdb -ex r --args python ...
... Ctrl+C ...
(gdb) info threads
(gdb) thread apply all bt
... Ctrl+D to exit from gdb ...
```

**Comment by expntly** [comment]
Looks like there are two kinds.

This one from a large program we're running and that I'm trying to debug:
```
Thread 71 (Thread 0x7fff7d774700 (LWP 5088)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fff4f339c6e in ?? () from /home/ubuntu/venv/lib/python3.6/site-packages/cv2/.libs/libavcodec-874f3d51.so.58.47.106
#2  0x00007ffff7bc16ba in start_thread (arg=0x7fff7d774700) at pthread_create.c:333
#3  0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

This one by basically starting a python prompt and merely executing `import cv2`:
```
Thread 2 (Thread 0x7fffeb9bf700 (LWP 5428)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffebfcd5eb in blas_thread_server () from /home/ubuntu/venv/lib/python3.6/site-packages/numpy/core/../.libs/libopenblasp-r0-2ecf47d5.3.7.dev.so
#2  0x00007ffff7bc16ba in start_thread (arg=0x7fffeb9bf700) at pthread_create.c:333
#3  0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by KindRoach** [comment]
Is anyone find the solution to limit thread using by OpenCV/FFmpeg for video decoding? 

I want to decode multi video streams simultaneously and create a python thread for each video stream. 

I'd like to make each thread use only one CPU core. However, by default config, each VideoCapture will create same number of threads as total CPU core on system, which race on all CPU cores and led to a performance drop.

**Comment by xylcbd** [comment]
export OPENCV_FFMPEG_THREADS = 1

**Comment by KindRoach** [comment]
Thanks a lot, it does work!

> export OPENCV_FFMPEG_THREADS = 1
