### ISSUE TITLE
CvException 

### ISSUE THREAD

**Issue by Squarellt** [opencv/opencv#15324]
Caused by: CvException [org.opencv.core.CvException: cv::Exception: OpenCV(3.4.6) C:\build\3_4_winpack-bindings-win64-vc14-static\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
]

**Comment by Squarellt** [comment]
at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
	at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:2347)

**Comment by dkurt** [comment]
Please use a forum http://answers.opencv.org for usage questions of follow issue's template
