### ISSUE TITLE
OOB in opencv_test_face

### ISSUE THREAD

**Issue by c0d3xpl0it** [opencv/opencv#15598]
We found OOB in opencv_test_face binary and OpenCV is complied with clang enabling ASAN.

Below is the output _with_ and _without_ Testdata.

**Build type**: Release
**OpenCV version**: 4.1.2-pre
**OS**: Linux 4.4.0-87-generic #110-Ubuntu
**OpenCV VCS version**: 4.1.1-270-g9f4f900

Without Testdata
```
fuzzer@fuzzer:~/victim/opencv_build/opencv/build/bin$ ./opencv_test_face
CTEST_FULL_OUTPUT
OpenCV version: 4.1.2-pre
OpenCV VCS version: 4.1.1-270-g9f4f900
Build type: Release
Compiler: /usr/local/bin/afl-clang-fast++  (ver 3.8.0)
Parallel framework: pthreads
CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2
Intel(R) IPP version: ippIP AVX2 (l9) 2019.0.0 Gold (-) Jul 24 2018
OpenCL is disabled
TEST: Skip tests with tags: 'mem_6gb', 'verylong'
[==========] Running 21 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from CV_Face_FacemarkAAM
[ RUN      ] CV_Face_FacemarkAAM.can_create_default
[       OK ] CV_Face_FacemarkAAM.can_create_default (0 ms)
[ RUN      ] CV_Face_FacemarkAAM.can_set_custom_detector
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: cascadeandhog/cascades/lbpcascade_frontalface.xml in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkAAM.can_set_custom_detector (0 ms)
[ RUN      ] CV_Face_FacemarkAAM.test_workflow
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/david1.jpg in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkAAM.test_workflow (0 ms)
[----------] 3 tests from CV_Face_FacemarkAAM (1 ms total)

[----------] 3 tests from CV_Face_FacemarkKazemi
[ RUN      ] CV_Face_FacemarkKazemi.can_create_default
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/lbpcascade_frontalface_improved.xml in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkKazemi.can_create_default (1 ms)
[ RUN      ] CV_Face_FacemarkKazemi.can_loadTrainingData
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/lbpcascade_frontalface_improved.xml in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkKazemi.can_loadTrainingData (0 ms)
[ RUN      ] CV_Face_FacemarkKazemi.can_detect_landmarks
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/lbpcascade_frontalface_improved.xml in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkKazemi.can_detect_landmarks (0 ms)
[----------] 3 tests from CV_Face_FacemarkKazemi (1 ms total)

[----------] 3 tests from CV_Face_FacemarkLBF
[ RUN      ] CV_Face_FacemarkLBF.can_create_default
[       OK ] CV_Face_FacemarkLBF.can_create_default (1 ms)
[ RUN      ] CV_Face_FacemarkLBF.can_set_custom_detector
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: cascadeandhog/cascades/lbpcascade_frontalface.xml in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkLBF.can_set_custom_detector (0 ms)
[ RUN      ] CV_Face_FacemarkLBF.test_workflow
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/david1.jpg in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_FacemarkLBF.test_workflow (0 ms)
[----------] 3 tests from CV_Face_FacemarkLBF (1 ms total)

[----------] 5 tests from CV_Face_BIF
[ RUN      ] CV_Face_BIF.can_create_default
[       OK ] CV_Face_BIF.can_create_default (22 ms)
[ RUN      ] CV_Face_BIF.fails_when_zero_bands
[       OK ] CV_Face_BIF.fails_when_zero_bands (1 ms)
[ RUN      ] CV_Face_BIF.fails_when_too_many_bands
[       OK ] CV_Face_BIF.fails_when_too_many_bands (0 ms)
[ RUN      ] CV_Face_BIF.fails_when_zero_rotations
[       OK ] CV_Face_BIF.fails_when_zero_rotations (0 ms)
[ RUN      ] CV_Face_BIF.can_compute
[       OK ] CV_Face_BIF.can_compute (374 ms)
[----------] 5 tests from CV_Face_BIF (397 ms total)

[----------] 1 test from CV_Face_Facemark
[ RUN      ] CV_Face_Facemark.test_utilities
unknown file: Failure
C++ exception with description "OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts.cpp:1015: error: (-2:Unspecified error) OpenCV tests: Can't find required data file: face/david1.jpg in function 'findData'
" thrown in the test body.
[  FAILED  ] CV_Face_Facemark.test_utilities (0 ms)
[----------] 1 test from CV_Face_Facemark (0 ms total)

[----------] 2 tests from CV_Face_SAVELOAD
[ RUN      ] CV_Face_SAVELOAD.use_save
[       OK ] CV_Face_SAVELOAD.use_save (414 ms)
[ RUN      ] CV_Face_SAVELOAD.use_write
[       OK ] CV_Face_SAVELOAD.use_write (346 ms)
[----------] 2 tests from CV_Face_SAVELOAD (760 ms total)

[----------] 4 tests from Face/MACE_
[ RUN      ] Face/MACE_.unsalted/0, where GetParam() = ("david")
[ERROR:0] global /home/fuzzer/victim/opencv_build/opencv/modules/videoio/src/cap.cpp (116) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.1.2-pre) /home/fuzzer/victim/opencv_build/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): tracking/david/data/david.webm in function 'icvExtractPattern'


/home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_mace.cpp:101: Failure
Value of: c.open(vid)
  Actual: false
Expected: true
ASAN:DEADLYSIGNAL
=================================================================
==6511==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000569c61 bp 0x7ffe40593d70 sp 0x7ffe405933e0 T0)
    #0 0x569c60 in cv::Rect_<int>::Rect_(cv::Rect_<int> const&) /home/fuzzer/victim/opencv_build/opencv/modules/core/include/opencv2/core/types.hpp:1832:7
    #1 0x569c60 in opencv_test::(anonymous namespace)::MaceTest::samples(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) /home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_mace.cpp:109
    #2 0x565b99 in opencv_test::(anonymous namespace)::MaceTest::run() /home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_mace.cpp:72:29
    #3 0x563870 in opencv_test::(anonymous namespace)::MACE__unsalted_Test::Body() /home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_mace.cpp:130:36
    #4 0x563157 in opencv_test::(anonymous namespace)::MACE__unsalted_Test::TestBody() /home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_mace.cpp:128:1
    #5 0x5b5b72 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:3917:10
    #6 0x5b5b72 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:3953
    #7 0x5b56e3 in testing::Test::Run() /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:3991:5
    #8 0x5bcd31 in testing::TestInfo::Run() /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:4167:5
    #9 0x5c00b7 in testing::TestCase::Run() /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:4285:5
    #10 0x607494 in testing::internal::UnitTestImpl::RunAllTests() /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:6660:11
    #11 0x60521c in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:3917:10
    #12 0x60521c in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:3953
    #13 0x6049ae in testing::UnitTest::Run() /home/fuzzer/victim/opencv_build/opencv/modules/ts/src/ts_gtest.cpp:6269:10
    #14 0x581836 in RUN_ALL_TESTS() /home/fuzzer/victim/opencv_build/opencv/modules/ts/include/opencv2/ts/ts_gtest.h:22224:10
    #15 0x581836 in main /home/fuzzer/victim/opencv_build/opencv_contrib/modules/face/test/test_main.cpp:41
    #16 0x7fdb2dd0482f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291
    #17 0x438cd8 in _start (/home/fuzzer/victim/opencv_build/opencv/build/bin/opencv_test_face+0x438cd8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/fuzzer/victim/opencv_build/opencv/modules/core/include/opencv2/core/types.hpp:1832:7 in cv::Rect_<int>::Rect_(cv::Rect_<int> const&)
==6511==ABORTING
```

**With Testdata**
All tests are successful and no error is thrown.

**Comment by c0d3xpl0it** [comment]
This also works for **OpenCV version**: 4.1.2-pre
**OpenCV VCS version**: 4.1.1-291-ge2a5a6a

**Comment by alalek** [comment]
Face is **opencv_contrib** module.
All related bugs should be reported into dedicated issue tracker.
I have moved your first report there: https://github.com/opencv/opencv_contrib/issues/2268
