### ISSUE TITLE
cornerSubPix error “(-215:Assertion failed) count >= 0” when using java

### ISSUE THREAD

**Issue by friends110110** [opencv/opencv#15711]
my environment is macos、 java 、 opencv 4.1.2 、intellij and so on ... My code is :

```
goodFeaturesToTrack(basedImg, corners, 20, 0.1, 10, maskMat, 3, false, 0.04);
TermCriteria termCriteria = new TermCriteria(TermCriteria.MAX_ITER+TermCriteria.COUNT, 1, 0.001);
Imgproc.cornerSubPix(basedImg, corners, new Size(5,5), new Size(-1,-1), termCriteria);
```
it throws errors:

```
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.2-pre) /Users/friends/opencv/modules/imgproc/src/cornersubpix.cpp:58: error: (-215:Assertion failed) count >= 0 in function 'cornerSubPix'
]
    at org.opencv.imgproc.Imgproc.cornerSubPix_0(Native Method)
    at org.opencv.imgproc.Imgproc.cornerSubPix(Imgproc.java:4887)
    at cn.com.opencv.ImgProcess.dealContourCharacter(ImgProcess.java:432)
    at cn.com.opencv.ImgProcess.process(ImgProcess.java:276)
    at cn.com.opencv.Controller.main(Controller.java:19)
```
How to correct it ? What does "error: (-215:Assertion failed) count >= 0 " means ?

**Comment by friends110110** [comment]
I have describe very clearly.

**Comment by asmorkalov** [comment]
The assertion is fired because `corners` array is empty.

**Comment by HelenTsvetkova** [comment]
If your `corners` are `double` try to make them `float`
