### ISSUE TITLE
readnetfromtensorflow

### ISSUE THREAD

**Issue by povoss** [opencv/opencv#15774]
##### System information (version)
 Example
- OpenCV => 4.1.1
- Operating System / Platform => Windows 64 Bit
- Compiler => java1.8.21

##### Detailed description

Exception in thread "AWT-EventQueue-0" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) E:\opencv-4.1.1\modules\dnn\src\tensorflow\tf_importer.cpp:544: error: (-2:Unspecified error) Input layer not found: Shape_3 in function 'cv::dnn::dnn4_v20190621::`anonymous-namespace'::TFImporter::connect'
]
	at org.opencv.dnn.Dnn.readNetFromTensorflow_1(Native Method)
	at org.opencv.dnn.Dnn.readNetFromTensorflow(Dnn.java:654)

##### Steps to reproduce
String model_pb_file = System.getProperty("user.dir")+"/frozen_inference_graph.pb";
//		String prototxt = System.getProperty("user.dir")+"/graph.pbtxt";
        Net net = readNetFromTensorflow(model_pb_file);

**Comment by dkurt** [comment]
Closing it unless issue became reproducible
