### ISSUE TITLE
OpenCV Java ... VideoCapture.open(URL) fails while Python3+cv2 is working on Win7.

### ISSUE THREAD

**Issue by ldpgh** [opencv/opencv#15922]
### System information (version)
- OpenCV => 4.1.1 (Java, opencv-python)
- Operating System / Platform => Windows 64 Bit / Win7Pro
- Compiler => unknown ... using binaries provided by OpenCV, PyPi
   - Python3.7.4+cv2 (opencv4.1.1) 
   - Java+OpenCV (1.8.0_192 / opencv-4.1.1_vc14_vc15)

### Detailed description
- FAIL to open URL MJEPG Stream using OpenCV Java-Wrapper.
- OK to open URL MJEPG Stream uinsg Python-Wrapper works perfect.
- OK to open URL MJEPG Stream using VLC and Firefox
- URL = http://localhost:5000/videofeed?cam.mjpg

### Steps to reproduce
- Start the server .... python server.py
- Open WebBrowser (or VLC) using given URL above to check for correct server activity
- Start one or the other client ... 
   - python client.py                      OR
   - javac -cp opencv-411.jar client.java && java.exe -cp .;opencv-411.jar client

The error report is given next to the file client.java below.

### Files
server.py
```
#........1.........2.........3.........4.........5.........6.........7.........8
# Python 3.7.4 / cv2.__version__=4.1.1
# WebCam-Server providing MJPEG stream
#   OK:Firefox_62.0.3   OK_SLOW:VLC_3.0.8   OK:Py3.7+cv2
#   FAIL:Java+OpenCV_4.1.1

# command to start the server
#    python server.py

import cv2, time
from flask import Flask, Response, request
import numpy as np

app=Flask(__name__)

def get_frames():
  while True:
    img=np.random.randint(0,255,[90,90,3], dtype=np.uint8)
    yield cv2.imencode('.jpg', img)[1].tobytes()
    time.sleep(0.01)

def gen():
  ii=0
  while True:
    for frame in get_frames():
      yield (b'--frame\r\n'
             b'Content-Type:image/jpeg\r\n'
             b'Content-Length: '+(b'%d' % len(frame))+b'\r\n'
             b'\r\n'+frame+b'\r\n')

@app.route('/videofeed')
def f_videofeed():
  print("@app.route('/videofeed') .....")
  return Response(gen(), mimetype='multipart/x-mixed-replace;boundary=frame')

if __name__=='__main__':
  app.run(host='localhost', threaded=True, debug=True)  # default at port 500
```
client.py
```
#........1.........2.........3.........4.........5.........6.........7.........8
# Copyright 2019 ldpgh
# Python 3.7.4 / cv2.__version__=4.1.1
# Client ... 

# command to start the Python client
#   python client.py

import cv2
fg=cv2.VideoCapture()
print(fg)
addr="http://localhost:5000/videofeed?cam1.mjpg"
print(addr)
tst=fg.open(addr, cv2.CAP_FFMPEG)
print(tst)
print(fg.getBackendName())

for ii in range(5):
  val,frm=fg.read()
  s1=frm.tostring()
  print("%d : %r  %r  %r ... %r" % (ii, val, len(s1), s1[:6], s1[-6:]))
fg.release()

print("...fertsch")
```

client.java
```
//.......1.........2.........3.........4.........5.........6.........7.........8
// Java 1.8.0_192 / opencv-4.1.1_vc14_vc15
// Client
//     opencv-411.jar/opencv_java411.dll vom InstallDir nach "." kopiert  !!!!!!

// command to start the Java client
//   javac -cp opencv-411.jar client.java && java.exe -cp .;opencv-411.jar client

import org.opencv.core.Core;
import org.opencv.videoio.VideoCapture;
import org.opencv.videoio.Videoio;

public class client{
  public static void main (String args[]) throws InterruptedException
  {
    Boolean tst=false;
    String s1="<string_has_not_been_assigned>";
    System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    VideoCapture fg=new VideoCapture();//Videoio.CAP_FFMPEG);
    System.out.println("fg -> "+fg);
    //String addr="http://localhost:5000/videofeed?cam1.mjpg";
    String addr="http://localhost:5000/videofeed?cam.mjpg";
    tst=fg.open(addr);
    System.out.println("fg.open(addr) -> "+tst);
    s1=fg.getBackendName();
    System.out.println("fg.getBackendName() -> "+s1);
  }
}
```

The console output of the Java client 
```
test_flask_opencv>
test_flask_opencv>
test_flask_opencv>javac -cp opencv-411.jar client.java && java.exe -cp .;opencv-411.jar client
fg -> org.opencv.videoio.VideoCapture@28d93b30
[ERROR:0] global C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.1.1) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://localhost:5000/videofeed?cam.mjpg in function 'c
v::icvExtractPattern'


fg.open(addr) -> false
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.1.1) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\videoio\src\cap.cpp:220: error: (-215:Assertion failed) api != 0 in function 'cv::VideoCap
ture::getBackendName'
]
        at org.opencv.videoio.VideoCapture.getBackendName_0(Native Method)
        at org.opencv.videoio.VideoCapture.getBackendName(VideoCapture.java:164)
        at client.main(client.java:24)

test_flask_opencv>
test_flask_opencv>
```

**Comment by ldpgh** [comment]
Does "question (invalid tracker)" means the Java-bindings has to be reported somewhere else?

**Comment by alalek** [comment]
This means that this tracker is for issues and bugs that needs fix in OpenCV.

Loading of FFmpeg plugin should be properly configured (`opencv_videoio_ffmpegXXX.dll` in modern OpenCV versions). `PATH` should point on directory with this file (add `build\bin` of winpack package).

[`OPENCV_VIDEOIO_DEBUG=1`](https://docs.opencv.org/master/de/db1/group__videoio__registry.html) environment variable should help with investigation.
