### ISSUE TITLE
cv2.so requires openblas even though atlas is chosen

### ISSUE THREAD

**Issue by capstayn** [opencv/opencv#16219]
##### System information (version)

- OpenCV => 3.4.9
- Operating System / Platform => archlinux 64bit
- Compiler => gcc 9.2.0

##### Detailed description

I have just installed opencv from source, with bindings to python3.8. I chose Atlas for BLAS implementation. When compiling the python bindings I saw warnings of the kind

`warning: libopenblas.so.3 not found`

Which sounded weird to me, because I had explicitly chosen Atlas implementation in cmake. The compilation went ahead, so I didn't think much of it. Besides, Archlinux doesn't allow you to have two implementations of BLAS installed on the system, so there was no much I could do about it. 

The issue became apparent when I tried to import cv2, it threw this error: 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "cv2/__init__.py", line 8, in <module>
>     import numpy
>   File "/usr/lib/python2.7/site-packages/numpy/__init__.py", line 145, in <module>
>     from . import lib
>   File "/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 9, in <module>
>     from .index_tricks import *
>   File "/usr/lib/python2.7/site-packages/numpy/lib/index_tricks.py", line 13, in <module>
>     import numpy.matrixlib as matrixlib
>   File "/usr/lib/python2.7/site-packages/numpy/matrixlib/__init__.py", line 6, in <module>
>     from .defmatrix import *
>   File "/usr/lib/python2.7/site-packages/numpy/matrixlib/defmatrix.py", line 13, in <module>
>     from numpy.linalg import matrix_power
>   File "/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 51, in <module>
>     from .linalg import *
>   File "/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 35, in <module>
>     from numpy.linalg import lapack_lite, _umath_linalg
> ImportError: libopenblas.so.3: cannot open shared object file: No such file or directory

So even though I had chosen atlas implementation, cv2.so is requiring openblas

##### Steps to reproduce

-On archlinux, install python-numpy
-Compile from source opencv, choose atlas implementation for BLAS
-Select python3.8 as default executable (for python bindings)
- import cv2 fails with above error

**Comment by capstayn** [comment]
I just figured out that the problem reside in the numpy package, not in cv2.so. The package of numpy that I have installed needs OpenBLAS (which is in opposition with their policies) and throws that error.
