### ISSUE TITLE
TypeError: Not a cmessage converting tensorflow model from .pb to .pbtxt

### ISSUE THREAD

**Issue by yieniggu** [opencv/opencv#16280]
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Ubuntu 18.04 64 bits
- Compiler => cmake

##### Detailed description

I am trying to generate a .pbtxt from a tensorflow frozen_inference_graph.pb file. I'm using a custom model based on ssd_resnet_50_fpn_coco tensorflow model.
When I run the [text_graph_ssd.py](https://github.com/opencv/opencv/blob/master/samples/dnn/tf_text_graph_ssd.py) on a ssd_inception_v2_coco custom model it generates the .pbtxt file without issues.

However when tried on the resnet model, at first got the output mentioned in #11560, then aplied the fix mentioned there.

Now, I have a new error:

```
Traceback (most recent call last):
  File "tf_text_graph_ssd.py", line 377, in <module>
    createSSDGraph(args.input, args.config, args.output)
  File "tf_text_graph_ssd.py", line 261, in createSSDGraph
    addConstNode('concat/axis_flatten', [-1], graph_def)
  File "/home/blue/tensorflow/scripts/postprocessing/tf_text_graph_common.py", line 114, in addConstNode
    graph_def.node.extend([node])
TypeError: Not a cmessage

```

I tried with the fix mentioned in #15176, but it didn't work.

##### Steps to reproduce
1. Download my .pb file from [here](https://gofile.io/?c=ymew4E)
2. Download the text_graph_ssd.py that I'm using [here](https://pastebin.com/FHmicfk3) and run the script. (Be sure to have the text_graph_common.py in the same directory).

**Comment by dkurt** [comment]
Can you please add a config file which is used for training? Should be named as `pipeline.config` or similar.

**Comment by yieniggu** [comment]
The script you mention is the first I tried. As I said, it works fine on a ssd_inception _v2_coco custom model, but not on the resnet model.


Here are the tow configs I used for each training.

**Comment by yieniggu** [comment]
@dkurt any update on this?

**Comment by dkurt** [comment]
@yieniggu, Can you please upload the file once again (link is not actual now) or test the latest master branch if it solves the problem? Thanks!
