### ISSUE TITLE
the problem with the input image function

### ISSUE THREAD

**Issue by vishwas1234567** [opencv/opencv#16444]
```python
def deskew(img):
    m = cv2.moments(img)
    if abs(m['mu02']) < 1e-2:
        return img.copy()
    skew = m['mu11']/m['mu02']
    M = np.float32([[1, skew, -0.5*SZ*skew], [0, 1, 0]])
    img = cv2.warpAffine(img,M,(SZ, SZ),flags=affine_flags)
    return img


def hog(img):
    gx = cv2.Sobel(img, cv2.CV_32F, 1, 0)
    gy = cv2.Sobel(img, cv2.CV_32F, 0, 1)
    mag, ang = cv2.cartToPolar(gx, gy)
    bins = np.int32(bin_n*ang/(2*np.pi))    # quantizing binvalues in (0...16)
    bin_cells = bins[:10,:10], bins[10:,:10], bins[:10,10:], bins[10:,10:]
    mag_cells = mag[:10,:10], mag[10:,:10], mag[:10,10:], mag[10:,10:]
    hists = [np.bincount(b.ravel(), m.ravel(), bin_n) for b, m in zip(bin_cells, mag_cells)]
    hist = np.hstack(hists)     # hist is a 64 bit vector
    return hist


img = cv2.imread(path,0)

cells = [np.hsplit(row,100) for row in np.vsplit(img,50)]

# First half is trainData, remaining is testData
train_cells = [ i[:50] for i in cells ]
test_cells = [ i[50:] for i in cells]

######     Now training      ########################

deskewed = [map(deskew,row) for row in train_cells]
hogdata = [map(hog,row) for row in deskewed]
trainData = np.float32(hogdata).reshape(-1,64)
responses = np.float32(np.repeat(np.arange(10),250)[:,np.newaxis])

svm = cv2.SVM()
svm.train(trainData,responses, params=svm_params)
svm.save('svm_data.dat')

######     Now testing      ########################

deskewed = [map(deskew,row) for row in test_cells]
hogdata = [map(hog,row) for row in deskewed]
testData = np.float32(hogdata).reshape(-1,bin_n*4)
result = svm.predict_all(testData)
```

```
#######   Check Accuracy   ########################
mask = result==responses
correct = np.count_nonzero(mask)
print(correct*100.0/result.size)
Traceback (most recent call last):

  File "<ipython-input-8-7a34a7e4b44b>", line 25, in <module>
    cells = [np.hsplit(row,100) for row in np.vsplit(img,50)]

  File "C:\Users\vishwasnarayan\Anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 972, in vsplit
    return split(ary, indices_or_sections, 0)

  File "C:\Users\vishwasnarayan\Anaconda3\lib\site-packages\numpy\lib\shape_base.py", line 849, in split
    'array split does not result in an equal division')

ValueError: array split does not result in an equal division
```

**Comment by phoenixcool12** [comment]
hi i am interested in this issue. Is anybody already working on this.

**Comment by alalek** [comment]
@phoenixcool12 Ignore this. There are many other interesting issues.

<details>

<summary>Long way</summary>

Try to ask from issue's author for **complete minimal reproducer**.

"Complete" means that issue should have **input data** for reproducer. For this example, including:
- `path` value
- contents of the `path` file

"Minimal" means that 90% of provided code is not needed at all (it crashes on the second executed statement - fortunately, the issue has attached traceback).

---

When you receive input data, try to reproduce it locally and elaborate what is wrong here (perhaps `img.shape` is not good or even `img is None`).
After that write answer about investigation results to the issue's author.

</details>

**Comment by phoenixcool12** [comment]
@alalek ok so you want me to correct the overall code?

**Comment by phoenixcool12** [comment]
@vishwas1234567 can you provide more details on the objective of your code.
