### ISSUE TITLE
import Tensorflow 2.x PB via readNetFromTensorflow DNN api function (C++)

### ISSUE THREAD

**Issue by rtrahms** [opencv/opencv#16879]
I have a UNet DNN that I have created and trained in python (TF2.1/Keras).  I saved the model to a PB file using the Model.save() method.  Reloading the model via the Model.load_file() method in TF works fine, but I cannot load the model using readNetFromTensorflow() in OpenCV.  I hear SavedModel is not currently supported by OpenCV, and that I should use a frozen graph, but frozen graph functionality is deprecated in TF2.x.  Any solutions here?
Thanks,
Rob

##### System information (version)
- OpenCV => 4.2
- Tensorflow => 2.1
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019

**Comment by dkurt** [comment]
Hi! Please add a link to specific model.

**Comment by rtrahms** [comment]
Maybe it would save time if I debugged this myself.  Is there a known-good TF2.1/Keras model that has been loaded in opencv using the DNN API?  Like a tutorial TF2.1 model?  I am looking for one right now.
Thanks,
Rob

**Comment by rtrahms** [comment]
I used the following test code to generate and store a TF2.1 model under mnist_test (called saved_model.pb):

import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test,  y_test, verbose=2)
model.save('models/mnist_test')

In a C++ app, I try to load the saved_model.pb file with the following code:

	cv::dnn::Net myNet;
	myNet = cv::dnn::readNetFromTensorflow(pbPath);

(pbPath is "models/saved_model.pb'"

**Comment by rtrahms** [comment]
The error I get is fairly consistent:

[libprotobuf ERROR C:\opencv4.2.0\opencv-4.2.0\3rdparty\protobuf\src\google\protobuf\wire_format_lite.cc:629] String field 'opencv_tensorflow.FunctionDef.Node.ret' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
OpenCV: terminate handler is called! The last OpenCV error is:
OpenCV(4.2.0) Error: Unspecified error (FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: C:\DATA\Developer\DeepLearning\Semantic_Segmentation\unet\models\mnist_test\saved_model.pb) in cv::dnn::ReadTFNetParamsFromBinaryFileOrDie, file C:\opencv4.2.0\opencv-4.2.0\modules\dnn\src\tensorflow\tf_io.cpp, line 42

**Comment by dkurt** [comment]
@rtrahms, may I ask you to try the following approach? It's the first time we are trying it so need you feedback:

1. I changed input resolution from 1x28x28 to 1x28x28x1 (NHWC)
2. Used the following script to convert SavedModel to a frozen graph:

```python
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
from tensorflow.python.tools import optimize_for_inference_lib

loaded = tf.saved_model.load('models/mnist_test')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(flatten_input=tf.TensorSpec(shape=[None, 28, 28, 1], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Remove NoOp nodes
for i in reversed(range(len(graph_def.node))):
    if graph_def.node[i].op == 'NoOp':
        del graph_def.node[i]

for node in graph_def.node:
    for i in reversed(range(len(node.input))):
        if node.input[i][0] == '^':
            del node.input[i]

# Remove a lot of Identity nodes
graph_def = optimize_for_inference_lib.optimize_for_inference(graph_def,
                                                              ['flatten_input'],
                                                              ['StatefulPartitionedCall/StatefulPartitionedCall/sequential/dense_1/BiasAdd'],
                                                              tf.float32.as_datatype_enum)

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
```

3. Tried to run with the following script:

```python
import numpy as np
import cv2 as cv

print(cv.__file__)

net = cv.dnn.readNet('frozen_graph.pb')
inp = np.random.standard_normal([1, 1, 28, 28]).astype(np.float32)
net.setInput(inp)
out = net.forward()
print(out.shape)
```
(note that input for OpenCV should be NCHW).

**Comment by dkurt** [comment]
**Update**: with changes from https://github.com/opencv/opencv/pull/16905 it's enough to just use

```python
import tensorflow as tf
print(tf.__version__)

from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
from tensorflow.python.tools import optimize_for_inference_lib

loaded = tf.saved_model.load('models/mnist_test')
infer = loaded.signatures['serving_default']

f = tf.function(infer).get_concrete_function(flatten_input=tf.TensorSpec(shape=[None, 28, 28, 1], dtype=tf.float32))
f2 = convert_variables_to_constants_v2(f)
graph_def = f2.graph.as_graph_def()

# Export frozen graph
with tf.io.gfile.GFile('frozen_graph.pb', 'wb') as f:
   f.write(graph_def.SerializeToString())
```

**Comment by jaswanthbjk** [comment]
@dkurt  **I followed the code mentioned by you. Can you help me?

I am using Tensorflow-GPU 2.4.0.

I have the following error** 

TypeError: signature_wrapper(*, input_tensor) missing required arguments: input_tensor


**The whole trace is as follows**

File "pbtxt.py", line 9, in <module>
    f = tf.function(infer).get_concrete_function(flatten_input=tf.TensorSpec(shape=[None, 1024, 1024, 1], dtype=tf.float32))
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py:1669 __call__  *
        return self._call_impl(args, kwargs)
    /home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py:1685 _call_impl  **
        raise structured_err
    /home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py:1679 _call_impl
        cancellation_manager)
    /home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py:1756 _call_with_structured_signature
        self._structured_signature_check_missing_args(args, kwargs)
    /home/jbandl2s/anaconda3/envs/cv_project/lib/python3.6/site-packages/tensorflow/python/eager/function.py:1777 _structured_signature_check_missing_args
        ", ".join(sorted(missing_arguments))))

    TypeError: signature_wrapper(*, input_tensor) missing required arguments: input_tensor

**Comment by Bleach665** [comment]
@dkurt Same error as above.

`ssd_resnet50_v1_fpn_640x640_coco17_tpu-8` model trained using Tensorflow object detection API using
https://github.com/tensorflow/models/blob/master/research/object_detection/model_main_tf2.py

After exported to `Save model`:
 `.\exporter_main_v2.py --input_type image_tensor --pipeline_config_path .\models\my_ssd_resnet50_v1_fpn\pipeline.config --trained_checkpoint_dir .\models\my_ssd_resnet50_v1_fpn\ --output_directory .\exported-models\models\Bel_model` using
https://github.com/tensorflow/models/blob/master/research/object_detection/exporter_main_v2.py

On this step inference work fine using Tensorflow.

Inference from `Saved model`:
<details>

````
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import pathlib
import tensorflow as tf

tf.get_logger().setLevel('ERROR')           # Suppress TensorFlow logging (2)

# Enable GPU dynamic memory allocation
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)


PATH_TO_LABELS = "label_map.pbtxt" 

# %%
# Load the model
# ~~~~~~~~~~~~~~
# Next we load the downloaded model
import time
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils

PATH_TO_SAVED_MODEL = "models\\Bel_model\\saved_model"

print('Loading model...', end='')
start_time = time.time()

# Load saved model and build the detection function
detect_fn = tf.saved_model.load(PATH_TO_SAVED_MODEL)

end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

# %%
# Load label map data (for plotting)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Label maps correspond index numbers to category names, so that when our convolution network
# predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility
# functions, but anything that returns a dictionary mapping integers to appropriate string labels
# would be fine.

category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)

# %%
# Putting everything together
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The code shown below loads an image, runs it through the detection model and visualizes the
# detection results, including the keypoints.
#
# Note that this will take a long time (several minutes) the first time you run this code due to
# tf.function's trace-compilation --- on subsequent runs (e.g. on new images), things will be
# faster.
#
# Here are some simple things to try out if you are curious:
#
# * Modify some of the input images and see if detection still works. Some simple things to try out here (just uncomment the relevant portions of code) include flipping the image horizontally, or converting to grayscale (note that we still expect the input image to have 3 channels).
# * Print out `detections['detection_boxes']` and try to match the box locations to the boxes in the image.  Notice that coordinates are given in normalized form (i.e., in the interval [0, 1]).
# * Set ``min_score_thresh`` to other values (between 0 and 1) to allow more detections in or to filter out more detections.
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))

IMAGE_PATHS = ['1.png', '2.png']

for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
    # image_np = np.tile(
    #     np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    # The input needs to be a tensor, convert it using `tf.convert_to_tensor`.
    input_tensor = tf.convert_to_tensor(image_np)
    # The model expects a batch of images, so add an axis with `tf.newaxis`.
    input_tensor = input_tensor[tf.newaxis, ...]

    # input_tensor = np.expand_dims(image_np, 0)
    detections = detect_fn(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                   for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
          image_np_with_detections,
          detections['detection_boxes'],
          detections['detection_classes'],
          detections['detection_scores'],
          category_index,
          use_normalized_coordinates=True,
          max_boxes_to_draw=200,
          min_score_thresh=.30,
          agnostic_mode=False)  
    
    plt.figure()
    plt.imshow(image_np_with_detections)
    
    #***
    newname =  image_path.replace('.', '_out.') 
    plt.savefig(newname)
    
    print('Done')
plt.show()

# sphinx_gallery_thumbnail_number = 2
````
</details>

Inference from `Checkpoint`:
<details>

````
#!/usr/bin/env python
# coding: utf-8
"""
Object Detection From TF2 Checkpoint
====================================
"""

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'    # Suppress TensorFlow logging (1)
import pathlib
import tensorflow as tf

PATH_TO_LABELS = "label_map.pbtxt" 
PATH_TO_MODEL_DIR = "models/Bel_model"

# %%
# Load the model
# ~~~~~~~~~~~~~~
# Next we load the downloaded model
import time
from object_detection.utils import label_map_util
from object_detection.utils import config_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

PATH_TO_CFG = PATH_TO_MODEL_DIR + "/pipeline.config"
PATH_TO_CKPT = PATH_TO_MODEL_DIR + "/checkpoint"

print('Loading model... ', end='')
start_time = time.time()

# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(PATH_TO_CFG)
model_config = configs['model']
detection_model = model_builder.build(model_config=model_config, is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(PATH_TO_CKPT, 'ckpt-0')).expect_partial()

@tf.function
def detect_fn(image):
    """Detect objects in image."""

    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)

    return detections

end_time = time.time()
elapsed_time = end_time - start_time
print('Done! Took {} seconds'.format(elapsed_time))

# %%
# Load label map data (for plotting)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Label maps correspond index numbers to category names, so that when our convolution network
# predicts `5`, we know that this corresponds to `airplane`.  Here we use internal utility
# functions, but anything that returns a dictionary mapping integers to appropriate string labels
# would be fine.

category_index = label_map_util.create_category_index_from_labelmap(PATH_TO_LABELS,
                                                                    use_display_name=True)

# %%
# Putting everything together
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~
# The code shown below loads an image, runs it through the detection model and visualizes the
# detection results, including the keypoints.
#
# Note that this will take a long time (several minutes) the first time you run this code due to
# tf.function's trace-compilation --- on subsequent runs (e.g. on new images), things will be
# faster.
#
# Here are some simple things to try out if you are curious:
#
# * Modify some of the input images and see if detection still works. Some simple things to try out here (just uncomment the relevant portions of code) include flipping the image horizontally, or converting to grayscale (note that we still expect the input image to have 3 channels).
# * Print out `detections['detection_boxes']` and try to match the box locations to the boxes in the image.  Notice that coordinates are given in normalized form (i.e., in the interval [0, 1]).
# * Set ``min_score_thresh`` to other values (between 0 and 1) to allow more detections in or to filter out more detections.
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')   # Suppress Matplotlib warnings

def load_image_into_numpy_array(path):
    """Load an image from file into a numpy array.

    Puts image into numpy array to feed into tensorflow graph.
    Note that by convention we put it into a numpy array with shape
    (height, width, channels), where channels=3 for RGB.

    Args:
      path: the file path to the image

    Returns:
      uint8 numpy array with shape (img_height, img_width, 3)
    """
    return np.array(Image.open(path))

IMAGE_PATHS = ['1.png', '2.png']

for image_path in IMAGE_PATHS:

    print('Running inference for {}... '.format(image_path), end='')

    image_np = load_image_into_numpy_array(image_path)        
    
    plt.figure()
    plt.imshow(image_np)

    # Things to try:
    # Flip horizontally
    # image_np = np.fliplr(image_np).copy()

    # Convert image to grayscale
    # image_np = np.tile(
    #     np.mean(image_np, 2, keepdims=True), (1, 1, 3)).astype(np.uint8)

    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)

    detections = detect_fn(input_tensor)

    # All outputs are batches tensors.
    # Convert to numpy arrays, and take index [0] to remove the batch dimension.
    # We're only interested in the first num_detections.
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                  for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    label_id_offset = 1
    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
            image_np_with_detections,
            detections['detection_boxes'],
            detections['detection_classes']+label_id_offset,
            detections['detection_scores'],
            category_index,
            use_normalized_coordinates=True,
            max_boxes_to_draw=200,
            min_score_thresh=.30,
            agnostic_mode=False)

    plt.figure()
    plt.imshow(image_np_with_detections)  
    
    #***
    newname =  image_path.replace('.', '_out_cp.') 
    plt.savefig(newname)
    
    print('Done')
plt.show()

# sphinx_gallery_thumbnail_number = 2
````
</details>

But when I try to convert `Saved model` to `Frozen graph` using this code
https://github.com/opencv/opencv/issues/16879#issuecomment-603815872
I receive error same as above:
<details>

````
2021-01-27 14:20:25.689687: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-27 14:20:25.689761: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-27 14:20:33.819028: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-01-27 14:20:33.819694: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-01-27 14:20:33.821661: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-27 14:20:33.825189: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Eclipse
2021-01-27 14:20:33.825303: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Eclipse
2021-01-27 14:20:33.826001: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-01-27 14:20:33.826483: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Traceback (most recent call last):
  File ".\frozen_graph.py", line 8, in <module>
    f = tf.function(infer).get_concrete_function(input_1=tf.TensorSpec(shape=[None, 640, 640, 3], dtype=tf.float32))
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\framework\func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\framework\func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1669 __call__  *
        return self._call_impl(args, kwargs)
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1685 _call_impl  **
        raise structured_err
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1678 _call_impl
        return self._call_with_structured_signature(args, kwargs,
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1756 _call_with_structured_signature
        self._structured_signature_check_missing_args(args, kwargs)
    C:\Users\Bleach\miniconda3\envs\TFstd\lib\site-packages\tensorflow\python\eager\function.py:1775 _structured_signature_check_missing_args
        raise TypeError("{} missing required arguments: {}".format(

    TypeError: signature_wrapper(*, input_tensor) missing required arguments: input_tensor
````
</details>

**Comment by dkurt** [comment]
@jaswanthbjk, please read error message carefully. You need to specify `input_tensor` instead of `flatten_input`

**Comment by AI-P-K** [comment]
Did anyone managed to actually find a way of loading TF2 saved_model.pb into OpenCV dnn module?

**Comment by 0Andriy** [comment]
no

**Comment by Tbeck-91** [comment]
> 
> 
> @jaswanthbjk, please read error message carefully. You need to specify `input_tensor` instead of `flatten_input`

could you be more clear? I just replace 'flatten_input' with 'input_tensor'?

**Comment by Tbeck-91** [comment]
how do I figure out what shape the input tensor needs to be?
