### ISSUE TITLE
readNetFromONNX cpp:136: error: (-215:Assertion failed) inputs.size() == 1 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'

### ISSUE THREAD

**Issue by zihaozhang9** [opencv/opencv#16912]
I use the following statement to load the onnx model. 
`net = cv2.dnn.readNetFromONNX('keras.onnx')`
But something goes wrong.
` net = cv2.dnn.readNetFromONNX('keras.onnx')
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\slice_layer.cpp:136: error: (-215:Assertion failed) inputs.size() == 1 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'`

**environment**:
window10
python3.6.10
opencv4.2.0
pythorch0.4.1

**All code is as follows**
`
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets,transforms
from PIL import ImageFont, Image, ImageDraw
class Net_keras(nn.Module):
    def __init__(self,num_classes=7):
        super(Net_keras, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=3, stride=1, padding=1, bias=True)
        self.relu1 = nn.ReLU()
        self.mp1 = nn.MaxPool2d(2)
        
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1, bias=True)
        self.relu2 = nn.ReLU()
        self.mp2 = nn.MaxPool2d(2)
        
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=0, bias=True)
        self.relu3 = nn.ReLU()
        self.mp3 = nn.MaxPool2d(2)
        
        self.conv4 = nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=0, bias=True)
        self.relu4 = nn.ReLU()
        self.mp4 = nn.MaxPool2d(2)
        
        self.conv5 = nn.Conv2d(128, 128, kernel_size=3, stride=1, padding=0, bias=True)
        self.relu5 = nn.ReLU()
        self.mp5 = nn.MaxPool2d(2)
        
        self.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(128 * 5 * 5, 256),
            nn.ReLU(),
            nn.Linear(256, num_classes),
        )
    def forward(self, x):
        x = self.relu1( self.conv1(x) )
        x = self.mp1(x)
        
        x = self.relu2( self.conv2(x) )
        feat1 = self.mp2(x)
        
        x = self.relu3( self.conv3(feat1) )
        feat2 = self.mp3(x)
        
        x = self.relu4( self.conv4(feat2) )
        feat3 = self.mp4(x)
        
        x = self.relu5( self.conv5(feat3) )
        feat4 = self.mp5(x)
        x = feat4.view(feat4.shape[0],-1)
        x = self.classifier(x)
        
        return x

def save_onnx():
    model = Net_keras(num_classes=7) 
    model.eval()
    x = torch.randn(1,3,224,224) 
    export_onnx_file = "keras.onnx" 	
    torch.onnx.export(model, x,export_onnx_file, verbose=True, input_names=["input"],output_names=["output"])
    
def read_cv():
    import cv2
    net = cv2.dnn.readNetFromONNX('keras.onnx')

save_onnx()
read_cv()
`

`graph(%input : Float(1, 3, 224, 224)
      %1 : Float(16, 3, 3, 3)
      %2 : Float(16)
      %3 : Float(32, 16, 3, 3)
      %4 : Float(32)
      %5 : Float(64, 32, 3, 3)
      %6 : Float(64)
      %7 : Float(128, 64, 3, 3)
      %8 : Float(128)
      %9 : Float(128, 128, 3, 3)
      %10 : Float(128)
      %11 : Float(256, 3200)
      %12 : Float(256)
      %13 : Float(7, 256)
      %14 : Float(7)) {
  %15 : Float(1, 16, 224, 224) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%input, %1, %2), scope: Net_keras/Conv2d[conv1]
  %16 : Float(1, 16, 224, 224) = onnx::Relu(%15), scope: Net_keras/ReLU[relu1]
  %17 : Float(1, 16, 112, 112) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%16), scope: Net_keras/MaxPool2d[mp1]
  %18 : Float(1, 32, 112, 112) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%17, %3, %4), scope: Net_keras/Conv2d[conv2]
  %19 : Float(1, 32, 112, 112) = onnx::Relu(%18), scope: Net_keras/ReLU[relu2]
  %20 : Float(1, 32, 56, 56) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%19), scope: Net_keras/MaxPool2d[mp2]
  %21 : Float(1, 64, 54, 54) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[1, 1]](%20, %5, %6), scope: Net_keras/Conv2d[conv3]
  %22 : Float(1, 64, 54, 54) = onnx::Relu(%21), scope: Net_keras/ReLU[relu3]
  %23 : Float(1, 64, 27, 27) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%22), scope: Net_keras/MaxPool2d[mp3]
  %24 : Float(1, 128, 25, 25) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[1, 1]](%23, %7, %8), scope: Net_keras/Conv2d[conv4]
  %25 : Float(1, 128, 25, 25) = onnx::Relu(%24), scope: Net_keras/ReLU[relu4]
  %26 : Float(1, 128, 12, 12) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%25), scope: Net_keras/MaxPool2d[mp4]
  %27 : Float(1, 128, 10, 10) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[1, 1]](%26, %9, %10), scope: Net_keras/Conv2d[conv5]
  %28 : Float(1, 128, 10, 10) = onnx::Relu(%27), scope: Net_keras/ReLU[relu5]
  %29 : Float(1, 128, 5, 5) = onnx::MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%28), scope: Net_keras/MaxPool2d[mp5]
  %30 : Dynamic = onnx::Shape(%29), scope: Net_keras
  %31 : Dynamic = onnx::Slice[axes=[0], ends=[1], starts=[0]](%30), scope: Net_keras
  %32 : Long() = onnx::Squeeze[axes=[0]](%31), scope: Net_keras
  %33 : Long() = onnx::Constant[value={-1}](), scope: Net_keras
  %34 : Dynamic = onnx::Unsqueeze[axes=[0]](%32), scope: Net_keras
  %35 : Dynamic = onnx::Unsqueeze[axes=[0]](%33), scope: Net_keras
  %36 : Dynamic = onnx::Concat[axis=0](%34, %35), scope: Net_keras
  %37 : Float(1, 3200) = onnx::Reshape(%29, %36), scope: Net_keras
  %38 : Float(1, 3200), %39 : Dynamic = onnx::Dropout[is_test=1, ratio=0.5](%37), scope: Net_keras/Sequential[classifier]/Dropout[0]
  %40 : Float(1, 256) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%38, %11, %12), scope: Net_keras/Sequential[classifier]/Linear[1]
  %41 : Float(1, 256) = onnx::Relu(%40), scope: Net_keras/Sequential[classifier]/ReLU[2]
  %output : Float(1, 7) = onnx::Gemm[alpha=1, beta=1, broadcast=1, transB=1](%41, %13, %14), scope: Net_keras/Sequential[classifier]/Linear[3]
  return (%output);
}

Traceback (most recent call last):
  File "temp.py", line 70, in <module>
    read_cv()
  File "temp.py", line 67, in read_cv
    net = cv2.dnn.readNetFromONNX('keras.onnx')
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\layers\slice_layer.cpp:136: error: (-215:Assertion failed) inputs.size() == 1 in function 'cv::dnn::SliceLayerImpl::getMemoryShapes'

`

**Comment by zihaozhang9** [comment]
Sorry. I updated pytorch. It works now. pytorch1.4.0
