### ISSUE TITLE
How to use prebuilt opencv python in Windows

### ISSUE THREAD

**Issue by zchrissirhcz** [opencv/opencv#17043]
##### System information (version)
- Platform => Windows 64 Bit
- Interpreter => Python 3.7 (via Miniconda)

##### Detailed description

I would like to compare two implementation of my algorithm, one in in Python, the other is C++. Both rely on OpenCV. I think I should keep them the same version, and be updated version. The opencv's Python and C++ libs's version confuse me.

I've downloaded the latest OpenCV 4.3.0 windows prebuilt package. I can easily use its C++ version libs. However, I just can't use the provided Python opencv. It complains the recursive loading of cv2 module.

##### Steps to reproduce
1. Go to https://opencv.org and download opencv4.3.0 Windows package. Extract and rename to D:/lib/opencv/4.3.0, which contain `source` and `build` sub folders.

2. Use this snippet to test:

`test.py`
```python
# coding: utf-8
import numpy as np

import sys
sys.path.insert(0, 'D:/lib/opencv/4.3.0/build/python')

import cv2

im = np.ones((100,100,3))
im = im * 0.73 * 255
cv2.imwrite('res-py.bmp', im)
```

3. Run `python test.py` and get result like:
```
python .\build\test_cv349-vs2017-x64\test.py
['D:/lib/opencv/4.3.0/build/python', 'D:\\lib\\opencv\\4.3.0\\build\\python\\cv2\\python-3.7', 'E:\\dbg\\zz\\darkcv\\build\\test_cv349-vs2017-x64', 'e:\\soft\\Miniconda3\\python37.zip', 'e:\\soft\\Miniconda3\\DLLs', 'e:\\soft\\Miniconda3\\lib', 'e:\\soft\\Miniconda3', 'e:\\soft\\Miniconda3\\lib\\site-packages', 'e:\\soft\\Miniconda3\\lib\\site-packages\\win32', 'e:\\soft\\Miniconda3\\lib\\site-packages\\win32\\lib', 'e:\\soft\\Miniconda3\\lib\\site-packages\\Pythonwin']
Traceback (most recent call last):
  File ".\build\test_cv349-vs2017-x64\test.py", line 7, in <module>
    import cv2
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 96, in <module>        
    bootstrap()
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 86, in bootstrap       
    import cv2
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 96, in <module>        
    bootstrap()
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 23, in bootstrap       
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

**Comment by alalek** [comment]
`python --version` ?

**Comment by zchrissirhcz** [comment]
@alalek 
The python version information is:

```bash
E:\dbg\zz\test>python --version
Python 3.7.4

E:\dbg\zz\test>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by alalek** [comment]
> 64 bit

Good.

---

As a workaround try to add full path with "/cv2/python-3.7" here (to skip loader):

```
sys.path.insert(0, 'D:/lib/opencv/4.3.0/build/python')
```

Additionally you need to adjust PATH environment variable too: include path with "x64/vc15/bin".

Try to run `x64/vc15/bin/opencv_version_win32.exe` if step above failed. It should dump configuration on console.

---

> Libraries may fail to load.

Please resolve this issue and try again too.

---

Python bindings are build using official Python distribution ( https://www.python.org/downloads/ ).
It is hard to say how Anaconda distribution differs.

**Comment by zchrissirhcz** [comment]
@alalek 
Thanks for reponse. Now I've changed to official Python instead of Anaconda's.

> Put "x64/vc15/bin" to PATH

Yes, now prepending to PATH
```bash
E:\dbg\zz\test>echo %PATH%
D:\lib\opencv\4.3.0\build\x64\vc15\bin;e:\lib\VulkanSDK\1.2.135.0\Bin;E:\soft\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;E:\soft\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;E:\soft\Git\usr\bin;
（and more）
```

> Which Python version now? 

```bash
E:\dbg\zz\test>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
> Can load cv2?
No, still can't.
```bash
>>> import cv2
['', 'E:/dev/opencv-3.4.9/build/vs2017-x64/lib/python3/Release', 'E:\\soft\\Python37\\python37.zip', 'E:\\soft\\Python37\\DLLs', 'E:\\soft\\Python37\\lib', 'E:\\soft\\Python37', 'E:\\soft\\Python37\\lib\\site-packages', 'e:\\dev\\opencv-3.4.9\\build\\vs2017-x64\\python_loader']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\dev\opencv-3.4.9\build\vs2017-x64\python_loader\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "e:\dev\opencv-3.4.9\build\vs2017-x64\python_loader\cv2\__init__.py", line 86, in bootstrap
    import cv2
  File "e:\dev\opencv-3.4.9\build\vs2017-x64\python_loader\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "e:\dev\opencv-3.4.9\build\vs2017-x64\python_loader\cv2\__init__.py", line 23, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

> Try to run `x64/vc15/bin/opencv_version_win32.exe`
Well, it gives output:
```

General configuration for OpenCV 4.3.0 =====================================
  Version control:               4.3.0

  Platform:
    Timestamp:                   2020-04-03T12:37:42Z
    Host:                        Windows 10.0.18363 AMD64
    CMake:                       3.16.4
    CMake generator:             Visual Studio 15 2017
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/MSBuild/15.0/Bin/MSBuild.exe
    MSVC:                        1916

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (14 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (28 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (3 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe  (ver 19.16.27035.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP2  /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP2  /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP2   /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP2 /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo stitching video videoio world
    Disabled:                    python2 python3
    Disabled by dependency:      -
    Unavailable:                 java js ts
    Applications:                apps
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI: 
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.0.4-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.0.10)
    JPEG 2000:                   build Jasper (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.54.100)
      avformat:                  YES (58.29.100)
      avutil:                    YES (56.31.100)
      swscale:                   YES (5.5.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   C:/build/master_winpack-build-win64-vc15/build/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                C:/build/master_winpack-build-win64-vc15/build/3rdparty/ippicv/ippicv_win/iw
    Eigen:                       NO
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                C:/build/master_winpack-build-win64-vc15/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            C:/utils/soft/python27-x64/python.exe

  Java:                          
    ant:                         C:/utils/soft/apache-ant-1.9.7/bin/ant.bat (ver 1.9.7)
    JNI:                         C:/Program Files/Java/jdk1.8.0_112/include C:/Program Files/Java/jdk1.8.0_112/include/win32 C:/Program Files/Java/jdk1.8.0_112/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    C:/build/master_winpack-build-win64-vc15/install
-----------------------------------------------------------------


OpenCL Platforms: 
    NVIDIA CUDA
        dGPU: GeForce GTX 970 (OpenCL 1.2 CUDA)
    Intel(R) OpenCL
        iGPU: Intel(R) HD Graphics 4600 (OpenCL 1.2 )
        CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (OpenCL 1.2 (Build 10094))
Current OpenCL device: 
    Type = dGPU
    Name = GeForce GTX 970
    Version = OpenCL 1.2 CUDA
    Driver version = 442.88
    Address bits = 64
    Compute units = 13
    Max work group size = 1024
    Local memory size = 48 KB
    Max memory allocation size = 1 GB
    Double support = Yes
    Host unified memory = No
    Device extensions:
        cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics
        cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics
        cl_khr_fp64
        cl_khr_byte_addressable_store
        cl_khr_icd
        cl_khr_gl_sharing
        cl_nv_compiler_options
        cl_nv_device_attribute_query
        cl_nv_pragma_unroll
        cl_nv_d3d10_sharing
        cl_khr_d3d10_sharing
        cl_nv_d3d11_sharing
        cl_nv_copy_opts
        cl_nv_create_buffer
        cl_khr_int64_base_atomics
        cl_khr_int64_extended_atomics
    Has AMD Blas = No
    Has AMD Fft = No
    Preferred vector width char = 1
    Preferred vector width short = 1
    Preferred vector width int = 1
    Preferred vector width long = 1
    Preferred vector width float = 1
    Preferred vector width double = 1
OpenCV's HW features list:
    ID=  1 (MMX) -> ON
    ID=  2 (SSE) -> ON
    ID=  3 (SSE2) -> ON
    ID=  4 (SSE3) -> ON
    ID=  5 (SSSE3) -> ON
    ID=  6 (SSE4.1) -> ON
    ID=  7 (SSE4.2) -> ON
    ID=  8 (POPCNT) -> ON
    ID=  9 (FP16) -> ON
    ID= 10 (AVX) -> ON
    ID= 11 (AVX2) -> ON
    ID= 12 (FMA3) -> ON
Total available: 12
Parallel framework: ms-concurrency (nthreads=8)
```

**Comment by alalek** [comment]
> echo %PATH%
> opencv\4.3.0

conflicts with

> import cv2
> E:/dev/opencv-3.4.9

Please avoid mess with versions.

**Comment by zchrissirhcz** [comment]
@alalek Thanks for pointint out the messy `cv2` versions.

Now the checks & results:

>Python version,  cv2 version?

```bash
E:\dbg\zz\test>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
```

>Test file content? Custom python module path?

```bash
E:\dbg\zz\test>cat test.py
# coding: utf-8
import numpy as np

import sys
sys.path.insert(0, 'D:/lib/opencv/4.3.0/build/python')

import cv2

im = np.ones((100,100,3))
im = im * 0.73 * 255
#print(im)
cv2.imwrite('res-py.bmp', im)
```

>Running result?

```bash
E:\dbg\zz\test>python test.py
['D:/lib/opencv/4.3.0/build/python', 'D:\\lib\\opencv\\4.3.0\\build\\python\\cv2\\python-3.7', 'E:\\dbg\\zz\\test', 'E:\\soft\\Python\\Python37\\python37.zip', 'E:\\soft\\Python\\Python37\\DLLs', 'E:\\soft\\Python\\Python37\\lib', 'E:\\soft\\Python\\Python37', 'E:\\soft\\Python\\Python37\\lib\\site-packages']
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import cv2
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 86, in bootstrap
    import cv2
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 96, in <module>
    bootstrap()
  File "D:/lib/opencv/4.3.0/build/python\cv2\__init__.py", line 23, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

>Dump result of `opencv_version_win32.exe`?
The same as previous comment.

**Comment by alalek** [comment]
> sys.path.insert(0, 'D:/lib/opencv/4.3.0/build/python')

0 index is reserved. Use 1 instead.

Please try this too:

> add full path with "/cv2/python-3.7" here

```.diff
-sys.path.insert(0, 'D:/lib/opencv/4.3.0/build/python')
+sys.path.insert(1, 'D:/lib/opencv/4.3.0/build/python/cv2/python-3.7')
```

Please collect diagnostic information, like [this](https://github.com/opencv/opencv/blob/4.3.0/platforms/winpack_dldt/package-tests/test_dnn_backends.py#L8-L10).

**Comment by zchrissirhcz** [comment]
@alalek  Thanks. Got it. Works.

In conlusion, to use OpenCV Windows prebuilt package provided Python interface (for temporary usage), use:
```python
import sys
sys.path.insert(1, '/path/to/opencv/build/python/cv2/python-x.y')
import cv2
```
(Use `1` instead of `0` since `0` means "current directory" where we invode current python script, [ref](https://stackoverflow.com/questions/10095037/why-use-sys-path-appendpath-instead-of-sys-path-insert1-path))

**Comment by tosa-no-onchan** [comment]
My case
opencv-4.1.0-vc14_vc15.exe
extract to C:\app\opencv-4.1.0

#set PYTHONPATH to batch files
set PYTHONPATH=C:\app\opencv-4.1.0\build\python;%PYTHONPATH%
