### ISSUE TITLE
OpenCV 4.2.0 with python3 and CUDA : Segfault on cv2.VideoCapture()

### ISSUE THREAD

**Issue by flavienbwk** [opencv/opencv#17141]
Hello,

I encounter a problem with OpenCV that I have for several days now : it segfaults when calling the `cv2.VideoCapture()` function.

When launching my script (with GDB) :

```
extract-all_1   | Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
extract-all_1   | 0x00007f83857fe33b in bool pyopencv_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(_object*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ArgInfo const&) [clone .isra.1286] ()
extract-all_1   |    from /usr/lib/python3/dist-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so
extract-all_1   | (gdb) quit
```

> When running my script without GDB, the container exits with code 139

I identified the problem occures when calling the "cv2.VideoCapture()" function :

```python3
def perform_video_extraction(video_path):
    input_movie = cv2.VideoCapture(video_path)
    nb_total_frames = int(input_movie.get(cv2.CAP_PROP_FRAME_COUNT))
    [...]
```

Hints :

- I process MP4 video files
- I've tried compressing my videos that are >30fps to 25fps
- I've tried with OpenCV 3.4.9, 4.1.0, 4.1.1, 4.1.2, 4.2.0 and 4.3.0 (pip install)
- I've tried compiling OpenCV 4.2.0 and 4.3.0 from source
- I've tried each version above successively with CUDA 10.0, 10.1 and 10.2 : each version for each case produces the same error
- This segfault is not reproduced when using the CPU (non-cuda) version of OpenCV
- This error reproduces on several computers with the same or different brands and graphic cards
- I have another identical PC to mine that **doesn't** reproduce the error. I've tried `docker save`ing its container image and execute it on my PC, but it produces segfault.

Here is my Dockerfile (CUDA 10.2 with OpenCV 4.2.0 built from source) : https://pastebin.com/raw/a42wtcRG

Here is what the `cmake` summary build returns : https://pastebin.com/raw/SFPUakyL

My config :

- Ubuntu 18.04
- Nvidia Docker [(CUDA 10.2, CUDNN 7, Ubuntu 18.04, devel)](https://gitlab.com/nvidia/container-images/cuda/blob/master/dist/ubuntu18.04/10.2/devel/cudnn7/Dockerfile)
- Python 3.6

**Have you any recommendation for debugging this problem ?**

Thank you

**Comment by alalek** [comment]
Please try to compile binaries with debug symbols ("-g" compiler option). Something like this:
```
cmake ... -DOPENCV_EXTRA_CXX_FLAGS=-g
```

**Comment by flavienbwk** [comment]
I've tried adding this. No change : segfault as well.

I've spotted a line about this `cv2.cpython-36m-x86_64-linux-gnu.so` file. Maybe it can help you ?

```
[ 87%] Linking CXX shared module ../../lib/python3/cv2.cpython-36m-x86_64-linux-gnu.so
-- Installing: /usr/lib/python3/dist-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so
-- Set runtime path of "/usr/lib/python3/dist-packages/cv2/python-3.6/cv2.cpython-36m-x86_64-linux-gnu.so" to "/usr/lib/x86_64-linux-gnu:/usr/local/cuda-10.2/lib64"
```

**Comment by flavienbwk** [comment]
I managed to debug the problem. Due to a stupid **encoding** issue.

Adding :

```Dockerfile
ENV LANG C.UTF-8
```

to my Dockerfile managed to make the container run (my original pastbin mentioned this line but after doublecheck, I didn't have it).

I was able to find out this idea because of this more accurate stacktrace from GDB : 

```
root@f42846d26d89:/opencv-4.2.0/build# gdb --args python3 -u /usr/app/scripts/extract.py
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/python3 -u /usr/app/scripts/extract.py
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7f29b384d700 (LWP 137)]
[New Thread 0x7f29b304c700 (LWP 138)]
[New Thread 0x7f29ae84b700 (LWP 139)]
[New Thread 0x7f29ae04a700 (LWP 140)]
[New Thread 0x7f29a9849700 (LWP 141)]
[New Thread 0x7f29a9048700 (LWP 142)]
[New Thread 0x7f29a6847700 (LWP 143)]
[New Thread 0x7f29a2046700 (LWP 144)]
[New Thread 0x7f299f845700 (LWP 145)]
[New Thread 0x7f299d044700 (LWP 146)]
[New Thread 0x7f299a843700 (LWP 147)]
[New Thread 0x7f2998042700 (LWP 148)]
[New Thread 0x7f2997841700 (LWP 149)]
[New Thread 0x7f2993040700 (LWP 150)]
[New Thread 0x7f299283f700 (LWP 151)]
[New Thread 0x7f298e03e700 (LWP 152)]
[New Thread 0x7f298b83d700 (LWP 153)]
[New Thread 0x7f298b03c700 (LWP 154)]
[New Thread 0x7f298683b700 (LWP 155)]
[New Thread 0x7f298403a700 (LWP 156)]
[New Thread 0x7f2981839700 (LWP 157)]
[New Thread 0x7f297f038700 (LWP 158)]
[New Thread 0x7f297c837700 (LWP 159)]
[New Thread 0x7f297c036700 (LWP 160)]
[New Thread 0x7f2977835700 (LWP 161)]
[New Thread 0x7f2975034700 (LWP 162)]
[New Thread 0x7f2972833700 (LWP 163)]
[New Thread 0x7f2970032700 (LWP 164)]
[New Thread 0x7f296d831700 (LWP 165)]
[New Thread 0x7f296b030700 (LWP 166)]
[New Thread 0x7f296a82f700 (LWP 167)]
[New Thread 0x7f295be6a700 (LWP 168)]
[New Thread 0x7f295b669700 (LWP 169)]
[New Thread 0x7f295ae68700 (LWP 170)]
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
getUnicodeString (str="", obj=<optimized out>) at /opencv-4.2.0/modules/python/src2/pycompat.hpp:69
69	        if (PyBytes_Check(bytes))
(gdb) backtrace
#0  0x00007f2959a1433b in getUnicodeString (str="", obj=<optimized out>) at /opencv-4.2.0/modules/python/src2/pycompat.hpp:69
#1  0x00007f2959a1433b in pyopencv_to<std::__cxx11::basic_string<char> >(PyObject*, cv::String&, ArgInfo const&) (obj=<optimized out>, value="", info=...)
    at /opencv-4.2.0/modules/python/src2/cv2.cpp:731
#2  0x00007f2959dd6a2d in pyopencv_cv_VideoCapture_VideoCapture(pyopencv_VideoCapture_t*, PyObject*, PyObject*) (self=0x7f2965344190, args=0x7f296307c3c8, kw=0x0)
    at /opencv-4.2.0/build/modules/python_bindings_generator/pyopencv_generated_types_content.h:21272
#3  0x0000000000551b81 in  ()
#4  0x00000000005aa6ec in _PyObject_FastCallKeywords ()
#5  0x000000000050abb3 in  ()
#6  0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#7  0x0000000000509d48 in  ()
#8  0x000000000050aa7d in  ()
#9  0x000000000050c5b9 in _PyEval_EvalFrameDefault ()
#10 0x0000000000508245 in  ()
#11 0x000000000050b403 in PyEval_EvalCode ()
#12 0x0000000000635222 in  ()
#13 0x00000000006352d7 in PyRun_FileExFlags ()
#14 0x0000000000638a8f in PyRun_SimpleFileExFlags ()
#15 0x0000000000639631 in Py_Main ()
#16 0x00000000004b0f40 in main ()
(gdb) list
64	{
65	    bool res = false;
66	    if (PyUnicode_Check(obj))
67	    {
68	        PyObject * bytes = PyUnicode_AsUTF8String(obj);
69	        if (PyBytes_Check(bytes))
70	        {
71	            const char * raw = PyBytes_AsString(bytes);
72	            if (raw)
73	            {
(gdb) 
```

> `/opencv-4.2.0` being my install path

It seems like my filenames were not in a right encoding format.
