### ISSUE TITLE
cv2.error: OpenCV(3.4.2) /io/opencv/modules/flann/src/miniflann.cpp:315: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'

### ISSUE THREAD

**Issue by InstantWindy** [opencv/opencv#17209]
```
cv2.error: OpenCV(3.4.2) /io/opencv/modules/flann/src/miniflann.cpp:315: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'
> type=1016
> 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "compute_match.py", line 152, in <module>
    main(cfg)
  File "compute_match.py", line 113, in main
    for pair in tqdm(pairs))
  File "/home/pcl/anaconda3/envs/match/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/pcl/anaconda3/envs/match/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/pcl/anaconda3/envs/match/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/pcl/anaconda3/envs/match/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/pcl/anaconda3/envs/match/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
cv2.error: OpenCV(3.4.2) /io/opencv/modules/flann/src/miniflann.cpp:315: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'
> type=1016
> 

```

**Comment by nlw0** [comment]
I'm getting this problem if I try to run this tutorial example with the LSH parameters.

https://docs.opencv.org/master/dc/dc3/tutorial_py_matcher.html

```
    matches = flann.knnMatch(np.array(des1,dtype=np.int8),np.array(des2,dtype=np.int8),k=2)
cv2.error: OpenCV(4.4.0) /home/nicolau/src/opencv-4.4.0/modules/flann/src/miniflann.cpp:315: error: (-210:Unsupported format or combination of formats) in function 'buildIndex_'
> type=5
> 
```
