### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKNSt6__ndk16vectorIiNS6_9allocatorIiEEEE"

### ISSUE THREAD

**Issue by weinixuehao** [opencv/opencv#17521]
##### System information (version)
- OpenCV => 3.4.3
- Operating System / Platform => android
- Compiler => bazel with ndk

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKNSt6__ndk16vectorIiNS6_9allocatorIiEEEE" referenced by "/data/app/com.google.mediapipe.apps.hededgedetectiongpu-2/lib/arm64/libmediapipe_jni.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:994)
        at java.lang.System.loadLibrary(System.java:1533)
        at com.google.mediapipe.apps.hededgedetectiongpu.MainActivity.<clinit>(MainActivity.java:52)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by weinixuehao** [comment]
I have checked my appcation .apk, there is an opencv so in it and other symbols works.

**Comment by alalek** [comment]
> _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKNSt6__ndk16vectorIiNS6_9allocatorIiEEEE
> ndk16

Try to check `2cv7imwrite`symbols in your `libopencv_*.so` (using `nm` tool from Android NDK).

**Comment by weinixuehao** [comment]
![image](https://user-images.githubusercontent.com/17869361/84564460-73ee8d00-ad94-11ea-9d93-f28af01e7236.png)
It seems to have

**Comment by alalek** [comment]
Not same, there is missing ndk16.
This means that different compilers / compiler options are used for OpenCV compilation and for your application.

**Comment by weinixuehao** [comment]
I'm sorry I didn't quite understand what you mean. I am using the mediapipe project recently, which uses pre-built opencv as a dependency. mediapipe uses ndk api level is 21. mediapipe used bazel as build system.
mediapipe:https://github.com/google/mediapipe.git

```
http_archive(
    name = "android_opencv",
    build_file = "@//third_party:opencv_android.BUILD",
    strip_prefix = "OpenCV-android-sdk",
    type = "zip",
    url = "https://github.com/opencv/opencv/releases/download/3.4.3/opencv-3.4.3-android-sdk.zip",
)
```

opencv_android.BUILD file
```
OPENCV_LIBRARY_NAME = "libopencv_java3.so"

OPENCVANDROIDSDK_NATIVELIBS_PATH = "sdk/native/libs/"

OPENCVANDROIDSDK_JNI_PATH = "sdk/native/jni/"

[cc_library(
    name = "libopencv_" + arch,
    srcs = [OPENCVANDROIDSDK_NATIVELIBS_PATH + arch + "/" + OPENCV_LIBRARY_NAME],
    hdrs = glob([
        OPENCVANDROIDSDK_JNI_PATH + "include/**/*.h",
        OPENCVANDROIDSDK_JNI_PATH + "include/**/*.hpp",
    ]),
    includes = [
        OPENCVANDROIDSDK_JNI_PATH + "include",
    ],
    visibility = ["//visibility:public"],
    alwayslink = 1,
) for arch in [
    "arm64-v8a",
    "armeabi-v7a",
    "x86",
    "x86_64",
]]
```

**Comment by alalek** [comment]
OpenCV 3.4.3 Android SDK has been compiled with NDK r10e (like OpenCV 3.0 - first major version) using GCC 4.8/4.9.
These binaries are not compatible with NDK r16 as the message says.

You should try to switch on modern OpenCV 4.x version or rebuild OpenCV 3.4 from sources with compatible NDK of your application.

**Comment by weinixuehao** [comment]
@alalek 
Thanks very much!
