### ISSUE TITLE
findChessboardCorners. TypeError: Expected Ptr<cv::UMat> for argument 'corners'

### ISSUE THREAD

**Issue by CherginetsDA** [opencv/opencv#17541]
##### System information
- OpenCV:  4.2.0.34
- Operating System / Platform => Ubuntu 18.04.1

##### Detailed description

If I use a function cv2.findChessboardCorners with 
`cv2.CALIB_CB_FAST_CHECK, 
cv2.CALIB_CB_ADAPTIVE_THRESH, 
cv2.CALIB_CB_FILTER_QUADS `
(which equalse 8L,1L,4L), then I get an error:
```
Traceback (most recent call last):
  File "./calibration.py", line 114, in <module>
    main()
  File "./calibration.py", line 59, in main
    ret, corners = cv2.findChessboardCorners(blurred, CHECKERBOARD, cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FILTER_QUADS)
TypeError: Expected Ptr<cv::UMat> for argument 'corners'
```
When I change cv2.CALIB_CB_FAST_CHECK, ,cv2.CALIB_CB_ADAPTIVE_THRESH, cv2.CALIB_CB_FILTER_QUADS to  8, 1 and 4 respectively, everything work fine.

###### Python code example
```
#!/usr/bin/env python
import cv2

def main():
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        cap.open()
        if not cap.isOpened():
            print("Camera didn't open...")
            exit()
    print("Camera opened...")
    kin ='a'
    while kin is not ord('e'):
        ret,frame = cap.read()
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blurred = cv2.GaussianBlur(gray, (3, 3), 0)
        ret,corners = cv2.findChessboardCorners(blurred, (6,9), cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FILTER_QUADS)
        if ret:
            corners_sub = cv2.cornerSubPix(blurred,corners,(11,11),(-1,-1),criteria)
            frame = cv2.drawChessboardCorners(frame, (6,9), corners2,ret)
        cv2.imshow("Image",frame)
        kin = cv2.waitKey(1)
    cv2.destroyAllWindows()

if __name__=='__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
```

**Comment by berak** [comment]
@CherginetsDA ,

```
>>> help(cv2.findChessboardCorners)
Help on built-in function findChessboardCorners:

findChessboardCorners(...)
    findChessboardCorners(image, patternSize[, corners[, flags]]) -> retval, corners

```


so, you're putting the flags, where (optionial) corners were expected, if you omit the corners, you need to call it with a "named argument" like:

    ret,corners = cv2.findChessboardCorners(blurred, (6,9), flags=cv2.CALIB_CB_FAST_CHECK + cv2.CALIB_CB_ADAPTIVE_THRESH + cv2.CALIB_CB_FILTER_QUADS)
