### ISSUE TITLE
ERROR: Failed building wheel for opencv-python

### ISSUE THREAD

**Issue by siddharthcb** [opencv/opencv#18359]
hi i am running on python3.7 and pip 20.2.3 on ubuntu 18.04, arm64.
when i am trying to install opencv using `pip3 install opencv-python`
i am getting following error.
`ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/smartagri/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpfga9p4k1
       cwd: /tmp/pip-install-fmfauafs/opencv-python
  Complete output (9 lines):
    File "/tmp/pip-build-env-jorjrbsz/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/tmp/pip-build-env-jorjrbsz/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/tmp/pip-build-env-jorjrbsz/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
      "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
  Traceback (most recent call last):
  
  Problem with the CMake installation, aborting build. CMake executable is cmake
  ----------------------------------------
  ERROR: Failed building wheel for opencv-python
Failed to build opencv-python
ERROR: Could not build wheels for opencv-python which use PEP 517 and cannot be installed directly`

**Comment by torta24x** [comment]
**Error :**

System : aws ec2 instance (t2 small)
issue : while installing `pip3 install opencv-python`

```
  Problem with the CMake installation, aborting build. CMake executable is cmake
  
  ----------------------------------------
  Failed building wheel for opencv-python
  Running setup.py clean for opencv-python

```
 **Worked for me**
`pip3 install --upgrade pip setuptools wheel`

**Comment by paulagd** [comment]
Hi,

I can download the video with torch.hub but when I try to reproduce the code for detecting the video I get the following:

```
> python detect.py --source decelera_landscape.mov --save-txt
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', img_size=640, iou_thres=0.45, save_conf=False, save_dir='inference/output', save_txt=True, source='decelera_landscape.mov', update=False, view_img=False, weights='yolov5s.pt')
Using CUDA device0 _CudaDeviceProperties(name='Tesla T4', total_memory=15109MB)

Fusing layers...
Model Summary: 140 layers, 7.45958e+06 parameters, 0 gradients
[ERROR:0] global /usr/src/opencv-4.4.0/modules/videoio/src/cap.cpp (142) open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.4.0) /usr/src/opencv-4.4.0/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): /home/paulagomez/yolov5/decelera_landscape.mov in function 'icvExtractPattern'


Results saved to inference/output
Done. (0.017s)
```

Any idea of what is whappening?

Thanks!!
