### ISSUE TITLE
iOS build: ObjC bindings compilation failed

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#18446]
Error message:
```
build-armv7-iphoneos/modules/objc/gen/objc/dnn/Dnn.mm:384:32: error: no matching conversion for C-style cast from 'NSString *__strong _Nonnull' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
    cv::dnn::resetMyriadDevice((std::string)device);
                               ^~~~~~~~~~~~~~~~~~~
```

Generated code becomes differ.

dnn.txt diff:
```.diff
- void cv::dnn::resetMyriadDevice()
+ void cv::dnn::resetMyriadDevice(string device = "MYRIAD")
```

Dnn.mm before:
```
//
//  void cv::dnn::resetMyriadDevice()
//
+ (void)resetMyriadDevice {
    cv::dnn::resetMyriadDevice();
}
```

Dnn.mm after:
```
//
//  void cv::dnn::resetMyriadDevice(string device = "MYRIAD")
//
+ (void)resetMyriadDevice:(NSString*)device {
    cv::dnn::resetMyriadDevice((std::string)device);
}

+ (void)resetMyriadDevice {
    cv::dnn::resetMyriadDevice();
}
```

/cc @komakai 

Appears after changing of build environment on `macosx-1` builder.
Perhaps related to default Python version and its modules.

Under investigation...

---

**Update**: gen_obj.py doesn't work with python3, so it is Python 2 changes (system or from homebrew) 
<details>
<summary>Python3 error</summary>

```
3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)]
Objective-C: Processing OpenCV modules: 11
Traceback (most recent call last):
  File "/Volumes/build-storage/build/precommit_ios/opencv/modules/objc/generator/../generator/gen_objc.py", line 1601, in <module>
    generator.gen(srcfiles, module, dstdir, objc_base_path, common_headers, manual_classes)
  File "/Volumes/build-storage/build/precommit_ios/opencv/modules/objc/generator/../generator/gen_objc.py", line 871, in gen
    self.add_enum(decl)
  File "/Volumes/build-storage/build/precommit_ios/opencv/modules/objc/generator/../generator/gen_objc.py", line 779, in add_enum
    if enum_fix.has_key(constinfo.classname):
AttributeError: 'dict' object has no attribute 'has_key'
```

</details>

**Comment by alalek** [comment]
**Invalid**, related to this PR only: #18220 ([build](http://pullrequest.opencv.org/buildbot/builders/precommit_ios/builds/24861))
