### ISSUE TITLE
Can not build macOS framework

### ISSUE THREAD

**Issue by calebmitcler** [opencv/opencv#18654]
- OpenCV current master
- macOS Catalina 10.15.7
- Python 2.7.16
- cmake version 3.18.4

I clone the repo, try to build the osx framework and get following error 

** BUILD FAILED **

The following build commands failed:
	CompileC platforms/osx/build/build/build-x86_64-macosx/modules/world/OpenCV.build/Release/opencv_world.build/Objects-normal/x86_64/opencv-onnx.pb.o modules/dnn/misc/onnx/opencv-onnx.pb.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
============================================================
ERROR: Command '['xcodebuild', 'MACOSX_DEPLOYMENT_TARGET=10.13', 'ARCHS=x86_64', '-sdk', 'macosx', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 148, in build
    self._build(outdir)
  File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 122, in _build
    self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
  File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 255, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
  File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 44, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'MACOSX_DEPLOYMENT_TARGET=10.13', 'ARCHS=x86_64', '-sdk', 'macosx', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65

seems to be same issues as [13759](https://github.com/opencv/opencv/issues/13759) so i fiddle with MACOSX_DEPLOYMENT_TARGET in platforms/osx/build_framework.py. same errors no matter the target

##### Steps to reproduce
git clone opencv
cd platforms/osx
python build_framework.py  build

**Comment by andy380743909** [comment]
> * OpenCV current master
> * macOS Catalina 10.15.7
> * Python 2.7.16
> * cmake version 3.18.4
> * Xcode 12.1 Build version 12A7403
> 
> I clone the repo, try to build the osx framework and get following error
> 
> ```
> ** BUILD FAILED **
> 
> The following build commands failed:
> 	CompileC platforms/osx/build/build/build-x86_64-macosx/modules/world/OpenCV.build/Release/opencv_world.build/Objects-normal/x86_64/opencv-onnx.pb.o modules/dnn/misc/onnx/opencv-onnx.pb.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)
> ============================================================
> ERROR: Command '['xcodebuild', 'MACOSX_DEPLOYMENT_TARGET=10.13', 'ARCHS=x86_64', '-sdk', 'macosx', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
> ============================================================
> Traceback (most recent call last):
>   File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 148, in build
>     self._build(outdir)
>   File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 122, in _build
>     self.buildOne(target[0], target[1], main_build_dir, cmake_flags)
>   File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 255, in buildOne
>     execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir)
>   File "/Volumes/Dev/XCode-openCV/please/opencv/platforms/ios/build_framework.py", line 44, in execute
>     retcode = check_call(cmd, cwd = cwd)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> CalledProcessError: Command '['xcodebuild', 'MACOSX_DEPLOYMENT_TARGET=10.13', 'ARCHS=x86_64', '-sdk', 'macosx', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
> ```
> 
> seems to be same issues as [13759](https://github.com/opencv/opencv/issues/13759) so i fiddle with MACOSX_DEPLOYMENT_TARGET in platforms/osx/build_framework.py. same errors no matter the target
> 
> ##### Steps to reproduce
> git clone opencv cd platforms/osx python build_framework.py build

+1
