### ISSUE TITLE
Problem building Python3 Install/Package OpenCV 4.5.1 on Windows

### ISSUE THREAD

**Issue by ProtoSD** [opencv/opencv#19335]
CMake 3.19.2
Visual Studio Community 2019
Anaconda 3.8.5 64-bit
Windows 7 Pro 64-bit

Similar Issues:
https://github.com/opencv/opencv/issues/17860
https://github.com/opencv/opencv/issues/16384
https://github.com/opencv/opencv/issues/17632

My problem seems related to the above issues, but I'm not clear about how to fix it.

My problem occurs  after building Install or trying to build Package. Also, I'm building with Contrib.

When I try to import cv2 I get:  

```
    (base) C:\Users\admin>python
    Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cv2
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\ProgramData\Anaconda3\lib\site-packages\cv2\__init__.py", line 102, in <module>
        bootstrap()
      File "C:\ProgramData\Anaconda3\lib\site-packages\cv2\__init__.py", line 90, in bootstrap
        import cv2
    ImportError: DLL load failed while importing cv2: The specified module could not be found.
    >>>
```

When I try to build Package I get:
```
Build started...
    1>------ Build started: Project: PACKAGE, Configuration: Release x64 ------
    1>CPack: Create package using NSIS
    1>CPack: Install projects
    1>CPack: - Install project: OpenCV [Release]
    1>CPack: -   Install component: dev
    1>CPack: -   Install component: libs
    1>CPack: -   Install component: licenses
    1>CPack: -   Install component: main
    1>CPack: -   Install component: pdb
    1>CPack: -   Install component: python
    1>CMake Error at G:/_DEV/build/modules/python3/cmake_install.cmake:42 (message):
    1>  ABSOLUTE path INSTALL DESTINATION forbidden (by caller):
    1>  C:/ProgramData/Anaconda3/Lib/site-packages/cv2/__init__.py
    1>Call Stack (most recent call first):
    1>  G:/_DEV/build/modules/cmake_install.cmake:185 (include)
    1>  G:/_DEV/build/cmake_install.cmake:122 (include)
    1>
    1>
    1>EXEC : CPack error : Error when generating package: OpenCV
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: The command "setlocal
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: cd G:\_DEV\build
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: G:
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: :cmEnd
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: :cmErrorLevel
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: exit /b %1
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: :cmDone
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(153,5): error MSB3073: :VCEnd" exited with code 1.
    1>Done building project "PACKAGE.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

```
-DCMAKE_CONFIGURATION_TYPES:STRING="Release" 
-DINSTALL_PYTHON_EXAMPLES:BOOL="1" 
-DOPENCV_EXTRA_MODULES_PATH:PATH="G:/_DEV/opencv_contrib/modules" 
-DOPENCV_GENERATE_SETUPVARS:BOOL="1" 

-DOPENCV_PYTHON3_VERSION:BOOL="1"
-DBUILD_opencv_python3:BOOL="1"

-DPYTHON3INTERP_FOUND=TRUE
-DPYTHON3LIBS_FOUND=TRUE
-DPYTHON3LIBS_VERSION_STRING=3.8.5
-DPYTHON3_DEBUG_LIBRARIES=PYTHON_DEBUG_LIBRARY-NOTFOUND
-DPYTHON3_EXECUTABLE=C:/ProgramData/Anaconda3/python.exe
-DPYTHON3_INCLUDE_PATH=C:/ProgramData/Anaconda3/include
-DPYTHON3_LIBRARY:FILEPATH="C:/ProgramData/Anaconda3/libs/python38.lib"
-DPYTHON3_NUMPY_INCLUDE_DIRS=C:/ProgramData/Anaconda3/lib/site-packages/numpy/core/include
-DPYTHON3_NUMPY_VERSION=1.19.2
-DPYTHON3_PACKAGES_PATH=C:/ProgramData/Anaconda3/Lib/site-packages
-DPYTHON_DEFAULT_AVAILABLE=TRUE
-DPYTHON_DEFAULT_EXECUTABLE=C:/ProgramData/Anaconda3/python.exe
```

**Comment by shreeman1000** [comment]
I have the same issue did you find a solution?

**Comment by LaurentBerger** [comment]
Are you admin or can you write in repository?

**Comment by alalek** [comment]
CPack is usually used for creation of re-distribution packages (without absolute paths in installation layout).
You need to pass `cmake ... -DINSTALL_CREATE_DISTRIB=ON` to receive re-distribution package installation layout.

> -DPYTHON3_PACKAGES_PATH=C:/ProgramData/Anaconda3/Lib/site-packages

Or change that as CPack blames.

---

Build / usage questions should go to Users OpenCV Q/A forum: https://forum.opencv.org/
