### ISSUE TITLE
can't open camera by index

### ISSUE THREAD

**Issue by richierh** [opencv/opencv#19356]
I use zbarcam which has dependencies on opencv
why I got this error ? 

```
[INFO   ] [Camera      ] Provider: opencv(['camera_picamera', 'camera_gi'] ignored)
[ WARN:0] global /tmp/pip-req-build-ms668fyv/opencv/modules/videoio/src/cap_v4l.cpp (893) open VIDEOIO(V4L2:/dev/video0): can't open camera by index
 Traceback (most recent call last):
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy_garden/xcamera/xcamera.py", line 85, in _on_index
     self._on_index_dispatch(*largs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy_garden/xcamera/xcamera.py", line 88, in _on_index_dispatch
     super()._on_index(*largs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 70, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 120, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
 AttributeError: 'NoneType' object has no attribute 'shape'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 48, in <module>
     DemoApp().run()
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/app.py", line 918, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/app.py", line 691, in load_kv
     root = Builder.load_file(rfilename)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 306, in load_file
     return self.load_string(data, **kwargs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 408, in load_string
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   [Previous line repeated 3 more times]
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 663, in _apply_rule
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     child.apply_class_lang_rules(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy_garden/xcamera/xcamera.kv", line 27:
 ...
      25:
      26:    id: camera
 >>   27:    resolution: 640, 480 # 1920, 1080
      28:    allow_stretch: True
      29:
 ...
 AttributeError: 'NoneType' object has no attribute 'shape'
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 840, in kivy.properties.ListProperty.set
   File "kivy/properties.pyx", line 545, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 600, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1154, in kivy._event.EventObservers._dispatch
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy_garden/xcamera/xcamera.py", line 85, in _on_index
     self._on_index_dispatch(*largs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy_garden/xcamera/xcamera.py", line 88, in _on_index_dispatch
     super()._on_index(*largs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/uix/camera.py", line 103, in _on_index
     self._camera = CoreCamera(index=self.index,
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 70, in __init__
     super(CameraOpenCV, self).__init__(**kwargs)
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/__init__.py", line 70, in __init__
     self.init_camera()
   File "/home/cireng/.virtualenvs/kivypos/lib/python3.8/site-packages/kivy/core/camera/camera_opencv.py", line 120, in init_camera
     self._resolution = (int(frame.shape[1]), int(frame.shape[0]))
 
```

**Comment by furas** [comment]
What system do you use?  
It seems you use some Linux but what distribution and version.

Error shows `open VIDEOIO(V4L2:/dev/video0): can't open camera by index`.   
Do you have `/dev/video0` in your system?  
```
ls /dev/video*
``` 

Did you test your camera directly with `opencv`?

```
import cv2

cap = cv2.VideoCapture('/dev/video0')
ret, frame = cap.read()
print(ret, frame)
```

If you have `/dev/video0` and this code doesn't work then you can try with `sudo` because you may not have privileges.
```
sudo python script.py
```

If this code work then problem can be in `zbarcam` and you would have to ask on `zbarcam` forum/repo

---

I tested this code on `Linux Mint 20` based on `Ubuntu 20.04` and it works without problem.  
I don't have your code with `zbarcam` to test it.

**Comment by oqlaalrefai** [comment]
@furas I try the opencv test and I get this result:
False None

**Comment by furas** [comment]
@oqlaalrefai  

If `sudo` can't find file then you may have to use `/full/path/to/script.py`

`False None` means it couldn't find camera - and it needs different value in `VideoCapture(..)`. OR camera may need some time to `warm up` before it start sending images - it may need to use `time.sleep(...)` before `read()`
