### ISSUE TITLE
opencv.js memory access out of bounds

### ISSUE THREAD

**Issue by naah69** [opencv/opencv#19397]
##### System information (version)

- OpenCV.js-webassembly == 4.5.1
- Operating System / Platform => Windows 64 Bit or MacOS 10.14.6
- Chrome => 87.0.4280.141

##### Detailed description

i use grabcut in js by opencv.js-webassembly == 4.5.1,when the canvas and mask bounds is big,it errors.

i use the bellow code and the canvas and mask bounds is 1000x3500（part of pic ）,it error

[beer3.jpg.zip](https://github.com/opencv/opencv/files/5870829/beer3.jpg.zip)

error log:
```
getAiAssistDraw error RuntimeError: memory access out of bounds
    at malloc (<anonymous>:wasm-function[11613]:0x4ac738)
    at <anonymous>:wasm-function[11171]:0x49e768
    at <anonymous>:wasm-function[3554]:0x15dd85
    at <anonymous>:wasm-function[3548]:0x15cdc8
    at <anonymous>:wasm-function[545]:0x195b2
    at <anonymous>:wasm-function[1040]:0x2b9ca
    at dynCall_viiiiiiii (<anonymous>:wasm-function[11714]:0x4afe0a)
    at Module.dynCall_viiiiiiii (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js:17:7642371)
    at dynCall_viiiiiiii_781 (eval at makeDynCaller (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js), <anonymous>:4:12)
    at Object.grabCut (eval at new_ (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js), <anonymous>:14:1)
    at Object.proto.<computed> [as grabCut] (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js:17:7575575)
    at Object.predict (webpack-internal:///./src/views/tool/editor/ai/pic/grabcut.js:130:71)
    at eval (webpack-internal:///./src/views/tool/editor/ai/algorithm.js:362:29)
    at eval (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:338:22)
    at Engine.scopedRun (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:348:25)
    at Engine.tidy (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:337:21)
CanvasManager.js?4ec2:3439 拉框失败 RuntimeError: memory access out of bounds
    at malloc (<anonymous>:wasm-function[11613]:0x4ac738)
    at <anonymous>:wasm-function[11171]:0x49e768
    at <anonymous>:wasm-function[3554]:0x15dd85
    at <anonymous>:wasm-function[3548]:0x15cdc8
    at <anonymous>:wasm-function[545]:0x195b2
    at <anonymous>:wasm-function[1040]:0x2b9ca
    at dynCall_viiiiiiii (<anonymous>:wasm-function[11714]:0x4afe0a)
    at Module.dynCall_viiiiiiii (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js:17:7642371)
    at dynCall_viiiiiiii_781 (eval at makeDynCaller (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js), <anonymous>:4:12)
    at Object.grabCut (eval at new_ (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js), <anonymous>:14:1)
    at Object.proto.<computed> [as grabCut] (webpack-internal:///./node_modules/opencv.js-webassembly/opencv.js:17:7575575)
    at Object.predict (webpack-internal:///./src/views/tool/editor/ai/pic/grabcut.js:130:71)
    at eval (webpack-internal:///./src/views/tool/editor/ai/algorithm.js:362:29)
    at eval (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:338:22)
    at Engine.scopedRun (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:348:25)
    at Engine.tidy (webpack-internal:///./node_modules/@tensorflow/tfjs-core/dist/engine.js:337:21)
```

##### Steps to reproduce

```javascript
 let {canvas, pointList} = data
        let src = cv.imread("part-canvas");
        cv.cvtColor(src, src, cv.COLOR_RGBA2RGB, 0);
        let roiRect = new cv.Rect(0, 0, canvas.width - 1, canvas.height - 1);
        let mask = cv.Mat.zeros(canvas.height, canvas.width, cv.CV_8UC1);
        let bgdModel = new cv.Mat();
        let fgdModel = new cv.Mat();
        let grayMask =undefined
        try {
            if (resultType === LABEL_TYPE_CONST.BOX) {
                cv.grabCut(src, mask, roiRect, bgdModel, fgdModel, 5, cv.GC_INIT_WITH_RECT);
            } else if (resultType === LABEL_TYPE_CONST.POLYGON) {
                $this.initMask(pointList, mask,new cv.Scalar(cv.GC_PR_FGD));
                cv.grabCut(src, mask, roiRect, bgdModel, fgdModel, 3, cv.GC_INIT_WITH_MASK);
            }
            grayMask = $this.generateGrayMask(src, mask);
            let result;
            if (aiInfo.modelName === AI_TYPE_CONST.GRABCUT_PIC_SEGMENT_LITE_FRONT) {
                result = $this.findContours(grayMask, resultType, cv.RETR_EXTERNAL, {enable: true, threshold: 0.0004});
            } else {
                result = $this.findContours(grayMask, resultType, cv.RETR_EXTERNAL);
            }

            // result = result.filter((a) => a.area > 10);
            result.sort((a, b) => b.area - a.area);
            result = [result[0]]
            return result
        }
        finally {
            src.delete()
            mask.delete()
            bgdModel.delete()
            fgdModel.delete()
            if(grayMask){
                grayMask.delete()
            }

        }
```

**Comment by alalek** [comment]
Complete minimal reproducer is required (current code snippet contains non-defined variables).

---

Does it work with smaller image?

---

> opencv.js-webassembly

This is unofficial package.
Please provide build flags of used binaries. Dump `cv.getBuildInformation()`.

---

Please provide reproducer without external dependencies, so we are able to reproduce that on our side.
For example, use interactive [OpenCV.js tutorial pages](https://docs.opencv.org/4.5.1/de/d06/tutorial_js_basic_ops.html).

---

> at malloc

Try to rebuild opencv.js with suggestions from here: https://github.com/emscripten-core/emscripten/issues/5161

**Comment by naah69** [comment]
i build the package .the core javascript is download by https://docs.opencv.org/4.5.1/opencv.js.
![image](https://user-images.githubusercontent.com/25682169/105806862-b8efc880-5fdf-11eb-8de1-953982477621.png)

**Comment by naah69** [comment]
$this.initMask
```
initMask: function (pointList, mask, color, line = {enable: false, thickness: 1, type: 4,color:0}) {
        let polygonVector = new cv.MatVector()
        let polygonMat=undefined
        try {
            let pointdata = []
            for (let i = 0; i < pointList.length; i++) {
                let x = pointList[i][0];
                let y = pointList[i][1];
                pointdata.push(Math.floor(x))
                pointdata.push(Math.floor(y))
                // if (line.enable && lastPoint) {
                //     cv.line(
                //         mask,
                //         new cv.Point(lastPoint.x, lastPoint.y),
                //         new cv.Point(x, y),
                //         line.color,
                //         line.thickness,
                //         line.type
                //     )
                // }
                // lastPoint = pointList[i]
            }
            polygonMat = cv.matFromArray(pointList.length, 1, cv.CV_32SC2, new Int32Array(pointdata));
            polygonVector.push_back(polygonMat)
            cv.fillPoly(mask, polygonVector, color)
        }finally {
            if(polygonMat){
                polygonMat.delete()
            }
            polygonVector.delete()
        }


    }
```

**Comment by naah69** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script>
        function onOpenCvReady(){
            console.log("opencv.js load")
        }
    </script>
    <script src="https://docs.opencv.org/4.5.1/opencv.js"  onload="onOpenCvReady();"></script>
<!--    <script src="opencv.js"></script>-->
</head>
<body>
<img src="beer.jpg" id="img" style="display:none;">
<button onclick="run()">run</button>
<canvas id="part-canvas"  ></canvas>

<script>

    function run(){
        let img=document.getElementById("img")
        let pointList=[
            [1134,97],
            [1042,904],
            [979,1745],
            [921,4032],
            [2000,4032],
            [1987,0],
        ]
        let partcanvas=document.getElementById("part-canvas")
        partcanvas.width=1090
        partcanvas.height=4032
        let partCtx = partcanvas.getContext("2d")
        partCtx.clearRect(0, 0, partcanvas.width, partcanvas.height);
        partCtx.drawImage(img, 910, 0, partcanvas.width, partcanvas.height, 0, 0, partcanvas.width, partcanvas.height);
        let src = cv.imread("part-canvas");
        cv.cvtColor(src, src, cv.COLOR_RGBA2RGB, 0);
        let roiRect = new cv.Rect(0, 0, partcanvas.width - 1, partcanvas.height - 1);
        let mask = cv.Mat.zeros(partcanvas.height, partcanvas.width, cv.CV_8UC1);
        let bgdModel = new cv.Mat();
        let fgdModel = new cv.Mat();
        let grayMask =undefined
        try {
            initMask(pointList, mask,new cv.Scalar(cv.GC_PR_FGD));
            cv.imshow('part-canvas', mask)
            cv.grabCut(src, mask, roiRect, bgdModel, fgdModel, 3, cv.GC_INIT_WITH_MASK);
            console.log("run done")
            cv.imshow('part-canvas', mask);
        }catch(e){
            console.log(e)
        }
        finally {
            src.delete()
            mask.delete()
            bgdModel.delete()
            fgdModel.delete()
            if(grayMask){
                grayMask.delete()
            }
        }
    }

    function initMask(pointList, mask, color, line = {enable: false, thickness: 1, type: 4,color:0}) {
        let polygonVector = new cv.MatVector()
        let polygonMat=undefined
        try {
            let pointdata = []
            for (let i = 0; i < pointList.length; i++) {
                let x = pointList[i][0]-910;
                let y = pointList[i][1];
                pointdata.push(Math.floor(x))
                pointdata.push(Math.floor(y))
            }
            polygonMat = cv.matFromArray(pointList.length, 1, cv.CV_32SC2, new Int32Array(pointdata));
            polygonVector.push_back(polygonMat)
            cv.fillPoly(mask, polygonVector, color)
        }finally {
            if(polygonMat){
                polygonMat.delete()
            }
            polygonVector.delete()
        }
    }
</script>
</body>
</html>
```

**Comment by alalek** [comment]
I'm able to run provided code.
- web page consumes ~1GB memory
- it prints "run done" on console (after a ~minute)
- no exception is shown (Google Chrome: `Version 87.0.4280.66 (Official Build) (64-bit)`)
- memory is not released after run() exit (on "Task Manager" window)
- second and third run also pass

P.S. 1GB is all memory available to WASM code (build-time option). Perhaps code hits this limit.

**Comment by naah69** [comment]
how to view the memory that WASM consumes，i try to find memory leak
