### ISSUE TITLE
version 4.5.1 findFundamentalMat Magsac algorithm SegmentFault across platforms on specific keypoint input

### ISSUE THREAD

**Issue by xiongzhiyao** [opencv/opencv#19639]
##### System information (version)
- OpenCV => 4.5.1
- Operating System / Platform => both on ubuntu 18.04 and macbook catalina
- Compiler => installed using pip

##### Detailed description

Magsac in cv2.findFundamentalMat() crashes on a specific pair of input points

##### Steps to reproduce

```
>>> import cv2
>>> cv2.__version__
'4.5.1'
>>> import numpy as np
>>> x = np.array([[941, 890],
...        [596, 940],
...        [898, 941],
...        [894, 933],
...        [586, 938],
...        [902, 933],
...        [887, 935]])
>>> y = np.array([[1416,  806],
...        [1157,  852],
...        [1380,  855],
...        [1378,  843],
...        [1145,  849],
...        [1378,  843],
...        [1378,  843]])
>>> cv2.findFundamentalMat(x, y, cv2.USAC_MAGSAC, 3, 0.99)
```

<details>

<summary>Python .py code</summary>

```.py
import numpy as np
import cv2 as cv

x = np.array([[941, 890],
        [596, 940],
        [898, 941],
        [894, 933],
        [586, 938],
        [902, 933],
        [887, 935]])

y = np.array([[1416,  806],
        [1157,  852],
        [1380,  855],
        [1378,  843],
        [1145,  849],
        [1378,  843],
        [1378,  843]])

res = cv.findFundamentalMat(x, y, cv.USAC_MAGSAC, 3, 0.99)

print(res)
```

</details>

**Comment by alalek** [comment]
GDB stacktrace (master branch):

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007fffdb960e97 in cv::usac::SampsonErrorImpl::setModelParameters (this=0x5555559d1a90, model=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/estimator.cpp:354
warning: Source file is more recent than executable.
354	        m11=static_cast<float>(m[0]); m12=static_cast<float>(m[1]); m13=static_cast<float>(m[2]);

(gdb) bt
#0  0x00007fffdb960e97 in cv::usac::SampsonErrorImpl::setModelParameters(cv::Mat const&) (this=0x5555559d1a90, model=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/estimator.cpp:354
#1  0x00007fffdb9fb504 in cv::usac::SPRTImpl::isModelGood(cv::Mat const&) (this=0x555555621b60, model=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/quality.cpp:426
#2  0x00007fffdb9bcc73 in cv::usac::SigmaConsensusImpl::refineModel(cv::Mat const&, cv::usac::Score const&, cv::Mat&, cv::usac::Score&) (this=0x5555558dcf20, in_model=..., best_model_score=..., new_model=..., new_model_score=...)
    at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/local_optimization.cpp:433
#3  0x00007fffdba0634d in cv::usac::Ransac::run(cv::Ptr<cv::usac::RansacOutput>&) (this=0x7fffffffaa50, ransac_output=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/ransac_solvers.cpp:198
#4  0x00007fffdba0d88d in cv::usac::run(cv::Ptr<cv::usac::Model const> const&, cv::_InputArray const&, cv::_InputArray const&, int, cv::Ptr<cv::usac::RansacOutput>&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&) (params=..., points1=..., points2=..., state=4, ransac_output=..., K1_=..., K2_=..., dist_coeff1=..., dist_coeff2=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/ransac_solvers.cpp:1005
#5  0x00007fffdba07e95 in cv::usac::findFundamentalMat(cv::_InputArray const&, cv::_InputArray const&, int, double, double, int, cv::_OutputArray const&)
    (points1=..., points2=..., method=38, thr=3, confidence=0.98999999999999999, max_iters=1000, mask=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/usac/ransac_solvers.cpp:509
#6  0x00007fffdb7ebdc4 in cv::findFundamentalMat(cv::_InputArray const&, cv::_InputArray const&, int, double, double, int, cv::_OutputArray const&)
    (_points1=..., _points2=..., method=38, ransacReprojThreshold=3, confidence=0.98999999999999999, maxIters=1000, _mask=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/fundam.cpp:839
#7  0x00007fffdb7ec8fd in cv::findFundamentalMat(cv::_InputArray const&, cv::_InputArray const&, int, double, double, cv::_OutputArray const&)
    (points1=..., points2=..., method=38, ransacReprojThreshold=3, confidence=0.98999999999999999, mask=...) at /home/alalek/projects/opencv/dev/modules/calib3d/src/fundam.cpp:904
#8  0x00007fffdd2e3110 in pyopencv_cv_findFundamentalMat(PyObject*, PyObject*, PyObject*) (py_args=0x7fffdfbf4720, kw=0x0) at modules/python_bindings_generator/pyopencv_generated_funcs.h:12771
#9  0x00007ffff7d608f9 in cfunction_call () at /lib64/libpython3.9.so.1.0
...
(gdb) p m
$1 = (const double * const) 0x0
```

Crash point is [here](https://github.com/opencv/opencv/blame/e0265c67c6012ca4d41e5fabab1f952e7a319718/modules/calib3d/src/usac/estimator.cpp#L354).
relates #17683
/cc @ivashmak @vpisarev
