### ISSUE TITLE
emcc.bat error code 1

### ISSUE THREAD

**Issue by ChristianBarette** [opencv/opencv#19700]
opencv 4.5.0
Cmake 3.20.0-rc2
Emscripten 1.38.31
Visual Studio 2021 1.54

I get the following error in Emscripten.cmake when I try to create opencv.js 4.5.0 :
emcc.bat'   -v"! Process returned with error code 1.

see all details below :

C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources\platforms\js>build_js.py --opencv_dir C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources --emscripten_dir C:\Users\Chris\Desktop\Webdev\emsdk\emsdk-master\emscripten\1.38.31 C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\build
Args: Namespace(build_dir='C:\\Users\\Chris\\Desktop\\Webdev\\opencv_4.5.0_w\\opencv\\build', build_doc=False, build_flags=None, build_perf=False, build_test=False, build_wasm=False, build_wasm_intrin_test=False, clean_build_dir=False, cmake_option=None, config='C:\\Users\\Chris\\Desktop\\Webdev\\opencv_4.5.0_w\\opencv\\sources\\platforms\\js\\opencv_js.config.py', config_only=False, disable_wasm=False, emscripten_dir='C:\\Users\\Chris\\Desktop\\Webdev\\emsdk\\emsdk-master\\emscripten\\1.38.31', enable_exception=False, opencv_dir='C:\\Users\\Chris\\Desktop\\Webdev\\opencv_4.5.0_w\\opencv\\sources', simd=False, skip_config=False, threads=False)
Check dir C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\build (create: True, clean: False)
Check dir C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources (create: False, clean: False)
Check dir C:\Users\Chris\Desktop\Webdev\emsdk\emsdk-master\emscripten\1.38.31 (create: False, clean: False)
=====
===== Config OpenCV.js build for default target
=====
Executing: ['cmake', '-DENABLE_PIC=FALSE', '-DCMAKE_BUILD_TYPE=Release', "-DCMAKE_TOOLCHAIN_FILE='C:\\Users\\Chris\\Desktop\\Webdev\\emsdk\\emsdk-master\\emscripten\\1.38.31\\cmake\\Modules\\Platform\\Emscripten.cmake'", "-DCPU_BASELINE=''", "-DCPU_DISPATCH=''", '-DCV_TRACE=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DWITH_1394=OFF', '-DWITH_ADE=OFF', '-DWITH_VTK=OFF', '-DWITH_EIGEN=OFF', '-DWITH_FFMPEG=OFF', '-DWITH_GSTREAMER=OFF', '-DWITH_GTK=OFF', '-DWITH_GTK_2_X=OFF', '-DWITH_IPP=OFF', '-DWITH_JASPER=OFF', '-DWITH_JPEG=OFF', '-DWITH_WEBP=OFF', '-DWITH_OPENEXR=OFF', '-DWITH_OPENGL=OFF', '-DWITH_OPENVX=OFF', '-DWITH_OPENNI=OFF', '-DWITH_OPENNI2=OFF', '-DWITH_PNG=OFF', '-DWITH_TBB=OFF', '-DWITH_TIFF=OFF', '-DWITH_V4L=OFF', '-DWITH_OPENCL=OFF', '-DWITH_OPENCL_SVM=OFF', '-DWITH_OPENCLAMDFFT=OFF', '-DWITH_OPENCLAMDBLAS=OFF', '-DWITH_GPHOTO2=OFF', '-DWITH_LAPACK=OFF', '-DWITH_ITT=OFF', '-DWITH_QUIRC=OFF', '-DBUILD_ZLIB=ON', '-DBUILD_opencv_apps=OFF', '-DBUILD_opencv_calib3d=ON', '-DBUILD_opencv_dnn=ON', '-DBUILD_opencv_features2d=ON', '-DBUILD_opencv_flann=ON', '-DBUILD_opencv_gapi=OFF', '-DBUILD_opencv_ml=OFF', '-DBUILD_opencv_photo=ON', '-DBUILD_opencv_imgcodecs=OFF', '-DBUILD_opencv_shape=OFF', '-DBUILD_opencv_videoio=OFF', '-DBUILD_opencv_videostab=OFF', '-DBUILD_opencv_highgui=OFF', '-DBUILD_opencv_superres=OFF', '-DBUILD_opencv_stitching=OFF', '-DBUILD_opencv_java=OFF', '-DBUILD_opencv_java_bindings_generator=OFF', '-DBUILD_opencv_js=ON', '-DBUILD_opencv_python2=OFF', '-DBUILD_opencv_python3=OFF', '-DBUILD_opencv_python_bindings_generator=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_PACKAGE=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_PERF_TESTS=OFF', '-DBUILD_DOCS=OFF', '-DWITH_PTHREADS_PF=OFF', '-DCV_ENABLE_INTRINSICS=OFF', '-DBUILD_WASM_INTRIN_TESTS=OFF', "-DCMAKE_C_FLAGS='-s USE_PTHREADS=0 '", "-DCMAKE_CXX_FLAGS='-s USE_PTHREADS=0 '", 'C:\\Users\\Chris\\Desktop\\Webdev\\opencv_4.5.0_w\\opencv\\sources']
Re-run cmake no build system arguments
CMake Error at C:/Users/Chris/Desktop/Webdev/emsdk/emsdk-master/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake:113 (message):
  Failed to fetch compiler version information with command
  "'C:/Users/Chris/Desktop/Webdev/emsdk/emsdk-master/emscripten/1.38.31/emcc.bat'
  -v"! Process returned with error code 1.
Call Stack (most recent call first):
  C:/Users/Chris/Desktop/Webdev/cmake-3.20.0-rc2-windows-x86_64/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:109 (enable_language)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources\platforms\js\build_js.py", line 269, in <module>
    builder.config()
  File "C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources\platforms\js\build_js.py", line 192, in config
    execute(cmd)
  File "C:\Users\Chris\Desktop\Webdev\opencv_4.5.0_w\opencv\sources\platforms\js\build_js.py", line 23, in execute
    raise Fail("Child returned: %s" % retcode)
__main__.Fail: Child returned: 1

**Comment by ChristianBarette** [comment]
I close this one and open another one.
