### ISSUE TITLE
 features_stride = float(config['feature_extractor'][0]['first_stage_features_stride'][0])

### ISSUE THREAD

**Issue by Jeffin21** [opencv/opencv#20075]
was trying to make pbtxt file using my trained model and config file and got this error using tf_text_graph_mask_rcnn.py
opencv version 4.5.2

```
Traceback (most recent call last):
  File "E:\mask_rcnn_inception_v2_coco_2018_01_28\opencv\sources\samples\dnn\tf_text_graph_mask_rcnn.py", line 41, in <module>
    features_stride = float(config['feature_extractor'][0]['first_stage_features_stride'][0])
KeyError: 'first_stage_features_stride'
```

files
https://drive.google.com/drive/folders/19OEdYZsGu8l41L42BW3ZswISor1RXvRd?usp=sharing

**Comment by Jeffin21** [comment]
@alalek small update on it 
i found the  missing key first_stage_features_stride in above and i fixed that and now new issue came 

```
File "E:\mask_rcnn_inception_v2_coco_2018_01_28\opencv\sources\samples\dnn\tf_text_graph_common.py", line 313, in writeTextGraph
    cv.dnn.writeTextGraph(modelPath, outputPath)
cv2.error: OpenCV(4.5.2) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi271kac\opencv\modules\dnn\src\tensorflow\tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: E:\mask_rcnn_inception_v2_coco_2018_01_28\motabiju\saved_model.pb in function 'cv::dnn::ReadTFNetParamsFromBinaryFileOrDie'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\mask_rcnn_inception_v2_coco_2018_01_28\opencv\sources\samples\dnn\tf_text_graph_mask_rcnn.py", line 53, in <module>
    writeTextGraph(args.input, args.output, ['num_detections', 'detection_scores', 'detection_boxes', 'detection_classes', 'detection_masks'])
  File "E:\mask_rcnn_inception_v2_coco_2018_01_28\opencv\sources\samples\dnn\tf_text_graph_common.py", line 316, in writeTextGraph
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'

E:\mask_rcnn_inception_v2_coco_2018_01_28\opencv\sources\samples\dnn>
```
