### ISSUE TITLE
Java desktop bindings: (-201:Incorrect size of input array) Input size not specified in function 'cv::dnn::dnn4_v20210301::Model::Impl::processFrame'

### ISSUE THREAD

**Issue by distlibs** [opencv/opencv#20377]
##### System information (version)
- OpenCV => 4.5.2
- Operating System / Platform => Windows 10 64 Bit
- Java => 11.0.4

Downloaded from here: https://sourceforge.net/projects/opencvlibrary/files/4.5.2/opencv-4.5.2-vc14_vc15.exe/download

##### Detailed description

I got error when I try to detect objects using `detect` method of `DetectionModel` object. 

```
Exception in thread "main" CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.2) C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\dnn\src\model.cpp:96: error: (-201:Incorrect size of input array) Input size not specified in function 'cv::dnn::dnn4_v20210301::Model::Impl::processFrame'
]
	at org.opencv.dnn.DetectionModel.detect_2(Native Method)
	at org.opencv.dnn.DetectionModel.detect(DetectionModel.java:146)
	at app.Testing.main(Testing.java:27)

Process finished with exit code 1
```

##### Steps to reproduce

Here is a code:

```
import org.opencv.core.*;
import org.opencv.dnn.DetectionModel;
import org.opencv.dnn.Dnn;
import org.opencv.dnn.Net;
import org.opencv.imgcodecs.Imgcodecs;

public class Testing {
    static {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    public static void main(String[] args) {
        Mat img = Imgcodecs.imread("test.jpg");

        Net net = Dnn.readNetFromDarknet("yolov4.cfg", "yolov4.weights");

        DetectionModel model = new DetectionModel(net);
        model.setInputScale(0.0039215);
        model.setInputSize(416, 416);
        model.setInputSwapRB(true);

        MatOfInt classIds = new MatOfInt();
        MatOfFloat scores = new MatOfFloat();
        MatOfRect boxes = new MatOfRect();
        model.detect(img, classIds, scores, boxes);
    }
}
```

Maybe I doing something wrong using Java. An image exists because I tried to display it with `HighGui.imshow`. I tried to run similar code with Python. Everything works fine.

CFG file and weights downloaded from here: https://github.com/AlexeyAB/darknet/releases

**Comment by alalek** [comment]
> 4.5.2

Try latest release first (4.5.3).

**Comment by distlibs** [comment]
A code is working fine using 4.5.3
