### ISSUE TITLE
output name getting via getUnconnectedOutLayersNames is different from description of OpenVINO model

### ISSUE THREAD

**Issue by AvenSun** [opencv/opencv#20380]
##### System information (version)
- OpenCV => OpenCV+OpenVINO Windows package 4.5.2 or 4.5.3
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Python => 3.7.9

##### Detailed description
output name getting via getUnconnectedOutLayersNames is different from description of OpenVINO model

[person-vehicle-bike-detection-2004](https://docs.openvinotoolkit.org/latest/omz_models_model_person_vehicle_bike_detection_2003.html)

[face-detection-0206](https://docs.openvinotoolkit.org/latest/omz_models_model_face_detection_0206.html)

[person-detection-0203](https://docs.openvinotoolkit.org/latest/omz_models_model_person_detection_0203.html)

currently found three models,  the doc page listed above said it has two outputs boxes and labels

but there's not just two when we try getting output via dnn.getUnconnectedOutLayersNames

then if we pass the output to forward of DNN, error occurred

```
model person-detection-0203
====OutputNames====
['1095_1096.0', '1312_1313.0', '1529_1530.0', '1746_1747.0', '1963_1964.0', '223
4_2235.0', 'boxes', 'labels']
====OutputNames====
Traceback (most recent call last):
  File "dnn.py", line 58, in <module>
    outs = net.forward(outNames)
cv2.error: [ PARAMETER_MISMATCH ] Failed to set output Blob. Dimensions mismatch
.
```
if we specify output ['boxes', 'labels'] , same error

```
model person-detection-0203
====OutputNames====
['1095_1096.0', '1312_1313.0', '1529_1530.0', '1746_1747.0', '1963_1964.0', '223
4_2235.0', 'boxes', 'labels']
====OutputNames====
Traceback (most recent call last):
  File "dnn.py", line 58, in <module>
    outs = net.forward(outNames)
cv2.error: [ PARAMETER_MISMATCH ] Failed to set output Blob. Dimensions mismatch
.
```

if we specify output ['boxes'] , there's no error, but getting different result when running multi times
the input image is the same one

##### Steps to reproduce

```
import cv2

# OpenCV+OpenVINO Windows package
# https://github.com/opencv/opencv/wiki/Intel's-Deep-Learning-Inference-Engine-backend#opencvopenvino-windows-package-community-version

model_root = '/intel'

# https://docs.openvinotoolkit.org/latest/omz_models_model_person_vehicle_bike_detection_2003.html
prefix = 'person-vehicle-bike-detection-2004'
size = (448,256)

# https://docs.openvinotoolkit.org/latest/omz_models_model_face_detection_0206.html
prefix = 'face-detection-0206'
size = (640,640)

# https://docs.openvinotoolkit.org/latest/omz_models_model_person_detection_0203.html
prefix = 'person-detection-0203'
size = (864,480)

print('model {}'.format(prefix))
net = cv2.dnn.Net_readFromModelOptimizer(
    model_root + '/{}/FP32/{}.xml'.format(prefix,prefix),
    model_root+ '/{}/FP32/{}.bin'.format(prefix,prefix))
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_INFERENCE_ENGINE)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU)

frame = cv2.imread('./test.jpg')
blob = cv2.dnn.blobFromImage(frame, 1.0, size, swapRB=False, crop=False)

outNames = net.getUnconnectedOutLayersNames()
print('====OutputNames====')
print(outNames)
print('====OutputNames====')

# outNames = []
# outNames.append("boxes")
# outNames.append("labels")

net.setInput(blob)
outs = net.forward(outNames)

print('====OriginalResult====')
print(outs[0][0])
print('====OriginalResult====')
```

**Comment by alalek** [comment]
> the doc page listed above said it has two outputs boxes and labels

Model's XML file defines 8 outputs:

```
$ grep "Result" intel/person-vehicle-bike-detection-2004/FP32/person-vehicle-bike-detection-2004.xml 
		<layer id="3015" name="boxes/sink_port_0" type="Result" version="opset1">
		<layer id="3022" name="labels/sink_port_0" type="Result" version="opset1">
		<layer id="3023" name="TopK_907/sink_port_0" type="Result" version="opset1">
		<layer id="3024" name="TopK_691/sink_port_0" type="Result" version="opset1">
		<layer id="3025" name="TopK_1555/sink_port_0" type="Result" version="opset1">
		<layer id="3026" name="TopK_1339/sink_port_0" type="Result" version="opset1">
		<layer id="3027" name="TopK_1123/sink_port_0" type="Result" version="opset1">
		<layer id="3028" name="TopK_1829/sink_port_0" type="Result" version="opset1">
```

InferenceEngine (IE) API [`.getOutputsInfo()`](https://docs.openvinotoolkit.org/2021.4/classInferenceEngine_1_1CNNNetwork.html#af8a6200f549b15a895e2cfefd304a9c2) returns this information:

```
Output: 'TopK_1123.0' precison=FP32 dims=1 [ 336]
Output: 'TopK_1339.0' precison=FP32 dims=1 [ 84]
Output: 'TopK_1555.0' precison=FP32 dims=1 [ 24]
Output: 'TopK_1829.0' precison=FP32 dims=1 [ 100]
Output: 'TopK_691.0' precison=FP32 dims=1 [ 1000]
Output: 'TopK_907.0' precison=FP32 dims=1 [ 1000]
Output: 'boxes' precison=FP32 dims=2 [ 100 5]
Output: 'labels' precison=I32 dims=1 [ 100]
```

`.getUnconnectedOutLayersNames()` returns the same names:

```
OpenCV output names: 8
- TopK_1123.0
- TopK_1339.0
- TopK_1555.0
- TopK_1829.0
- TopK_691.0
- TopK_907.0
- boxes
- labels
```

---

Observed `PARAMETER_MISMATCH` exceptions are triggered by these 2 issues:
- 1D layouts. OpenCV uses Mat internally which supports 2D+ layouts only (1D is forced as 2D). See #17393 (the same 1D problem) and #18594 (still incomplete).
- OpenCV DNN module supports FP32 output only. See 'labels' layout. It is with `I32` precision. OpenCV DNN tries to reconfigure output precision [here](https://github.com/opencv/opencv/blob/4.5.3/modules/dnn/src/ie_ngraph.cpp#L603), but looks like this doesn't work anymore. Exception message is:
  `[ PARAMETER_MISMATCH ] Failed to set output blob with precision: FP32, if CNNNetwork output blob precision is: I32`

/cc @dkurt

**Comment by AvenSun** [comment]
```
<meta_data>
		<MO_version value="2021.3.0-2767-91fe355156e-releases/2021/3"/>
		<cli_parameters>
			<caffe_parser_path value="DIR"/>
			<data_type value="FP32"/>
			<disable_nhwc_to_nchw value="False"/>
			<disable_omitting_optional value="False"/>
			<disable_resnet_optimization value="False"/>
			<disable_weights_compression value="False"/>
			<enable_concat_optimization value="False"/>
			<enable_flattening_nested_params value="False"/>
			<enable_ssd_gluoncv value="False"/>
			<extensions value="DIR"/>
			<framework value="onnx"/>
			<freeze_placeholder_with_value value="{}"/>
			<generate_deprecated_IR_V7 value="False"/>
			<input value="image"/>
			<input_model value="DIR/model.onnx"/>
			<input_model_is_text value="False"/>
			<input_shape value="[1,3,256,448]"/>
			<k value="DIR/CustomLayersMapping.xml"/>
			<keep_shape_ops value="True"/>
			<legacy_mxnet_model value="False"/>
			<log_level value="ERROR"/>
			<mean_scale_values value="{'image': {'mean': None, 'scale': array([255.])}}"/>
			<mean_values value="()"/>
			<model_name value="person-vehicle-bike-detection-2004"/>
			<output value="['boxes', 'labels']"/>
			<output_dir value="DIR"/>
			<placeholder_data_types value="{}"/>
			<placeholder_shapes value="{'image': array([  1,   3, 256, 448])}"/>
			<progress value="False"/>
			<remove_memory value="False"/>
			<remove_output_softmax value="False"/>
			<reverse_input_channels value="True"/>
			<save_params_from_nd value="False"/>
			<scale_values value="image[255.0]"/>
			<silent value="False"/>
			<static_shape value="False"/>
			<stream_output value="False"/>
			<unset unset_cli_parameters="batch, counts, disable_fusing, disable_gfusing, finegrain_fusing, input_checkpoint, input_meta_graph, input_proto, input_symbol, mean_file, mean_file_offsets, move_to_preprocess, nd_prefix_name, pretrained_model_name, saved_model_dir, saved_model_tags, scale, tensorboard_logdir, tensorflow_custom_layer_libraries, tensorflow_custom_operations_config_update, tensorflow_object_detection_api_pipeline_config, tensorflow_use_custom_operations_config, transformations_config"/>
		</cli_parameters>
	</meta_data>
```
I thought the node   **/net/meta_data/cli_parameters/output[@value]**  is the output of network

and the [document page](https://docs.openvinotoolkit.org/latest/omz_models_model_person_vehicle_bike_detection_2003.html) just lists these two

![openvino](https://user-images.githubusercontent.com/5615543/125166322-b5d34800-e1cd-11eb-8f5b-6c11a92e8b6e.jpg)
