### ISSUE TITLE
iOS Build fails with OpenCV4.4.0

### ISSUE THREAD

**Issue by helloooideeeeea** [opencv/opencv#20645]
- OpenCV => 4.4.0
- Operating System / Platform => macos Big sur 11.5.1
- Compiler => Xcode 12.5.1
- cmake => 3.20.1
- python => 2.7.18

I have tried to build from the source code because I had to remove a specific OpenCV module from OpenCV 4.4.0.
However, the following error was output and could not succee built .

( OpenCV 4.5.3 succeeded in build. )

Build execution command: $ python opencv/platforms/ios/build_framework.py ios

How do you edit it, succeed in build?

Complement:
Because the build fails for another reason, I edited the cmake command execution script (opencv/platforms/ios/build_framework.py). IPHONEOS_DEPLOYMENT_TARGET = '8.0' to '9.0'.

```
CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/MatExt.swift (in target 'opencv_objc_framework' from project 'opencv2')
    cd /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -emit-bc /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/ByteVectorExt.swift /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/CvTypeExt.swift /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/DoubleVectorExt.swift /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/FloatVectorExt.swift /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/IntVectorExt.swift -primary-file /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/MatExt.swift -emit-module-path /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt\~partial.swiftmodule -emit-module-doc-path /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt\~partial.swiftdoc -emit-module-source-info-path /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt.dia -emit-dependencies-path /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt.d -target armv7-apple-ios9.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -I /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/lib/Release -F /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/lib/Release -swift-version 5 -enforce-exclusivity\=checked -O -serialize-debugging-options -Xcc -working-directory -Xcc /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen -Xcc -Wno-incomplete-umbrella -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/swift-overrides.hmap -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/lib/Release/include -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/install/include -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/install/include/opencv2 -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/imgproc -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/ml -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/photo -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/dnn -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/features2d -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/imgcodecs -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/videoio -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/calib3d -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/objdetect -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/video -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/DerivedSources-normal/armv7 -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/DerivedSources/armv7 -Xcc -I/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/DerivedSources -Xcc -DCMAKE_INTDIR\=\"Release-iphoneos\" -target-sdk-version 14.5 -module-name opencv2 -o /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/framework_build/opencv2.build/Release-iphoneos/opencv_objc_framework.build/Objects-normal/armv7/MatExt.bc
/Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/MatExt.swift:36:18: error: cannot find type 'Mat' in scope
public extension Mat {
                 ^~~

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/ByteVectorExt.swift
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/CvTypeExt.swift
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/DoubleVectorExt.swift
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/FloatVectorExt.swift
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/IntVectorExt.swift
	CompileSwift normal armv7 /Users/me_name/Downloads/opencv/ios/build/build-armv7-iphoneos/modules/objc/gen/objc/core/MatExt.swift
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
(7 failures)
============================================================
ERROR: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
============================================================
Traceback (most recent call last):
  File "opencv/platforms/ios/build_framework.py", line 137, in build
    self._build(outdir)
  File "opencv/platforms/ios/build_framework.py", line 123, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "opencv/platforms/ios/build_framework.py", line 256, in buildOne
    execute(buildcmd + ["-target", "ALL_BUILD", "build"], cwd = builddir + "/modules/objc/framework_build")
  File "opencv/platforms/ios/build_framework.py", line 40, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/Users/me_name/.pyenv/versions/2.7.18/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['xcodebuild', 'BITCODE_GENERATION_MODE=bitcode', 'IPHONEOS_DEPLOYMENT_TARGET=9.0', 'ARCHS=armv7', '-sdk', 'iphoneos', '-configuration', 'Release', '-parallelizeTargets', '-jobs', '16', '-target', 'ALL_BUILD', 'build']' returned non-zero exit status 65
```

**Comment by alalek** [comment]
> OpenCV 4.4.0
> OpenCV 4.5.3 succeeded in build

We don't maintain outdated releases due to limited resources.
4.5.3 is update for OpenCV 4.x series. Previous 4.x releases are outdated and not supported.

**Comment by helloooideeeeea** [comment]
I got it.

I tried build on AWS mac instance.
build successed.

mac catalina 10.15.7
Xcode 11.6
