### ISSUE TITLE
SystemError: <class 'cv2.VideoCapture'>

### ISSUE THREAD

**Issue by houjim** [opencv/opencv#20917]
Hi ,
I used the VideoCapture function to call the camera, but something went wrong. Is this a bug? My CV version is 4.5.3 .
import cv2
cap = cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('WindowName',gray)
    if cv2.waitKey(1)&0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

cv2.error: OpenCV(4.5.3) /Users/runner/miniforge3/conda-bld/libopencv_1633800950233/work/modules/videoio/src/cap.cpp:239: error: (-215:Assertion failed) !info.backendFactory.empty() in function 'open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/master/python/cv2video.py", line 2, in <module>
    cap = cv2.VideoCapture(0)
SystemError: <class 'cv2.VideoCapture'> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/master/python/cv2video.py", line 2, in <module>
    cap = cv2.VideoCapture(1)
SystemError: <class 'cv2.VideoCapture'> returned a result with an error set

**Comment by alalek** [comment]
> 4.5.3

According to issue's template (which you have removed):
- you must check with latest OpenCV release.
- don't open duplicates

**Comment by shohoku10yyl** [comment]
Hello, I met the same problem as you , have you solved this problem?
