### ISSUE TITLE
Python: sporadic failures of `get_cache_dir_test`

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#21120]
Python tests are launched in parallel (different processes for Python 2.7 / 3.x).

```
======================================================================
ERROR: test_get_cache_dir_imread_interop_jpeg (test_fs_cache_dir.get_cache_dir_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\build\precommit_custom_windows\4.x\opencv\modules\python\test\test_fs_cache_dir.py", line 35, in test_get_cache_dir_imread_interop_jpeg
    self.get_cache_dir_imread_interop("jpg")
  File "C:\build\precommit_custom_windows\4.x\opencv\modules\python\test\test_fs_cache_dir.py", line 27, in get_cache_dir_imread_interop
    os.remove(test_file_name)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\build\\precommit_custom_windows\\build\\_ocl_tmp\\opencv\\4.5-dev\\downloads\\test.jpg'

======================================================================
ERROR: test_get_cache_dir_imread_interop_png (test_fs_cache_dir.get_cache_dir_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\build\precommit_custom_windows\4.x\opencv\modules\python\test\test_fs_cache_dir.py", line 32, in test_get_cache_dir_imread_interop_png
    self.get_cache_dir_imread_interop("png")
  File "C:\build\precommit_custom_windows\4.x\opencv\modules\python\test\test_fs_cache_dir.py", line 27, in get_cache_dir_imread_interop
    os.remove(test_file_name)
WindowsError: [Error 5] Access is denied: 'C:\\build\\precommit_custom_windows\\build\\_ocl_tmp\\opencv\\4.5-dev\\downloads\\test.png'
```

**Comment by alalek** [comment]
relates #19668

/cc @asmorkalov

**Comment by alalek** [comment]
GHA has the similar problem: https://github.com/opencv/opencv/actions/runs/3807769331/jobs/6507732624

```
test_get_cache_dir_imread_interop_jpeg (test_fs_cache_dir.get_cache_dir_test) ... [ WARN:0@102.959] global loadsave.cpp:244 cv::findDecoder imread_('C:\Users\shiqi\AppData\Local\Temp\opencv\4.x-dev\downloads\test.jpg'): can't open/read file: check file path/integrity
ERROR
test_get_cache_dir_imread_interop_png (test_fs_cache_dir.get_cache_dir_test) ... ERROR

...

======================================================================
ERROR: test_get_cache_dir_imread_interop_jpeg (test_fs_cache_dir.get_cache_dir_test)
Testing OpenCV 4.7.0-dev
Local repo path: c:\GHA-OCV-2\_work\opencv\opencv\opencv
WARNING: OpenCV tests config file (opencv_python_tests.cfg) is missing, running subset of tests
Discovering python tests from: c:\GHA-OCV-2\_work\opencv\opencv\opencv\modules\python\test
----------------------------------------------------------------------
    found 118 tests
Traceback (most recent call last):
  File "c:\GHA-OCV-2\_work\opencv\opencv\opencv\modules\python\test\test_fs_cache_dir.py", line 35, in test_get_cache_dir_imread_interop_jpeg
    self.get_cache_dir_imread_interop("jpg")
  File "c:\GHA-OCV-2\_work\opencv\opencv\opencv\modules\python\test\test_fs_cache_dir.py", line 27, in get_cache_dir_imread_interop
    os.remove(test_file_name)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\shiqi\\AppData\\Local\\Temp\\opencv\\4.x-dev\\downloads\\test.jpg'

======================================================================
ERROR: test_get_cache_dir_imread_interop_png (test_fs_cache_dir.get_cache_dir_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\GHA-OCV-2\_work\opencv\opencv\opencv\modules\python\test\test_fs_cache_dir.py", line 32, in test_get_cache_dir_imread_interop_png
    self.get_cache_dir_imread_interop("png")
  File "c:\GHA-OCV-2\_work\opencv\opencv\opencv\modules\python\test\test_fs_cache_dir.py", line 27, in get_cache_dir_imread_interop
    os.remove(test_file_name)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\shiqi\\AppData\\Local\\Temp\\opencv\\4.x-dev\\downloads\\test.png'
```
