### ISSUE TITLE
cv2.dnn don't support permute operator for 3D data?

### ISSUE THREAD

**Issue by zhoujinhai** [opencv/opencv#21211]
### 1、problem
My model was trained by 3D points,  A permute layer in the model for transpose the input data. After I coverted it into onnx model and the follow error has show  when I readed the net by cv2.dnn.readNetFromONNX().  **Does the cv support `res = xyz.permute(0, 2, 1)`?**

```bash
Traceback (most recent call last):
  File "testFunction.py", line 281, in <module>
    print("$$$$$cv res$$$$: ", net.forward())
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\layers\permute_layer.cpp:138: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'
```

### 2、envs
> python: 3.7.4
> onnx: 1.10.2
> onnxruntime: 1.9.0
> cv2: 4.5.3.36

### 3、codes
I have splited the permute layer into `TestNet`, the code is follow:
```python

class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()

    def forward(self, xyz):
        # xyz==> (B, N, C)
        res = xyz.permute(0, 2, 1)
        return res


if __name__ == "__main__":
    net = TestNet()
    inputs = torch.randn((1, 3, 10))
    out = net(inputs)
    print("**** torch out ******: ", out)
    onnx_path = "./test.onnx"
    print("start convert model to onnx >>>")
    torch.onnx.export(net,  # support torch.nn.Module, torch.jit.ScriptModule or torch.jit.ScriptFunction
                      (inputs, ),
                      onnx_path,
                      verbose=True,
                      input_names=["points"],
                      output_names=["res"],
                      opset_version=12,
                      operator_export_type=torch.onnx.OperatorExportTypes.ONNX,  # ONNX_ATEN_FALLBACK,
                      dynamic_axes={
                          "points": {0: "b", 1: "c", 2: "n"},
                          "res": {0: "b", 1: "n", 2: "c"}
                      }
                      )

    print("onnx model has exported!")

    # inference by onnx
    import onnxruntime
    import onnx
    # check
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)
    so1 = onnxruntime.SessionOptions()
    available_providers = onnxruntime.get_available_providers()

    net_session = onnxruntime.InferenceSession(onnx_path, sess_options=so1, providers=available_providers)
    out = net_session.run(None, {"points": inputs.numpy()})
    print("----onnx runtime out----: ", out)

    import cv2
    net = cv2.dnn.readNetFromONNX(onnx_path)
    # get layer info
    layer_names = net.getLayerNames()

    for name in layer_names:
        id = net.getLayerId(name)
        layer = net.getLayer(id)
        print("layer id : %d, type : %s, name: %s" % (id, layer.type, layer.name))

    print("cv2 load model is OK!")
    print("start set input")
    net.setInput(inputs.numpy().astype(np.float32), name="points")
    print("set input Done")
    print("$$$$$cv res$$$$: ", net.forward())
```

- output
```bash
**** torch out ******:  tensor([[[-1.2937,  1.9868,  0.0909],
         [-0.9117, -0.8731, -0.1538],
         [ 0.0967, -1.0970, -0.6543],
         [-1.1497, -0.7184, -2.5352],
         [ 1.2859,  0.8317,  0.6881],
         [-0.0223,  0.9872,  1.2178],
         [ 0.9625, -2.2484, -0.6857],
         [ 1.9240,  1.1681, -1.1798],
         [-1.3165,  1.4293, -0.7341],
         [ 1.0019,  0.7357,  0.2986]]])
start convert model to onnx >>>
graph(%points : Float(1, 3, 10)):
  %res : Float(1, 10, 3) = onnx::Transpose[perm=[0, 2, 1]](%points) # testFunction.py:166:0
  return (%res)

onnx model has exported!
----onnx runtime out----:  [array([[[-1.2937394 ,  1.9868381 ,  0.09090378],
        [-0.9116994 , -0.87310386, -0.15384082],
        [ 0.09665833, -1.0969893 , -0.6543151 ],
        [-1.1497294 , -0.7183546 , -2.5352223 ],
        [ 1.2858971 ,  0.831663  ,  0.6880769 ],
        [-0.02230639,  0.987236  ,  1.217819  ],
        [ 0.96246654, -2.2483692 , -0.68568254],
        [ 1.923988  ,  1.1680775 , -1.179822  ],
        [-1.3164822 ,  1.4293067 , -0.73408717],
        [ 1.0019474 ,  0.7356518 ,  0.2985982 ]]], dtype=float32)]
layer id : 1, type : Permute, name: res
cv2 load model is OK!
start set input
set input Done
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\dnn.cpp (3512) cv::dnn::dnn4_v20210608::Net::Impl::getLayerShapesRecursively OPENCV/DNN: [Permute]:(res): getMemoryShapes() throws exception. inputs=1 outputs=0/0 blobs=0
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\dnn.cpp (3515) cv::dnn::dnn4_v20210608::Net::Impl::getLayerShapesRecursively     input[0] = [ 1 3 ]
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\dnn.cpp (3525) cv::dnn::dnn4_v20210608::Net::Impl::getLayerShapesRecursively Exception message: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\layers\permute_layer.cpp:138: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

Traceback (most recent call last):
  File "testFunction.py", line 281, in <module>
    print("$$$$$cv res$$$$: ", net.forward())
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\layers\permute_layer.cpp:138: error: (-215:Assertion failed) (int)_numAxes == inputs[0].size() in function 'cv::dnn::PermuteLayerImpl::getMemoryShapes'

```

### 4、other test
**I have try to modify the permute layer to res = xyz.permute(0, 3, 2, 1) in TestNet, and modify the inputs = torch.randn((1,  2, 3, 10)). The code is run successed!**
```python
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()

    def forward(self, xyz):
        # xyz==> (B, N, C)
        res = xyz.permute(0, 3, 2, 1)
        return res


if __name__ == "__main__":
    net = TestNet()
    inputs = torch.randn((1, 4, 3, 10))
    out = net(inputs)
    print("**** torch out ******: ", out)
    onnx_path = "./test.onnx"
    print("start convert model to onnx >>>")
    torch.onnx.export(net,  # support torch.nn.Module, torch.jit.ScriptModule or torch.jit.ScriptFunction
                      (inputs, ),
                      onnx_path,
                      verbose=True,
                      input_names=["points"],
                      output_names=["res"],
                      opset_version=12,
                      operator_export_type=torch.onnx.OperatorExportTypes.ONNX,  # ONNX_ATEN_FALLBACK,
                      dynamic_axes={
                          "points": {0: "b", 1: "c", 2: "n"},
                          "res": {0: "b", 1: "n", 2: "c"}
                      }
                      )

    print("onnx model has exported!")

    # inference by onnx
    import onnxruntime
    import onnx
    # check
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)
    so1 = onnxruntime.SessionOptions()
    available_providers = onnxruntime.get_available_providers()

    net_session = onnxruntime.InferenceSession(onnx_path, sess_options=so1, providers=available_providers)
    out = net_session.run(None, {"points": inputs.numpy()})
    print("----onnx runtime out----: ", out)

    import cv2
    net = cv2.dnn.readNetFromONNX(onnx_path)
 
    layer_names = net.getLayerNames()

    for name in layer_names:
        id = net.getLayerId(name)
        layer = net.getLayer(id)
        print("layer id : %d, type : %s, name: %s" % (id, layer.type, layer.name))

    print("cv2 load model is OK!")
    print("start set input")
    net.setInput(inputs.numpy().astype(np.float32), name="points")
    print("set input Done")
    print("$$$$$cv res$$$$: ", net.forward())

```

**Comment by alalek** [comment]
> inputs = torch.randn((1, 3, 10))

Check this issue: #19091

**Comment by zhoujinhai** [comment]
> > inputs = torch.randn((1, 3, 10))
> 
> Check this issue: #19091

Thanks, I have try used `inputs = torch.randn((1, 3, 10))`, but get the same error!

**Comment by zhoujinhai** [comment]
> > inputs = torch.randn((1, 3, 10))
> 
> Check this issue: #19091

![image](https://user-images.githubusercontent.com/20365125/144974749-0284ffcb-4a70-4bcb-8b81-2c6176439297.png)

Thanks reply, There is no solution at present？

**Comment by zhoujinhai** [comment]
I have modify net like this:
```python
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()

    def forward(self, xyz):
        # xyz==> (B, N, C)
        # xyz = xyz.unsqueeze(0)
        res = xyz.permute(0, 1, 3, 2)
        res = res.squeeze(0)
        return res
```

and `inputs = inputs.unsqueeze(0)`

Then, it runs ok. Is there any other better solution？

**Comment by zhoujinhai** [comment]
@alalek I have met another error, the detail and code is [#21214](https://github.com/opencv/opencv/issues/21214). Can you help me? thanks!
