### ISSUE TITLE
Node [ConstantOfShape]:(13) parse error?

### ISSUE THREAD

**Issue by zhoujinhai** [opencv/opencv#21214]
### 1. question
I am readed the onnx model by cv2.dnn.readNetFromONNX()，I got the follow error:
```bash
Traceback (most recent call last):
  File "testFunction.py", line 269, in <module>
    net = cv2.dnn.readNetFromONNX(onnx_path)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2146: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20210608::ONNXImporter::handleNode'
> Node [ConstantOfShape]:(13) parse error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1833: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20210608::ONNXImporter::handleNode(const class opencv_onnx::NodeProto &)'
> >  (expected: 'inpShape[i] > 0'), where
> >     'inpShape[i]' is 0
> > must be greater than
> >     '0' is 0
> 

```

### 2. envs
> python: 3.7.4
> torch: 1.5.0
> onnx: 1.10.2
> onnxruntime: 1.9.0
> cv2: 4.5.3.36

### 3. pytorch model export to onnx
```python
def farthest_point_sample(xyz, npoint):
    """
    Input:
        xyz: pointcloud data, [B, N, 3]
        npoint: number of samples
    Return:
        centroids: sampled pointcloud index, [B, npoint]
    """
    device = xyz.device
    B, N, C = xyz.shape
    # B = int(B)
    # N = int(N)
    # C = int(C)

    centroids = torch.zeros(B, int(npoint), dtype=torch.long, device=device)
    distance = torch.full((B, N), 1e10, device=device)  # torch.ones(B, N).to(device) * 1e10
    # farthest = torch.randint(0, N, (B,), dtype=torch.long).to(device)  # random choice

    _, farthest = xyz[:, :, 1].max(1)  # torch.max(xyz[:, :, 1], 1)[1]

    batch_indices = torch.arange(B, dtype=torch.long, device=device)

    for i in range(int(npoint)):
        centroids[:, i] = farthest
        centroid = xyz[batch_indices, farthest, :].view(B, 1, 3)
        dist = torch.sum((xyz - centroid) ** 2, -1)
        # mask = dist < distance
        # distance[mask] = dist[mask]
        distance = torch.where(dist < distance, dist, distance)
        farthest = torch.max(distance, -1)[1]

    return centroids


class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()

    def forward(self, xyz):
        # xyz==> (B, N, C)
        xyz = xyz.permute(0, 1, 3, 2)
        xyz = xyz.squeeze(0)
        npoint = 2
        select = farthest_point_sample(xyz, npoint)
        return select


if __name__ == "__main__":
    net = TestNet()
    inputs = torch.randn((1, 3, 20))
    out = net(inputs.unsqueeze(0))
    print("**** torch out ******: ", out)
    onnx_path = "./test.onnx"
    print("start convert model to onnx >>>")
    torch.onnx.export(net,  # support torch.nn.Module, torch.jit.ScriptModule or torch.jit.ScriptFunction
                      (inputs.unsqueeze(0), ),
                      onnx_path,
                      verbose=True,
                      input_names=["points"],
                      output_names=["res"],
                      opset_version=12,
                      operator_export_type=torch.onnx.OperatorExportTypes.ONNX,  # ONNX_ATEN_FALLBACK,
                      dynamic_axes={
                          "points": {1: "b", 2: "c", 3: "n"},
                          "res": {0: "b", 1: "n", 2: "c"}
                      }
                      )
    
    print("onnx model has exported!")
```

### 4. inference
```python
import onnx
import numpy as np
import torch
import onnxruntime
import cv2


if __name__ == "__main__":
    onnx_path = "./test.onnx"
    inputs = torch.randn((1, 3, 15))
    # check
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)
    so1 = onnxruntime.SessionOptions()
    available_providers = onnxruntime.get_available_providers()

    net_session = onnxruntime.InferenceSession(onnx_path, sess_options=so1, providers=available_providers)
    out = net_session.run(None, {"points": inputs.unsqueeze(0).numpy()})
    print("----onnx runtime out----: ", out)

    net = cv2.dnn.readNetFromONNX(onnx_path)
    # 获取各层信息
    layer_names = net.getLayerNames()

    for name in layer_names:
        id = net.getLayerId(name)
        layer = net.getLayer(id)
        print("layer id : %d, type : %s, name: %s" % (id, layer.type, layer.name))

    print("cv2 load model is OK!")
    print("start set input")
    net.setInput(inputs.unsqueeze(0).numpy().astype(np.float32), name="points")
    print("set input Done")
    print("$$$$$cv res$$$$: ", net.forward())
```

- output
```bash
**** torch out ******:  tensor([[16, 14]])
----onnx runtime out----:  [array([[16, 14]], dtype=int64)]
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\onnx\onnx_importer.cpp (2127) cv::dnn::dnn4_v20210608::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [ConstantOfShape]:(13)
Traceback (most recent call last):
  File "E:/code/Server223/pointNet/inference_C++/testFunction.py", line 270, in <module>
    net = cv2.dnn.readNetFromONNX(onnx_path)
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\onnx\onnx_importer.cpp:2146: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20210608::ONNXImporter::handleNode'
> Node [ConstantOfShape]:(13) parse error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-c2l3r8zm\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1833: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20210608::ONNXImporter::handleNode(const class opencv_onnx::NodeProto &)'
> >  (expected: 'inpShape[i] > 0'), where
> >     'inpShape[i]' is 0
> > must be greater than
> >     '0' is 0
> 
```

**Comment by zhoujinhai** [comment]
If I am uncomments the next code in function `farthest_point_sample`:
```python
# B = int(B)
# N = int(N)
# C = int(C)
```
the last error not show, but the model will not supported dynamic inputs. It just only supported the inputs = torch.randn((1, 3, 20))

**Comment by Abdurrahheem** [comment]
@zhoujinhai I coudl run your sample code using OpenCV 5.x and results match with ONNX. 
Unfortunately these kind of dynamic operations are not supported in 4.x.
