### ISSUE TITLE
Cannot load yolov8n-pose ONNX model

### ISSUE THREAD

**Issue by dizcza** [opencv/opencv#23464]
### Descripe the feature and motivation

Ultralytics has just released Yolov8-pose estimation models. But I cannot load them in OpenCV DNN. It'd be really nice to support their models - I'm forced to use onnxruntime.

Here is the model I exported from their `yolov8n-pose.pt` with default parameters: [yolov8n-pose.onnx](https://www.dropbox.com/s/ihotlm7vf4i1l8d/yolov8n-pose.onnx?dl=1)

The error I'm getting:

```
  File "/home/dizcza/Projects/Airtouch/edgeai-yolov5/onnx_inference/yolo_pose_onnx_inference.py", line 148, in inference_video
    net = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Reshape@ai.onnx]:(onnx_node!/model.22/dfl/Reshape) parse error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/layers/reshape_layer.cpp:109: error: (-215:Assertion failed) total(srcShape, srcRange.start, srcRange.end) == maskTotal in function 'computeShapeByReshapeMask'
```

### Additional context

I'm marking the issue as a feature request cause I'm aware of ONNX not fully supported by OpenCV DNN module.

**Comment by dizcza** [comment]
If there is any chance to manually convert their model to something loadable in OpenCV DNN, please let me know. Perhaps, some layers can be stripped/rewritten with the weights untouched. I'm not into ONNX tinkering.

**Comment by dizcza** [comment]
So this happens at the Reshape node:

![Screenshot from 2023-04-06 09-29-20](https://user-images.githubusercontent.com/7688337/230290206-b04c2219-339b-4fcd-8ea2-e249c4c56c86.png)

Surely, it's easily fixed, isn't it?

**Comment by zihaomu** [comment]
Hi @dizcza, have you tried to simplify the ONNX model by `onnxsim` before loading to opencv?
```py
import onnx
import onnxsim

input_shape = np.array([1, 3, 640, 640])
input = dict()
input["images"] = input_shape
out = onnxsim.simplify(onnx_model, input_shapes=input)
```

**Comment by dizcza** [comment]
Doesn't work:

```
WARNING: The argument `input_shapes` is deprecated. Please use `overwrite_input_shapes` and/or `test_input_shapes` instead. An error will be raised in the future.
Traceback (most recent call last):
  File "/home/dizcza/Projects/Airtouch/yolov7-pose-estimation/yolov8.py", line 17, in <module>
    out = onnxsim.simplify(model, input_shapes=input)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 159, in simplify
    overwrite_input_shapes = check_and_update_input_shapes(
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 71, in check_and_update_input_shapes
    input_names = get_input_names(model)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 68, in get_input_names
    input_names = [ipt.name for ipt in get_inputs(model)]
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/onnxsim/onnx_simplifier.py", line 64, in get_inputs
    initializer_names = [x.name for x in model.graph.initializer]
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/ultralytics/yolo/engine/model.py", line 114, in __getattr__
    raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
AttributeError: 'YOLO' object has no attribute 'graph'. See valid attributes below.

    YOLO (You Only Look Once) object detection model.

    Args:
        model (str, Path): Path to the model file to load or create.

    Attributes:
        predictor (Any): The predictor object.
        model (Any): The model object.
        trainer (Any): The trainer object.
        task (str): The type of model task.
        ckpt (Any): The checkpoint object if the model loaded from *.pt file.
        cfg (str): The model configuration if loaded from *.yaml file.
        ckpt_path (str): The checkpoint file path.
        overrides (dict): Overrides for the trainer object.
        metrics (Any): The data for metrics.

    Methods:
        __call__(source=None, stream=False, **kwargs):
            Alias for the predict method.
        _new(cfg:str, verbose:bool=True) -> None:
            Initializes a new model and infers the task type from the model definitions.
        _load(weights:str, task:str='') -> None:
            Initializes a new model and infers the task type from the model head.
        _check_is_pytorch_model() -> None:
            Raises TypeError if the model is not a PyTorch model.
        reset() -> None:
            Resets the model modules.
        info(verbose:bool=False) -> None:
            Logs the model info.
        fuse() -> None:
            Fuses the model for faster inference.
        predict(source=None, stream=False, **kwargs) -> List[ultralytics.yolo.engine.results.Results]:
            Performs prediction using the YOLO model.

    Returns:
        list(ultralytics.yolo.engine.results.Results): The prediction results.
```

**Comment by zihaomu** [comment]
Hi @dizcza, thanks for your feedback. I'm working on it.

**Comment by zihaomu** [comment]
Hi, I just found the `onnxsim` code has a bug.

```py
import onnx
import onnxsim

input_shape = np.array([1, 3, 640, 640])
input = dict()
input["images"] = input_shape

out = onnxsim.simplify(onnx_model, input_shapes=input)
onnx.save(out[0], "path_to_save")
```
And the simplified model can be found at :
[yolov8n-pose_sim.onnx.zip](https://github.com/opencv/opencv/files/11197968/yolov8n-pose_sim.onnx.zip)

It works well on my site.

**Comment by dizcza** [comment]
I've downloaded your file, it doesn't work for me:

```python
import cv2

net = cv2.dnn.readNetFromTensorflow("yolov8n-pose_sim.onnx")
```

```
Traceback (most recent call last):
  File "/home/dizcza/Projects/Airtouch/yolov7-pose-estimation/load_onnx.py", line 3, in <module>
    net = cv2.dnn.readNetFromTensorflow("yolov8n-pose_sim.onnx")
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/tensorflow/tf_io.cpp:42: error: (-2:Unspecified error) FAILED: ReadProtoFromBinaryFile(param_file, param). Failed to parse GraphDef file: yolov8n-pose_sim.onnx in function 'ReadTFNetParamsFromBinaryFileOrDie'
```

**Comment by zihaomu** [comment]
Hi @dizcza, my fault. I forgot the `split` node issue. 
The error your met will be fixed with this PR: https://github.com/opencv/opencv/pull/23482

**Comment by dizcza** [comment]
I tried to build your fork, and it succeeded but I cannot import cv2 in Python although I've setup the correct Python path at the build:
```
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dizcza/Projects/Airtouch/opencv_onnx_fix/build/python_loader/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/dizcza/Projects/Airtouch/opencv_onnx_fix/build/python_loader/cv2/__init__.py", line 112, in bootstrap
    load_first_config([
  File "/home/dizcza/Projects/Airtouch/opencv_onnx_fix/build/python_loader/cv2/__init__.py", line 109, in load_first_config
    raise ImportError('OpenCV loader: missing configuration file: {}. Check OpenCV installation.'.format(fnames))
ImportError: OpenCV loader: missing configuration file: ['config-3.9.py', 'config-3.py']. Check OpenCV installation.
```
