### ISSUE TITLE
Cannot disabled gapi when building OpenCV with python

### ISSUE THREAD

**Issue by WanliZhong** [opencv/opencv#23626]
### Expected behaviour

When set `-DBUILD_opencv_gapi=OFF` during building OpenCV with python, it should be well when I import cv2.

### Actual behaviour

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wanli/Desktop/OpenCV_China/opencv/cmake-build-debug/python_loader/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/wanli/Desktop/OpenCV_China/opencv/cmake-build-debug/python_loader/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/Users/wanli/Desktop/OpenCV_China/opencv/cmake-build-debug/python_loader/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/Users/wanli/miniconda3/envs/opencv-dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/wanli/Desktop/OpenCV_China/opencv/cmake-build-debug/python_loader/cv2/gapi/__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

```

### Steps to reproduce

- build  OpenCV with
  ```shell
  -DBUILD_opencv_python2=OFF
  -DBUILD_opencv_python3=ON
  -DBUILD_opencv_gapi=OFF
  -DPYTHON3_INCLUDE_DIR="path/to/python3.8"
  -DPYTHON3_EXECUTABLE="path/to/bin/python" 
  -DPYTHON3_NUMPY_INCLUDE_DIRS="path/to/site-packages/numpy/core/include/"
  -DCMAKE_OSX_ARCHITECTURES=arm64 
  -DCMAKE_SYSTEM_PROCESSOR=arm64
  ```
- MacOS
- architecture arm 64
- opencv 4.x

**Comment by WanliZhong** [comment]
Thanks, it works for me when I remove the whole build folder. But it doesn't work if I only remove python_loader folder.

It will throw error
```shell
In file included from /Users/wanli/Desktop/OpenCV_China/opencv/modules/python/src2/cv2.cpp:11:
/Users/wanli/Desktop/OpenCV_China/opencv/cmake-build-full/modules/python_bindings_generator/pyopencv_generated_include.h:53:10: fatal error: 'opencv2/gapi/core.hpp' file not found
#include "opencv2/gapi/core.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [modules/python3/CMakeFiles/opencv_python3.dir/__/src2/cv2.cpp.o] Error 1
make[1]: *** [modules/python3/CMakeFiles/opencv_python3.dir/all] Error 2
make: *** [all] Error 2
```
