### ISSUE TITLE
opencv_android app stops after being opened in galaxy s6

### ISSUE THREAD

**Issue by sarmadm** [opencv/opencv#7258]
Hi

after loading opencv application from android studio to my S6 when I press the start activity , the app stops and displyes these errors in logcat , what is the possible solutuino for this issue ?

Regards
- OpenCV => 2.4.10
- Operating System / Platform => ubuntu
- Compiler => android studio
##### Steps to reproduce

/ AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: org.blatnik.eyemon, PID: 28080
                                                                    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                                        at android.view.ViewRootImpl.setView(ViewRootImpl.java:853)
                                                                        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:337)
                                                                        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
                                                                        at android.app.Dialog.show(Dialog.java:350)
                                                                        at org.opencv.android.BaseLoaderCallback.onManagerConnected(BaseLoaderCallback.java:79)
                                                                        at org.blatnik.eyemon.MainService$1.onManagerConnected(MainService.java:113)
                                                                        at org.opencv.android.AsyncServiceHelper$3.onServiceConnected(AsyncServiceHelper.java:319)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1335)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1352)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-08 14:59:05.981 28080-28080/org.blatnik.eyemon I/Process: Sending signal. PID: 28080 SIG: 9

**Comment by alalek** [comment]
Android version?

**Comment by sarmadm** [comment]
S6 android ver:  6.0.1

Build tool for the app : 24.0.1

**Comment by alalek** [comment]
Did you try to run [OpenCV Android samples](https://github.com/opencv/opencv/tree/2.4.10/samples/android)?
What value is passed to `BaseLoaderCallback` constructor? It should be current `Activity` (not `getApplicationContext()` or [similar](http://stackoverflow.com/questions/19024940/android-error-unable-to-add-window-token-null-is-not-for-an-application))

BTW, [BaseLoaderCallback.java:79](https://github.com/opencv/opencv/blob/2.4.10/modules/java/generator/src/java/android%2BBaseLoaderCallback.java#L79) is a failure report line.

**Comment by sarmadm** [comment]
Hi , Yes the samples are working without problems .

this the link to baseloadercallback : [http://paste.ofcode.org/39zFE9a9RbNN6uU7tBQaT6E](url)

**Comment by leeman12345** [comment]
I had the same issue on Galaxy 7 edge.

**Comment by leeman12345** [comment]
Open CV does not seem to work on later Android versions
