### ISSUE TITLE
stitching_detailed.cpp : throw_no_cuda

### ISSUE THREAD

**Issue by duchengyao** [opencv/opencv#7344]
##### System information (version)

- OpenCV => 3.1
- Operating System / Platform => ubuntu 16
- Compiler => make
##### Detailed description

> I have compiled OpenCV with cuda, and run `cuda::GpuMat` `cuda::cvtColor` well.

I complie `stitching_detailed.cpp` , and run with `1.jpg 2.jpg  --try_cuda yes --features orb`. When running at `LINE 709: seam_finder->find(images_warped_f, corners, masks_warped);` crashed:

```
OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file ***/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 101
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/duchengyao/project/
***/opencv/modules/core/include/opencv2/core/private.cuda.hpp:101: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda
```

It is really annoying me.

Regards,

**Comment by alalek** [comment]
> The called functionality is disabled for current build or platform

This is the reason. You need to rebuild used OpenCV and samples (`-DBUILD_EXAMPLES=ON`) with CUDA support for your device. `cv::getBuildInformation()` may help you to debug this problem.

**Comment by duchengyao** [comment]
@alalek 

I have already build with CUDA,but without NVCUVID. Is this problem related to NVCUVID?

```
  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  YES
    USE NVCUVID:                 NO
    NVIDIA GPU arch:             52
    NVIDIA PTX archs:
    Use fast math:               NO
```

But even though I check the `WITH_NVCUVID` in CMake GUI, there are still ` USE NVCUVID:  NO`.

-----

the full cmake configure log:

```
Detected version of GNU GCC: 54 (504)
FP16: Compiler support is not available
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.8", minimum required is "1.2.3") 
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
Checking for module 'gstreamer-base-1.0'
  No package 'gstreamer-base-1.0' found
Checking for module 'gstreamer-video-1.0'
  No package 'gstreamer-video-1.0' found
Checking for module 'gstreamer-app-1.0'
  No package 'gstreamer-app-1.0' found
Checking for module 'gstreamer-riff-1.0'
  No package 'gstreamer-riff-1.0' found
Checking for module 'gstreamer-pbutils-1.0'
  No package 'gstreamer-pbutils-1.0' found
Checking for module 'gstreamer-base-0.10'
  No package 'gstreamer-base-0.10' found
Checking for module 'gstreamer-video-0.10'
  No package 'gstreamer-video-0.10' found
Checking for module 'gstreamer-app-0.10'
  No package 'gstreamer-app-0.10' found
Checking for module 'gstreamer-riff-0.10'
  No package 'gstreamer-riff-0.10' found
Checking for module 'gstreamer-pbutils-0.10'
  No package 'gstreamer-pbutils-0.10' found
Looking for linux/videodev.h
Looking for linux/videodev.h - not found
Looking for linux/videodev2.h
Looking for linux/videodev2.h - found
Looking for sys/videoio.h
Looking for sys/videoio.h - not found
Checking for module 'libavresample'
  No package 'libavresample' found
Looking for libavformat/avformat.h
Looking for libavformat/avformat.h - found
Looking for ffmpeg/avformat.h
Looking for ffmpeg/avformat.h - not found
Checking for module 'libgphoto2'
  No package 'libgphoto2' found
A library with BLAS API found.
A library with LAPACK API found.
found IPP (ICV version): 9.0.1 [9.0.1]
at: /home/duchengyao/project/opencv/3rdparty/ippicv/unpack/ippicv_lnx
CUDA detected: 8.0
CUDA NVCC target flags: -gencode;arch=compute_50,code=sm_50;-D_FORCE_INLINES
Could NOT find JNI (missing:  JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
Caffe:   NO
Protobuf:   YES
Glog:   YES
HDF5:   YES
Module opencv_sfm disabled because the following dependencies are not found: Eigen
HDF5:   YES
The protocol buffer compiler and libprotobuf were found
Tesseract:   NO

General configuration for OpenCV 3.1.0-dev =====================================
  Version control:               3.1.0-1374-g7f14a27

  Platform:
    Timestamp:                   2016-09-27T03:35:10Z
    Host:                        Linux 4.4.0-36-generic x86_64
    CMake:                       3.5.1
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /usr/bin/c++  (ver 5.4.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -Wno-comment -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):
    Linker flags (Debug):
    Precompiled headers:         NO
    Extra dependencies:          /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libjasper.so /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so gtk-3 gdk-3 pangocairo-1.0 pango-1.0 atk-1.0 cairo-gobject cairo gdk_pixbuf-2.0 gio-2.0 gobject-2.0 gthread-2.0 glib-2.0 dc1394 avcodec-ffmpeg avformat-ffmpeg avutil-ffmpeg swscale-ffmpeg /usr/lib/x86_64-linux-gnu/libbz2.so /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so /usr/lib/x86_64-linux-gnu/libpthread.so /usr/lib/x86_64-linux-gnu/libsz.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libdl.so /usr/lib/x86_64-linux-gnu/libm.so dl m pthread rt cudart nppc nppi npps cublas cufft -L/usr/local/cuda/lib64
    3rdparty dependencies:       libwebp libtiff

  OpenCV modules:
    To be built:                 cudev core cudaarithm flann hdf imgproc ml reg surface_matching video cudabgsegm cudafilters cudaimgproc cudawarping dnn fuzzy imgcodecs photo shape videoio cudacodec highgui objdetect plot ts xobjdetect xphoto bgsegm bioinspired dpm face features2d line_descriptor saliency text calib3d ccalib cudafeatures2d cudalegacy cudaobjdetect cudaoptflow cudastereo datasets rgbd stereo structured_light superres tracking videostab xfeatures2d ximgproc aruco optflow stitching python2
    Disabled:                    world contrib_world
    Disabled by dependency:      -
    Unavailable:                 java python3 viz cvv matlab sfm

  GUI: 
    QT:                          NO
    GTK+ 3.x:                    YES (ver 3.18.9)
    GThread :                    YES (ver 2.48.1)
    GtkGlExt:                    NO
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.8)
    JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver )
    WEBP:                        build (ver 0.3.1)
    PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.2.54)
    TIFF:                        build (ver 42 - 4.0.2)
    JPEG 2000:                   /usr/lib/x86_64-linux-gnu/libjasper.so (ver 1.900.1)
    OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2.2.0)
    GDAL:                        NO
    GDCM:                        NO

  Video I/O:
    DC1394 1.x:                  NO
    DC1394 2.x:                  YES (ver 2.2.4)
    FFMPEG:                      YES
      codec:                     YES (ver 56.60.100)
      format:                    YES (ver 56.40.101)
      util:                      YES (ver 54.31.100)
      swscale:                   YES (ver 3.1.101)
      resample:                  NO
      gentoo-style:              YES
    GStreamer:                   NO
    OpenNI:                      NO
    OpenNI PrimeSensor Modules:  NO
    OpenNI2:                     NO
    PvAPI:                       NO
    GigEVisionSDK:               NO
    UniCap:                      NO
    UniCap ucil:                 NO
    V4L/V4L2:                    NO/YES
    XIMEA:                       NO
    Xine:                        NO
    gPhoto2:                     NO

  Parallel framework:            pthreads

  Other third-party libraries:
    Use IPP:                     9.0.1 [9.0.1]
         at:                     /home/duchengyao/project/opencv/3rdparty/ippicv/unpack/ippicv_lnx
    Use IPP Async:               NO
    Use VA:                      NO
    Use Intel VA-API/OpenCL:     NO
    Use Lapack:                  NO
    Use Eigen:                   NO
    Use Cuda:                    YES (ver 8.0)
    Use OpenCL:                  YES
    Use OpenVX:                  NO
    Use custom HAL:              NO

  NVIDIA CUDA
    Use CUFFT:                   YES
    Use CUBLAS:                  YES
    USE NVCUVID:                 NO
    NVIDIA GPU arch:             50
    NVIDIA PTX archs:
    Use fast math:               NO

  OpenCL:                        <Dynamic loading of OpenCL library>
    Include path:                /home/duchengyao/project/opencv/3rdparty/include/opencl/1.2
    Use AMDFFT:                  NO
    Use AMDBLAS:                 NO

  Python 2:
    Interpreter:                 /usr/bin/python2.7 (ver 2.7.12)
    Libraries:                   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.12)
    numpy:                       /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)
    packages path:               lib/python2.7/dist-packages

  Python 3:
    Interpreter:                 /usr/bin/python3 (ver 3.5.2)

  Python (for build):            /usr/bin/python2.7

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Matlab:                        NO

  Tests and samples:
    Tests:                       YES
    Performance tests:           YES
    C/C++ Examples:              YES

  Install path:                  /usr/local/opencv3

  cvconfig.h is in:              /home/duchengyao/project/opencv/release_cuda_cmakeGUI
-----------------------------------------------------------------

Configuring done
```

**Comment by duchengyao** [comment]
Follow this instruction [cuda-videoreader-error](http://answers.opencv.org/question/70250/cuda-videoreader-error/). I think the problem is NVCUVENC.

But I can't build with NVCUVENC. However I configure CMake GUI ,  still `NVCUVENC = NO`

**Comment by alalek** [comment]
Please build debug version (something like this: `cmake -DCMAKE_BUILD_TYPE=Debug . && make`) and add gdb stacktrace (run in terminal `gdb --args <path_to_example> <example_args>`, `r`, wait for exception stop, `bt` command)

**Comment by duchengyao** [comment]
Thanks. I followed your instruction and get these message.

```
$ gdb --args stitching_detailed_Debug d08.mp4.jpg d09.mp4.jpg --try_cuda yes --features orb
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from stitching_detailed_Debug...done.
(gdb) r
Starting program: /home/duchengyao/cuda-workspace/mosaic/datas/hands_jpg/rotated/stitching_detailed_Debug d08.mp4.jpg d09.mp4.jpg --try_cuda yes --features orb
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Finding features...
[New Thread 0x7fffd1826700 (LWP 32256)]
[New Thread 0x7fffc8fff700 (LWP 32257)]
[New Thread 0x7fffc3fff700 (LWP 32258)]
[New Thread 0x7fffc37fe700 (LWP 32259)]
[New Thread 0x7fffc2ffd700 (LWP 32260)]
[New Thread 0x7fffc27fc700 (LWP 32261)]
[New Thread 0x7fffc1ffb700 (LWP 32262)]
[New Thread 0x7fffc17fa700 (LWP 32263)]
[New Thread 0x7fffc0ff9700 (LWP 32264)]
[New Thread 0x7fffbbfff700 (LWP 32265)]
[New Thread 0x7fffbb7fe700 (LWP 32266)]
[New Thread 0x7fffbaffd700 (LWP 32267)]
[New Thread 0x7fffba7fc700 (LWP 32268)]
[New Thread 0x7fffb9ffb700 (LWP 32269)]
[New Thread 0x7fffb97fa700 (LWP 32270)]
Features in image #1: 1390
Features in image #2: 1391
Finding features, time: 0.190212 sec
[New Thread 0x7fffb8ff9700 (LWP 32271)]
[New Thread 0x7fff897ff700 (LWP 32272)]
Pairwise matchingPairwise matching, time: 0.633485 sec
Initial intrinsics #1:
[1813.010091655975, 0, 335.5;
 0, 1813.010091655975, 447;
 0, 0, 1]
Initial intrinsics #2:
[1813.010091655975, 0, 335.5;
 0, 1813.010091655975, 447;
 0, 0, 1]
Camera #1:
[730.8503876842117, 0, 335.5;
 0, 730.8503876842117, 447;
 0, 0, 1]
Camera #2:
[739.1898399865494, 0, 335.5;
 0, 739.1898399865494, 447;
 0, 0, 1]
Warping images (auxiliary)... 
Warping images, time: 0.00388901 sec
OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/duchengyao/project/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 101
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/duchengyao/project/opencv/modules/core/include/opencv2/core/private.cuda.hpp:101: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda


Thread 1 "stitching_detai" received signal SIGABRT, Aborted.
0x00007ffff366c418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff366c418 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff366e01a in __GI_abort () at abort.c:89
#2  0x00007ffff3fae84d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff3fac6b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff3fac701 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff3fac919 in __cxa_throw ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff710bbf2 in cv::error(cv::Exception const&) ()
   from /usr/local/opencv3/lib/libopencv_core.so.3.1
#7  0x00007ffff710bd83 in cv::error(int, cv::String const&, char const*, char const*, int) () from /usr/local/opencv3/lib/libopencv_core.so.3.1
#8  0x00007ffff21c7c50 in cv::cuda::graphcut(cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::GpuMat&, cv::cuda::Stream&) ()
   from /usr/local/opencv3/lib/libopencv_cudalegacy.so.3.1
#9  0x00007ffff4e90abc in cv::detail::GraphCutSeamFinderGpu::findInPair(unsigned long, unsigned long, cv::Rect_<int>) ()
   from /usr/local/opencv3/lib/libopencv_stitching.so.3.1
#10 0x00007ffff4e88892 in cv::detail::PairwiseSeamFinder::run() ()
   from /usr/local/opencv3/lib/libopencv_stitching.so.3.1
---Type <return> to continue, or q <return> to quit---
#11 0x00007ffff4e917f3 in cv::detail::PairwiseSeamFinder::find(std::vector<cv::UMat, std::allocator<cv::UMat> > const&, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > > const&, std::vector<cv::UMat, std::allocator<cv::UMat> >&) () from /usr/local/opencv3/lib/libopencv_stitching.so.3.1
#12 0x00007ffff4e9cdf4 in cv::detail::GraphCutSeamFinderGpu::find(std::vector<cv::UMat, std::allocator<cv::UMat> > const&, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > > const&, std::vector<cv::UMat, std::allocator<cv::UMat> >&) () from /usr/local/opencv3/lib/libopencv_stitching.so.3.1
#13 0x00000000004162ef in main (argc=7, argv=0x7fffffffdbf8)
    at ../src/stitching_detailed.cpp:712
(gdb) quit
A debugging session is active.

	Inferior 1 [process 32252] will be killed.

Quit anyway? (y or n) 
Please answer y or n.
A debugging session is active.

	Inferior 1 [process 32252] will be killed.

Quit anyway? (y or n) y
```

 Is this helpful?

Regards,

**Comment by alalek** [comment]
Yes, it is useful.

Looks like `cv::cuda::graphcut` implementation is [explicitly disabled](https://github.com/opencv/opencv/blob/73e1d64ae07be010a2c64e6906d0e938846c6bef/modules/cudalegacy/src/graphcuts.cpp#L46-L49) for CUDA 8.0: #6510

Possible workaround is to use CUDA 7.5.

**Comment by duchengyao** [comment]
So, does the `cv::cuda::graphcut` not supported for CUDA 8.0?

Will `stitching_detailed.cpp` support CUDA 8.0 later?

BTW, Why I cannot build OpenCV with NVCUVID?

Thanks!

**Comment by mujinkeji** [comment]
Is this problem solved?

Thanks！

**Comment by IsaTGP** [comment]
Hi, 
I have the same problem, I am compiling stitching_detailed.cpp , and run with boat1.jpg boat2.jpg --try_cuda yes. 
When running: seam_finder->find(images_warped_f, corners, masks_warped); crashed:

OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/indra/Opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 111
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/indra/Opencv/opencv/modules/core/include/opencv2/core/private.cuda.hpp:111: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda

I understand that the problem is because cv::cuda::graphcut is deprecated and not supported from CUDA 8, I am using CUDA 9 and Opencv 3.3.

There must be another module that we can use instead of graphcut, I need to know how can I perform stitching using CUDA 9 however all examples that I found are using the sentence that causes this error: seam_finder->find(images_warped_f, corners, masks_warped);

Please I need help!!

Thank you!

**Comment by vintserg** [comment]
Hi,
I have the same problem.
 When i try use  
```     cv::cudacodec::createVideoWriter(outputFilename, frame_original.size(), fps) terminate called after throwing an instance of 'cv::Exception'```
    trow this exception
```what():  /home/sergey/opencv/modules/core/include/opencv2/core/private.cuda.hpp:111: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda```
My options:
```
	opencv  3.3.1 with  extension pack
	cuda 8.0 or 9.0 - result the same.
	Ubuntu 16.04 x86_64
	--   NVIDIA CUDA
	--     Use CUFFT:                   YES
	--     Use CUBLAS:                  YES
	--     USE NVCUVID:                 YES
	--     NVIDIA GPU arch:             61
	--     NVIDIA PTX archs:
	--     Use fast math:               YES
```
```cmake -D CMAKE_BUILD_TYPE=RELEASE  -D CMAKE_INSTALL_PREFIX=/usr/local     -D INSTALL_PYTHON_EXAMPLES=OFF     -D INSTALL_C_EXAMPLES=ON     -D OPENCV_EXTRA_MODULES_PATH=/home/sergey/opencv_contrib/modules     -D PYTHON_EXECUTABLE=~/.virtualenvs/tf35/bin/python     -D BUILD_EXAMPLES=ON  -D CUDA_ARCH_BIN=6.1 -D WITH_CUDA=ON -D WITH_NVCUVID=ON -D ENABLE_FAST_MATH=1 -D CUDA_FAST_MATH=1 -DBUILD_opencv_text=OFF .. ```


By comments on the Internet, the integration code with cuda is likely to be fully working only in version 7.5
Is it planned to support cuda latest versions in opencv?

Thank you!

**Comment by amin-git** [comment]
same Problem :

- OpenCV 3.4.1 (output of cv2.__version__ = pre 4.0.0)

- with Cuda 9.0

>   NVIDIA CUDA:                   YES (ver 9.0, CUFFT CUBLAS)
>     NVIDIA GPU arch:             50

when run stitch simple sample get this error 
 `[ INFO:0] Initialize OpenCL runtime...
[ INFO:0] Successfully initialized OpenCL cache directory: /home/amin/.cache/opencv/4.0.0-pre/opencl_cache/
[ INFO:0] Preparing OpenCL cache configuration for context: NVIDIA_Corporation--GeForce_840M--384_111
OpenCV(4.0.0-pre) Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file /home/amin/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 113
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.0-pre) /home/amin/opencv/modules/core/include/opencv2/core/private.cuda.hpp:113: error: (-213:The function/feature is not implemented) The called functionality is disabled for current build or platform in function 'throw_no_cuda'`

run alphaComp sample with cuda without problem 
:(

**Comment by xamix** [comment]
Hi,

Same problem for me using OpenCv 3.3 and Cuda 8.

Since it's a pretty old issue, has someone found a solution to use Cuda >= 8.0 for stiching?

Regards.

**Comment by Tudou880306** [comment]
Hi,
 i have the same problem
 Opencv4.0.0 
 cuda 9.2

Regards.

**Comment by Amin-Tgz** [comment]
maybe one solution for stitching is using [stitching_detailed.cpp](https://github.com/opencv/opencv/blob/master/samples/cpp/stitching_detailed.cpp) instead of Stitcher class and then **comment out parts given below** or utilize another method for seam_find_type that use CPU instead of GPU like _dp_colorgrad_
this helps you to use GPU and Cuda library for other modules of stitching pipeline
furthermore, if you compile OpenCV with OpenCL this code can help you get faster speed.

 if use **seam_find_type == "gc_color"**
```
#ifdef HAVE_OPENCV_CUDALEGACY
				if (try_cuda && cuda::getCudaEnabledDeviceCount() > 0)
	seam_finder=makePtr<detail::GraphCutSeamFinderGpu(GraphCutSeamFinderBase::COST_COLOR);
			       else
		#endif
```
or
if use **seam_find_type == "gc_colorgrad"**
```
#ifdef HAVE_OPENCV_CUDALEGACY
				if (try_cuda && cuda::getCudaEnabledDeviceCount() > 0)
seam_finder=makePtr<detail::GraphCutSeamFinderGpu(GraphCutSeamFinderBase::COST_COLOR_GRAD);
				else
		#endif
```

**Comment by Stocastico** [comment]
I have the same problem with OpenCV 4.3.0 and Cuda 10.0.
Had to use disable GPU for the seam finder.

**Comment by makolele12** [comment]
Same problem here with OpenCV 4.3.0 and CUDA 10.2 
Does someone knows a current alternative to this? Using the CPU alternative is not feasible for me as it takes too long to compute.

**Comment by HZNUJeffreyRen** [comment]
I have the same problem with Opencv 4.5.0 and cuda 11.2， Windows10
Has anyone solved it yet？

**Comment by HZNUJeffreyRen** [comment]
I have the same problem with Opencv 4.5.0 and cuda 11.2， Windows10
Has anyone solved it yet？

**Comment by HZNUJeffreyRen** [comment]
I have the same problem with Opencv 4.5.0 and cuda 11.2， Windows10
Has anyone solved it yet？

**Comment by KristinSun** [comment]
> 帮助您获得更快的速

解决了吗

**Comment by KristinSun** [comment]
> 我的Opencv 4.5.0和cuda 11.2也有同样的问题，Windows10 有人解决了吗？

解决了吗

**Comment by KristinSun** [comment]
> ##### System information (version)
> * OpenCV => 3.1
> * Operating System / Platform => ubuntu 16
> * Compiler => make
> 
> ##### Detailed description
> > I have compiled OpenCV with cuda, and run `cuda::GpuMat` `cuda::cvtColor` well.
> 
> I complie `stitching_detailed.cpp` , and run with `1.jpg 2.jpg --try_cuda yes --features orb`. When running at `LINE 709: seam_finder->find(images_warped_f, corners, masks_warped);` crashed:
> 
> ```
> OpenCV Error: The function/feature is not implemented (The called functionality is disabled for current build or platform) in throw_no_cuda, file ***/opencv/modules/core/include/opencv2/core/private.cuda.hpp, line 101
> terminate called after throwing an instance of 'cv::Exception'
>   what():  /home/duchengyao/project/
> ***/opencv/modules/core/include/opencv2/core/private.cuda.hpp:101: error: (-213) The called functionality is disabled for current build or platform in function throw_no_cuda
> ```
> 
> It is really annoying me.
> 
> Regards,

解决了吗这个问题

**Comment by duanluan** [comment]
总结一下，4.x 之后就没有 GPU 加速了，我模仿 3.x 修改了相关源码，添加了 try_cuda 参数，并使用了相关 GPU 方法，然后编译调用，发现和使用 CPU 差不多，甚至有些配置下会更慢一点点。可能是我改源码的时候，有那么一两个 GPU 方法在 CUDA 8.x 之后就用不了了的原因，那一两个方法我保持了原样。
现在测试下来，两张 720p 的相机画面做融合，每一帧最快 0.3s，想做实时融合还是有点卡，应该还是只能针对相机画面场景自己实现了。

In summary, there is no GPU acceleration after version 4.x. I mimicked the changes made in version 3.x by modifying the relevant source code, adding a "try_cuda" parameter, and utilizing GPU methods. However, upon compilation and testing, I found that it performs similarly to using the CPU, and in some configurations, it's even slightly slower. This might be because a couple of GPU methods I modified are no longer compatible with CUDA 8.x and later. I left those one or two methods as they were.
Now, after testing, when combining the images from two 720p cameras, the fastest frame processing time is 0.3 seconds. Real-time fusion is still somewhat laggy, so it seems that implementing a custom solution for camera image scenarios is the way to go.
