### ISSUE TITLE
Regression issue with Calib3dTest.findFundamentalMat

### ISSUE THREAD

**Issue by abratchik** [opencv/opencv#7510]
##### System information (version)

- OpenCV => 3.1 upstream/master (505c19bc20b971288f321f6092f9dfc479001e2b)
- Operating System / Platform => Mac OSX 10.11.5 (15F34)
- Compiler => Xcode Version 8.0 (8A218a)

##### Detailed description

Java unit test is failing the test case  **Calib3dTest.testFindFundamentalMatListOfPointListOfPoint** with the following message:

```
Max difference between expected and actiual Mats is 0.6962482904638616, that bigger than 0.001

junit.framework.AssertionFailedError: Max difference between expected and actiual Mats is 0.6962482904638616, that bigger than 0.0001
at org.opencv.test.OpenCVTestCase.compareMats(Unknown Source)
at org.opencv..test.OpenCVTestCase.assertMatEqual(Unknown Source)
at org.opencv.test.calib3d.Calib3dTest.testFindFundamentalMatListOfPointListOfPPoint(Unknown Source)
at org.opencv.test.OpenCVTestCase.runTest(Unknown Source)
```
The test is running the following code:
```
    public void testFindFundamentalMatListOfPointListOfPoint() {
        int minFundamentalMatPoints = 8;

        MatOfPoint2f pts = new MatOfPoint2f();
        pts.alloc(minFundamentalMatPoints);

        for (int i = 0; i < minFundamentalMatPoints; i++) {
            double x = Math.random() * 100 - 50;
            double y = Math.random() * 100 - 50;
            pts.put(i, 0, x, y); //add(new Point(x, y));
        }

        Mat fm = Calib3d.findFundamentalMat(pts, pts);

        truth = new Mat(3, 3, CvType.CV_64F);
        truth.put(0, 0, 0, -0.577, 0.288, 0.577, 0, 0.288, -0.288, -0.288, 0);
        assertMatEqual(truth, fm, EPS);
    }
```

##### Steps to reproduce

Compile OpenCV with java enabled and run the autotests from the build folder using the following command:
```
python ../modules/ts/misc/run.py . -t java
```
Results of autotests can be seen on this page: opencv/build/modules/java/pure_test/.build/testResults/junit-noframes.html

**Comment by alalek** [comment]
Test uses random input data and fixed golden result. This design is wrong, so I believe it should be disabled to enable autotests and fixed later.

**Comment by abratchik** [comment]
Ok, I'll disable it in the next fix for autotests. Thank you!
