### ISSUE TITLE
An error occurred while calling the setVocabulary()

### ISSUE THREAD

**Issue by xiaochus** [opencv/opencv#7922]
**System information (version)**

- OpenCV => 3.1.0
- Operating System / Platform => Windows 10 64 Bit
- Compiler => python 3.5

**Detailed description**

The var that i pass to the function is a numpy.array var and I am sure it is a correct type.An error occurred while calling the setVocabulary() as follow.

```
OpenCV Error: Assertion failed (The data should normally be NULL!) in NumpyAllocator::allocate, file ..\..\..\modules\python\src2\cv2.cpp, line 163
Traceback (most recent call last):
  File "E:/Documents/Documents/python/Traffic/main.py", line 15, in <module>
    c = sd.detect(img)
  File "E:\Documents\Documents\python\Traffic\src\SlideDetect.py", line 93, in detect
    svm, extractor = self.detector.create_detector()
  File "E:\Documents\Documents\python\Traffic\src\Detector.py", line 126, in create_detector
    extract_bow.setVocabulary(vocabulary)
cv2.error: ..\..\..\modules\python\src2\cv2.cpp:163: error: (-215) The data should normally be NULL! in function NumpyAllocator::allocate
```

**part of code**

```
    @staticmethod
    def _get_flann_matcher():
        flann_params = dict(algorithm=1, trees=5)
        flann = cv2.FlannBasedMatcher(flann_params, {})
        return flann

    @staticmethod
    def _get_extract_detect():
        sift = cv2.xfeatures2d.SIFT_create()
        return sift

    @staticmethod
    def _extract_sift(image, extractor, detector):
        im = cv2.imread(image, 0)
        features = extractor.compute(im, detector.detect(im))[1]
        return features

    def create_detector(self):
        detect = self._get_extract_detect()
        extract = self._get_extract_detect()
        matcher = self._get_flann_matcher()
        car_list, neg_list = self._get_train_data_address()

        bow_kmeans_trainer = cv2.BOWKMeansTrainer(12)
        extract_bow = cv2.BOWImgDescriptorExtractor(extract, matcher)

        for i in range(self.sample):
            features = self._extract_sift(car_list[i], extract, detect)
            bow_kmeans_trainer.add(features)

        vocabulary = bow_kmeans_trainer.cluster()
        extract_bow.setVocabulary(vocabulary)
```

**Comment by Vinit-Koshti** [comment]
openCV 3.1.0 do not contain the SIFT algo module, but it was part of opencv 2.4 so plz take a look its an openCV ERROR because of SIFT feature absence in openCV 3.1.0
