### ISSUE TITLE
opencv does not build on Mac OS X 10.12.2 with Xcode 8.2

### ISSUE THREAD

**Issue by sushangjin** [opencv/opencv#7990]
my cmake version is 3.1.0
execute the shell:
python ../platforms/ios/build_framework.py ios

then output:
-- Setting up iPhoneOS toolchain for IOS_ARCH='armv7'
-- iPhoneOS toolchain loaded
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
-- Configuring incomplete, errors occurred!
See also "/Users/moon/dev/cpp-lib/opencv-master/build/ios/build/armv7-iPhoneOS/CMakeFiles/CMakeOutput.log".
See also "/Users/moon/dev/cpp-lib/opencv-master/build/ios/build/armv7-iPhoneOS/CMakeFiles/CMakeError.log".
-master/build/ios/build/armv7-iPhoneOS
CMake Error at CMakeLists.txt:98 (project):
  No CMAKE_CXX_COMPILER could be found.

CMake Error at CMakeLists.txt:98 (project):
  No CMAKE_C_COMPILER could be found.

============================================================
ERROR: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/moon/dev/cpp-lib/opencv-master/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/moon/dev/cpp-lib/opencv-master', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1
============================================================
Traceback (most recent call last):
  File "../platforms/ios/build_framework.py", line 88, in build
    self._build(outdir)
  File "../platforms/ios/build_framework.py", line 82, in _build
    self.buildOne(t[0], t[1], mainBD, cmake_flags)
  File "../platforms/ios/build_framework.py", line 138, in buildOne
    execute(cmakecmd, cwd = builddir)
  File "../platforms/ios/build_framework.py", line 34, in execute
    retcode = check_call(cmd, cwd = cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '-GXcode', '-DAPPLE_FRAMEWORK=ON', '-DCMAKE_INSTALL_PREFIX=install', '-DCMAKE_BUILD_TYPE=Release', '-DIOS_ARCH=armv7', '-DCMAKE_TOOLCHAIN_FILE=/Users/moon/dev/cpp-lib/opencv-master/platforms/ios/cmake/Toolchains/Toolchain-iPhoneOS_Xcode.cmake', '-DENABLE_NEON=ON', '/Users/moon/dev/cpp-lib/opencv-master', '-DCMAKE_C_FLAGS=-fembed-bitcode', '-DCMAKE_CXX_FLAGS=-fembed-bitcode']' returned non-zero exit status 1

**Comment by sushangjin** [comment]
[CMakeFiles.zip](https://github.com/opencv/opencv/files/695493/CMakeFiles.zip)

**Comment by alalek** [comment]
> Code signing is required for product type 'Unit Test Bundle' in SDK 'iOS 10.2'

Problem is here. Need to support this somehow.

**Comment by multidisplayad** [comment]
I have the same issue.
Any helps?

**Comment by areslui** [comment]
I got this error, any help? it occurred when I was compiling the opencv_contrib modules.

CMake Error at CMakeLists.txt:7 (ocv_glob_modules):
  Unknown CMake command "ocv_glob_modules".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

thanks!!

**Comment by misuqian** [comment]
same issue.and I use HomeBrew to update cmake to 3.8.2 and work fine.wish this can help you

**Comment by yongduek** [comment]
Had the same problem.
So, I ran this first.
`$ sudo xcode-select  --switch /Applications/Xcode.app/Contents/Developer`
Then
`$ make -G Xcode ..`
worked fine.
