### ISSUE TITLE
CascadeClassifier exception on JDK8, macOS Sierra

### ISSUE THREAD

**Issue by virl** [opencv/opencv#8094]
##### System information (version)
- OpenCV => 3.1
- Operating System / Platform => macOS Sierra 10.12.3 (16D32)
- Compiler => JDK8, bindings from https://github.com/openpnp/opencv/issues/17

##### Detailed description

"Unrecognized or unsupported array type in function cvGetMat":
```
Caused by: CvException [org.opencv.core.CvException: cv::Exception: /Users/jason/Projects/openpnp/opencv/opencv/opencv-3.2.0/modules/core/src/array.cpp:2501: error: (-206) Unrecognized or unsupported array type in function cvGetMat
]
	at org.opencv.objdetect.CascadeClassifier.detectMultiScale_1(Native Method)
	at org.opencv.objdetect.CascadeClassifier.detectMultiScale(CascadeClassifier.java:159)
```
Source (Kotlin):
```
val faceGrayMat = gray.submat(faceRect)
var drects = MatOfRect()
eyeLeftCascade.detectMultiScale(faceGrayMat, drects)
```
What is strange is that that code has been called thousands of times for the images of the same format, but the exception occurs only from time to time.

**Comment by virl** [comment]
I'm running CascadeClassifier instances on threadpool (one instance for each task/thread, so perfectly thread safe on my part) and after some time (thousands of successful launches on same basically image of same format) I'm getting a crash:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000015599cd3c, pid=21420, tid=0x0000000000013303
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libopencv_java320.dylib+0x1f4d3c]  _ZNK2cv11_InputArray4sizeEi+0x6fc
```
```
Stack: [0x000070000977d000,0x000070000987d000],  sp=0x000070000987c300,  free space=1020k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libopencv_java320.dylib+0x1f4d3c]  _ZNK2cv11_InputArray4sizeEi+0x6fc
C  [libopencv_java320.dylib+0x77d16a]  _ZN2cv17CascadeClassifier16detectMultiScaleERKNS_11_InputArrayERNSt3__16vectorINS_5Rect_IiEENS4_9allocatorIS7_EEEEdiiNS_5Size_IiEESD_+0xea
C  [libopencv_java320.dylib+0x52272]  Java_org_opencv_objdetect_CascadeClassifier_detectMultiScale_11+0x82
J 2045  org.opencv.objdetect.CascadeClassifier.detectMultiScale_1(JJJ)V (0 bytes) @ 0x000000010d31877d [0x000000010d3186c0+0xbd]
...
ava frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2045  org.opencv.objdetect.CascadeClassifier.detectMultiScale_1(JJJ)V (0 bytes) @ 0x000000010d318707 [0x000000010d3186c0+0x47]
```

**Comment by alalek** [comment]
Without complete stable reproducer (source code & image data) it is not possible to resolve this problem.
