### ISSUE TITLE
Unable to create DescriptorMatcher in openCV 3.2 - Android

### ISSUE THREAD

**Issue by daniel-barkan** [opencv/opencv#8135]
I'm running the following code in android:
```
FeatureDetector detector = FeatureDetector.create(FeatureDetector.ORB);
DescriptorExtractor descriptor = DescriptorExtractor.create(DescriptorExtractor.ORB);
DescriptorMatcher matcher = DescriptorMatcher.create(DescriptorMatcher.BRUTEFORCE_HAMMING);
```
and getting the following exception:
```
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.features2d.DescriptorMatcher.create_1(int) (tried Java_org_opencv_features2d_DescriptorMatcher_create_11 and Java_org_opencv_features2d_DescriptorMatcher_create_11__I)
                                                                                     at org.opencv.features2d.DescriptorMatcher.create_1(Native Method)
                                                                                     at org.opencv.features2d.DescriptorMatcher.create(DescriptorMatcher.java:76)
```
The same code works on android with version 3.1 and 2.4 and works on Windows with version 3.2.
it looks like the method Java_org_opencv_features2d_DescriptorMatcher_create_11 was not added to version 3.2 on Android. I saw that there is a new implementation of DescriptorMatcher creation on 3.2 that gets a String instead of int. It looks that it is also missing from this version on Android.

I'm testing it with a Nexus 5 device.

**Comment by alalek** [comment]
It is strange, because symbol is here:
```
/opt/android/android-ndk-r12b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc-nm -D ./3.2.0/OpenCV-android-sdk/sdk/native/libs/armeabi-v7a/libopencv_java3.so | grep Java_org_opencv_features2d_DescriptorMatcher_create_11 
000d71fc T Java_org_opencv_features2d_DescriptorMatcher_create_11
```

Please check `adb logcat` output on application startup for loaded OpenCV version.

**Comment by daniel-barkan** [comment]
in both 3.1 and 3.2 the in the logcat, the first attempt to load opencv fails but eventually I get "OpenCV libs init was ok!"

This is the logcat of 3.2 

```
02-06 14:10:50.589 25183-25183/org.opencv.samples.tutorial3 W/System: ClassLoader referenced unknown path: /data/app/org.opencv.samples.tutorial3-1/lib/arm
02-06 14:10:50.594 25183-25183/org.opencv.samples.tutorial3 I/OCVSample::Activity: Instantiated new class org.opencv.samples.tutorial3.Tutorial3Activity
02-06 14:10:50.609 25183-25183/org.opencv.samples.tutorial3 I/OCVSample::Activity: called onCreate
02-06 14:10:50.669 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: Attr count: 4
02-06 14:10:50.670 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: Trying to get library list
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: Library list: ""
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: First attempt to load libs
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: Trying to init OpenCV libs
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: Trying to load library opencv_java3
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: Cannot load library "opencv_java3"
02-06 14:10:50.675 25183-25183/org.opencv.samples.tutorial3 W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.opencv.samples.tutorial3-1/base.apk"],nativeLibraryDirectories=[/data/app/org.opencv.samples.tutorial3-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libopencv_java3.so"
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:367)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at java.lang.System.loadLibrary(System.java:1076)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:91)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at org.opencv.samples.tutorial3.Tutorial3Activity.onResume(Tutorial3Activity.java:107)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.Activity.performResume(Activity.java:6327)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.os.Looper.loop(Looper.java:148)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
02-06 14:10:50.683 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-06 14:10:50.684 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-06 14:10:50.684 25183-25183/org.opencv.samples.tutorial3 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-06 14:10:50.684 25183-25183/org.opencv.samples.tutorial3 D/OpenCV/StaticHelper: First attempt to load libs fails
02-06 14:10:50.684 25183-25183/org.opencv.samples.tutorial3 D/OCVSample::Activity: Internal OpenCV library not found. Using OpenCV Manager for initialization
02-06 14:10:50.741 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call surfaceChanged event
02-06 14:10:50.741 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call checkCurrentState
02-06 14:10:50.779 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Service connection created
02-06 14:10:50.780 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Trying to get library path
02-06 14:10:50.781 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Trying to get library list
02-06 14:10:50.782 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Library list: "libopencv_java3.so"
02-06 14:10:50.782 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: First attempt to load libs
02-06 14:10:50.782 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Trying to init OpenCV libs
02-06 14:10:50.782 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Trying to load libs by dependency list
02-06 14:10:50.782 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Trying to load library /data/app/org.opencv.engine-1/lib/arm/libopencv_java3.so
02-06 14:10:50.817 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: OpenCV libs init was ok!
02-06 14:10:50.817 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: First attempt to load libs is OK
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   videoio: Removing WinRT API headers by default
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper: General configuration for OpenCV 3.0.0 =====================================
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Version control:               3.0.0-6-gc1f114b-dirty
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Platform:
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Host:                        Linux 3.13.0-53-generic x86_64
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Target:                      Linux 1 armv7-a
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     CMake:                       2.8.12.2
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     CMake generator:             Ninja
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     CMake build tool:            /usr/bin/ninja
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Configuration:               Release
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   C/C++:
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Built as dynamic libs?:      NO
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C++ Compiler:                /usr/bin/ccache /home/maksim/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++ (ver 4.8)
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C++ flags (Release):         -fexceptions -frtti -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C++ flags (Debug):           -fexceptions -frtti -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C Compiler:                  /usr/bin/ccache /home/maksim/android-ndk-r10e/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C flags (Release):           -fexceptions -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -mthumb -fomit-frame-pointer -fno-strict-aliasing -O3 -DNDEBUG  -DNDEBUG
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C flags (Debug):             -fexceptions -fpic -Wno-psabi --sysroot=/home/maksim/android-ndk-r10e/platforms/android-8/arch-arm -funwind-tables -finline-limit=64 -fsigned-char -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fdata-sections -ffunction-sections -Wa,--noexecstack    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wno-narrowing -fdiagnostics-show-option -fomit-frame-pointer -mfpu=neon -fvisibility=hidden -marm -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -O0 -DDEBUG -D_DEBUG
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Linker flags (Release):      -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Linker flags (Debug):        -Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now 
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Precompiled headers:         NO
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Extra dependencies:          z dl m log
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     3rdparty dependencies:       libjpeg libwebp libpng libtiff libjasper IlmImf tbb
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   OpenCV modules:
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     To be built:                 hal core flann imgproc ml photo video imgcodecs shape videoio highgui objdetect superres ts features2d calib3d java stitching videostab
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Disabled:                    world
02-06 14:10:50.820 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Disabled by dependency:      -
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 viz
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Android: 
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Android ABI:                 armeabi-v7a with NEON
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     STL type:                    gnustl_static
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Native API level:            android-8
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     SDK target:                  android-11
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Android NDK:                 /home/maksim/android-ndk-r10e (toolchain: arm-linux-androideabi-4.8)
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     android tool:                /home/maksim/android-sdk-linux/tools/android (Android SDK Tools, revision 24.3.)
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Google Play manager:         NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Android examples:            YES
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   GUI: 
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     GTK+:                        NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     GThread :                    NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     GtkGlExt:                    NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     OpenGL support:              NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     VTK support:                 NO
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Media I/O: 
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     ZLib:                        z (ver 1.2.3)
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     JPEG:                        build (ver 90)
02-06 14:10:50.822 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     WEBP:                        build (ver 0.3.1)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     PNG:                         build (ver 1.5.12)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     TIFF:                        build (ver 42 - 4.0.2)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     JPEG 2000:                   build (ver 1.900.1)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     OpenEXR:                     build (ver 1.7.1)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     GDAL:                        NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Video I/O:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Other third-party libraries:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use IPP:                     NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use Eigen:                   NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use TBB:                     YES (ver 4.1 interface 6102)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use OpenMP:                  NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use GCD                      NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use Concurrency              NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use C=:                      NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use pthreads for parallel for:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:                                  NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use Cuda:                    NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Use OpenCL:                  NO
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Python 2:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Interpreter:                 /usr/bin/python2.7 (ver 2.7.6)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Python 3:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Interpreter:                 /usr/bin/python3.4 (ver 3.4)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Python (for build):            /usr/bin/python2.7
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Java:
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     ant:                         /usr/bin/ant (ver 1.9.3)
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Java wrappers:               YES
02-06 14:10:50.823 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Java tests:                  YES
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Matlab:
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     mex:                         NO
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Documentation:
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Doxygen:                     NO
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     PlantUML:                    NO
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Tests and samples:
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Tests:                       YES
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     Performance tests:           NO
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:     C/C++ Examples:              NO
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   Install path:                  /home/maksim/workspace/android-pack/builds/o4a/install
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper:   cvconfig.h is in:              /home/maksim/workspace/android-pack/builds/o4a
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 I/OpenCVManager/Helper: -----------------------------------------------------------------
02-06 14:10:50.824 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Init finished with status 0
02-06 14:10:50.825 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Unbind from service
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 D/OpenCVManager/Helper: Calling using callback
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 I/OCVSample::Activity: OpenCV loaded successfully
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call checkCurrentState
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call processExitState: 0
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call processEnterState: 1
02-06 14:10:50.827 25183-25183/org.opencv.samples.tutorial3 D/CameraBridge: call onEnterStartedState
02-06 14:10:50.828 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: Connecting to camera
02-06 14:10:50.828 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: Initialize java camera
02-06 14:10:50.828 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: Trying to open camera with old open()
02-06 14:10:50.983 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: getSupportedPreviewSizes()
02-06 14:10:50.983 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: Set preview size to 1280x960
02-06 14:10:50.988 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: startPreview
02-06 14:10:50.995 25183-25183/org.opencv.samples.tutorial3 D/JavaCameraView: Starting processing thread
02-06 14:11:14.067 25183-25183/org.opencv.samples.tutorial3 I/OCVSample::Activity: onTouch event
02-06 14:11:14.084 25183-25183/org.opencv.samples.tutorial3 I/Sample::Tutorial3View: Taking picture
02-06 14:11:14.970 25183-25183/org.opencv.samples.tutorial3 I/Sample::Tutorial3View: Saving a bitmap to file
02-06 14:11:15.292 25183-25183/org.opencv.samples.tutorial3 E/art: No implementation found for long org.opencv.features2d.DescriptorMatcher.create_1(int) (tried Java_org_opencv_features2d_DescriptorMatcher_create_11 and Java_org_opencv_features2d_DescriptorMatcher_create_11__I)
02-06 14:11:15.295 25183-25183/org.opencv.samples.tutorial3 D/AndroidRuntime: Shutting down VM
02-06 14:11:15.319 25183-25183/org.opencv.samples.tutorial3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: org.opencv.samples.tutorial3, PID: 25183
                                                                              java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.features2d.DescriptorMatcher.create_1(int) (tried Java_org_opencv_features2d_DescriptorMatcher_create_11 and Java_org_opencv_features2d_DescriptorMatcher_create_11__I)
                                                                                  at org.opencv.features2d.DescriptorMatcher.create_1(Native Method)
                                                                                  at org.opencv.features2d.DescriptorMatcher.create(DescriptorMatcher.java:76) 
```

**Comment by alalek** [comment]
> This is the logcat of 3.2

No, OpenCV 3.0.0 is loaded from outdated OpenCV Manager:

> Trying to load library /data/app/org.opencv.engine-1/lib/arm/libopencv_java3.so
> ...
> General configuration for OpenCV 3.0.0 =====================================
>   Version control:               3.0.0-6-gc1f114b-dirty

Try to disable/uninstall OpenCV Manager application and link correct OpenCV libraries directly to your application (copy "libs" folder from OpenCV Android SDK manually or via some gradle task).
Also You can update OpenCV Manager application (update is not available on Google Play now, try to use APK from OpenCV Android SDK 3.2.0).
But direct linking with OpenCV libraries is preferable now.

**Comment by daniel-barkan** [comment]
OK. Is working. Thanks!
I suggest to update the version on google play or to change the documentation of version 3.2

**Comment by YasserMojahed** [comment]
I have the same issue.
How could u solve it? did u update Opencv Manager or did u link the libs directly?
thx for help

**Comment by huanghuoxian** [comment]
I have the same issue.

**Comment by kishanverma26** [comment]
### Why this show don't know
`  Caused by: java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.features2d.DescriptorMatcher.create_1(int) (tried Java_org_opencv_features2d_DescriptorMatcher_create_11 and Java_org_opencv_features2d_DescriptorMatcher_create_11__I)
        at org.opencv.features2d.DescriptorMatcher.create_1(Native Method)
        at org.opencv.features2d.DescriptorMatcher.create(DescriptorMatcher.java:79)
   `

**Comment by alalek** [comment]
@kishanverma26 Looks like you have mess with versions of Java files and used native library (see comments above how to detect that).
Remove all OpenCV installations (especially "OpenCV Manager") and try again.

Build / usage questions should go to Users OpenCV Q/A forum: http://answers.opencv.org
