### ISSUE TITLE
Can not use cv2.findContours

### ISSUE THREAD

**Issue by xfsm1912** [opencv/opencv#8254]
##### System information (version)

- OpenCV => :2.4.11:
- Operating System / Platform => :Mac 10.12.3:
- Compiler => : not sure:

##### Detailed description

I cannot use command 'cv2.findContours'

Here is my code:
```import cv2
import numpy as np

a = cv2.imread("/Users/Jianhua/Documents/viz/6010_0_0.png");
b = cv2.imread("/Users/Jianhua/Documents/6010_0_1.png");

image, contours, hierarchy = cv2.findContours(a, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_TC89_KCOS) 
```

but output is:
```Traceback (most recent call last):
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/Jianhua/anaconda/lib/python2.7/inspect.py", line 1048, in getinnerframes
    framelist.append((tb.tb_frame,) + getframeinfo(tb, context))
  File "/Users/Jianhua/anaconda/lib/python2.7/inspect.py", line 1008, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/Jianhua/anaconda/lib/python2.7/inspect.py", line 453, in getsourcefile
    if hasattr(getmodule(object, filename), '__loader__'):
  File "/Users/Jianhua/anaconda/lib/python2.7/inspect.py", line 482, in getmodule
    file = getabsfile(object, _filename)
  File "/Users/Jianhua/anaconda/lib/python2.7/inspect.py", line 466, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/Users/Jianhua/anaconda/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_code(self, code_obj, result)
   2896             if result is not None:
   2897                 result.error_in_exec = sys.exc_info()[1]
-> 2898             self.showtraceback()
   2899         else:
   2900             outflag = 0

/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in showtraceback(self, exc_tuple, filename, tb_offset, exception_only)
   1822                     except Exception:
   1823                         stb = self.InteractiveTB.structured_traceback(etype,
-> 1824                                             value, tb, tb_offset=tb_offset)
   1825 
   1826                     self._showtraceback(etype, value, stb)

/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1404         self.tb = tb
   1405         return FormattedTB.structured_traceback(
-> 1406             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1407 
   1408 

/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1312             # Verbose modes need a full traceback
   1313             return VerboseTB.structured_traceback(
-> 1314                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1315             )
   1316         else:

/Users/Jianhua/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.pyc in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1196                 structured_traceback_parts += formatted_exception
   1197         else:
-> 1198             structured_traceback_parts += formatted_exception[0]
   1199 
   1200         return structured_traceback_parts

IndexError: string index out of range
```

can somebody tell me what is going on?

Thank you

**Comment by alalek** [comment]
```
   File "/Users/Jianhua/anaconda/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
```

Sorry, but this cannot be fixed in OpenCV.
You should investigate problems with your machine configuration yourself.
