### ISSUE TITLE
CUDA tests result to segfualt with toolkit 8.0 and opencv version 3.2.0

### ISSUE THREAD

**Issue by el-cangrejo** [opencv/opencv#8568]
##### System information (version)

- OpenCV => :grey_question: 3.2.0
- Operating System / Platform => :grey_question: Ubuntu Desktop 16.04.2 64bit
- Compiler => :grey_question:  gcc 5.4.0

##### Detailed description

I compiled Opencv with the following configuration:
##### Cmake information
```
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_PNG=OFF \
    -DBUILD_TIFF=OFF \
    -DBUILD_TBB=OFF \
    -DBUILD_JPEG=OFF \
    -DBUILD_JASPER=OFF \
    -DBUILD_ZLIB=OFF \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_opencv_java=OFF \
    -DBUILD_opencv_python2=ON \
    -DBUILD_opencv_python3=OFF \
    -DWITH_OPENCL=OFF \
    -DWITH_OPENMP=OFF \
    -DWITH_FFMPEG=ON \
    -DWITH_GSTREAMER=OFF \
    -DWITH_GSTREAMER_0_10=OFF \
    -DWITH_CUDA=ON \
    -DWITH_GTK=ON \
    -DWITH_VTK=OFF \
    -DWITH_TBB=ON \
    -DWITH_1394=OFF \
    -DWITH_OPENEXR=OFF \
    -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 \
    -DCUDA_ARCH_BIN='3.0 3.5 5.0 6.0 6.1 6.2' \
    -DCUDA_ARCH_PTX="" \
    -DINSTALL_C_EXAMPLES=ON \
    -DINSTALL_TESTS=OFF \
    -DBUILD_opencv_cudalegacy=OFF \
```
And the CUDA specific configuration is:
```
cmake -L .. | grep -i cuda
-- CUDA detected: 8.0
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_62,code=sm_62;-D_FORCE_INLINES
--     Extra dependencies:          /usr/lib/x86_64-linux-gnu/libwebp.so /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/x86_64-linux-gnu/libtiff.so /usr/lib/x86_64-linux-gnu/libjasper.so /usr/lib/x86_64-linux-gnu/libjpeg.so gtk-x11-2.0 gdk-x11-2.0 pangocairo-1.0 atk-1.0 cairo gdk_pixbuf-2.0 gio-2.0 pangoft2-1.0 pango-1.0 gobject-2.0 glib-2.0 fontconfig freetype gthread-2.0 avcodec-ffmpeg avformat-ffmpeg avutil-ffmpeg swscale-ffmpeg dl m pthread rt tbb /usr/lib/libopenblas.so cudart nppc nppi npps cufft -L/usr/local/cuda-8.0/lib64
--     To be built:                 cudev core cudaarithm flann imgproc ml video cudabgsegm cudafilters cudaimgproc cudawarping imgcodecs photo shape videoio cudacodec cudaoptflow highgui objdetect superres ts cudaobjdetect features2d calib3d cudafeatures2d cudastereo stitching videostab python2
--     Disabled:                    cudalegacy python3 world
--     Use Cuda:                    YES (ver 8.0)
--   NVIDIA CUDA
BUILD_CUDA_STUBS:BOOL=OFF
BUILD_opencv_cudaarithm:BOOL=ON
BUILD_opencv_cudabgsegm:BOOL=ON
BUILD_opencv_cudacodec:BOOL=ON
BUILD_opencv_cudafeatures2d:BOOL=ON
BUILD_opencv_cudafilters:BOOL=ON
BUILD_opencv_cudaimgproc:BOOL=ON
BUILD_opencv_cudalegacy:BOOL=OFF
BUILD_opencv_cudaobjdetect:BOOL=ON
BUILD_opencv_cudaoptflow:BOOL=ON
BUILD_opencv_cudastereo:BOOL=ON
BUILD_opencv_cudawarping:BOOL=ON
CUDA_ARCH_BIN:STRING=3.0 3.5 5.0 6.0 6.1 6.2
CUDA_ARCH_PTX:STRING=
CUDA_FAST_MATH:BOOL=OFF
CUDA_GENERATION:STRING=
CUDA_HOST_COMPILER:FILEPATH=/usr/bin/gcc-5
CUDA_SEPARABLE_COMPILATION:BOOL=OFF
WITH_CUDA:BOOL=ON
```

I have installed the CUDA 8.0 toolkit. I have the following gpu according to deviceQuery:
##### Device information
```
Device 0: "GeForce GTX 1050"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 1998 MBytes (2094792704 bytes)
  ( 5) Multiprocessors, (128) CUDA Cores/MP:     640 CUDA Cores
  GPU Max Clock rate:                            1455 MHz (1.46 GHz)
  Memory Clock rate:                             3504 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 1048576 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = GeForce GTX 1050
Result = PASS
```
##### Problem 

When I try to run the cuda tests produced in ./build/bin like opencv_test_cudev I get the following output:

##### Seg fault
```
 ./opencv_test_cudev 
CTEST_FULL_OUTPUT
OpenCV version: 3.2.0
OpenCV VCS version: unknown
Build type: release
Parallel framework: tbb
CPU features: mmx sse sse2 sse3
[==========] Running 190 tests from 77 test cases.
[----------] Global test environment set-up.
[----------] 1 test from Sobel
[ RUN      ] Sobel.Accuracy
*** Error in `./opencv_test_cudev': malloc(): memory corruption: 0x00000000038431d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f202c29a7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8181e)[0x7f202c2a481e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f202c2a65d4]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x1ad176)[0x7f201a71d176]
/usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x1187c7)[0x7f201a6887c7]
##### ...
7f2025400000-7f2025411000 r-xp 00000000 08:15 2761014                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f2025411000-7f2025610000 ---p 00011000 08:15 2761014                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f2025610000-7f2025611000 r--p 00010000 08:15 2761014                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f2025611000-7f2025612000 rw-p 00011000 08:15 2761014                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f2025612000-7f2025614000 r-xp 00000000 08:15 2761010                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f2025614000-7f2025813000 ---p 00002000 08:15 2761010                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f2025813000-7f2025814000 r--p 00001000 08:15 2761010                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f2025814000-7f2025815000 rw-p 00002000 08:15 2761010                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f2025815000-7f2025817000 r-xp 00000000 08:15 2761006                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f2025817000-7f2025a16000 ---p 00002000 08:15 2761006                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f2025a16000-7f2025a17000 r--p 00001000 08:15 2761006                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f2025a17000-7f2025a18000 rw-p 00002000 08:15 2761006                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f2025a18000-7f2025a21000 r-xp 00000000 08:15 2761008                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f2025a21000-7f2025c20000 ---p 00009000 08:15 2761008                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f2025c20000-7f2025c21000 r--p 00008000 08:15 2761008                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2[1]    25906 segmentation fault (core dumped)  ./opencv_test_cudev
```
Even if I try to compile a simple program using a CUDA module although it compiles normally I get the same kind of segmentation fault. 

Runnning gdb on the opencv_test_cudev program and backtracing the segfault I get the following output:

##### gdb output
```
#0  0x00007ffff3d0b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff3d0d02a in __GI_abort () at abort.c:89
#2  0x00007ffff3d4d7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff3e662e0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff3d55e0a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, 
    str=0x7ffff3e66438 "free(): invalid next size (normal)", action=3) at malloc.c:5004
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3865
#5  0x00007ffff3d5998c in __GI___libc_free (mem=<optimized out>) at malloc.c:2966
#6  0x00007ffff3d5154b in __GI__IO_setb (f=f@entry=0x223a0f0, b=b@entry=0x0, eb=eb@entry=0x0, a=a@entry=0) at genops.c:382
#7  0x00007ffff3d4f8ee in _IO_new_file_close_it (fp=fp@entry=0x223a0f0) at fileops.c:185
#8  0x00007ffff3d433ef in _IO_new_fclose (fp=0x223a0f0) at iofclose.c:58
#9  0x00007fffe21e1a22 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#10 0x00007fffe21e2626 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#11 0x00007fffe228d3ed in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#12 0x00007fffe2297f65 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#13 0x00007fffe229838a in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#14 0x00007fffe20e260b in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#15 0x00007fffe20e2f52 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#16 0x00007fffe220b4ad in cuMemAlloc_v2 () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#17 0x00007ffff7b9efa3 in ?? () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
#18 0x00007ffff7b7deae in ?? () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
#19 0x00007ffff7baf4ac in cudaMalloc () from /usr/local/cuda-8.0/lib64/libcudart.so.8.0
#20 0x00007ffff4acf5ee in cv::cuda::Stream::Impl::Impl(CUstream_st*) ()
   from /home/user/Documents/Libraries/opencv-3.2.0/build/lib/libopencv_core.so.3.2
#21 0x00007ffff4ad13a7 in cv::cuda::Stream::Null() () from /home/user/Documents/Libraries/opencv-3.2.0/build/lib/libopencv_core.so.3.2
#22 0x00000000004264c6 in Sobel_Accuracy_Test::Body() ()
#23 0x00000000004250a9 in Sobel_Accuracy_Test::TestBody() ()
#24 0x00000000005c17c3 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#25 0x00000000005c1a27 in testing::Test::Run() [clone .part.477] ()
#26 0x00000000005c1ef5 in testing::TestInfo::Run() [clone .part.478] ()
#27 0x00000000005c212d in testing::TestCase::Run() [clone .part.479] ()
#28 0x00000000005c4361 in testing::internal::UnitTestImpl::RunAllTests() [clone .part.481] [clone .constprop.563] ()
#29 0x00000000005c478e in testing::UnitTest::Run() ()
#30 0x0000000000417b38 in main ()
```
Any kind of suggestion on how to resolve this issue would be welcomed. Thank you in advance.

**Comment by linknum23** [comment]
Have you tried using a lower version of gcc, like 4.9?

**Comment by fishpepper** [comment]
I am having trouble with opencv 3.2. + cuda8 as well.

The opencv cuda examples crash:
```
bin/opencv_test_cudev   
CTEST_FULL_OUTPUT
OpenCV version: 3.2.0-dev
OpenCV VCS version: 3.2.0-828-g51e16bb
Build type: release
Parallel framework: tbb
CPU features: mmx sse sse2 sse3
[==========] Running 190 tests from 77 test cases.
[----------] Global test environment set-up.
[----------] 1 test from BitNotTest/0, where TypeParam = unsigned char
[ RUN      ] BitNotTest/0.GpuMat
*** Error in `bin/opencv_test_cudev': malloc(): memory corruption: 0x00000000028c9580 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f71e9e577e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8213e)[0x7f71e9e6213e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f71e9e64184]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_Znwm+0x18)[0x7f71ea756e78]
/vol/test/lib/libopencv_core.so.3.2(+0x29a22c)[0x7f71eace522c]
/vol/test/lib/libopencv_core.so.3.2(_ZN2cv4cuda6Stream4ImplC2EP11CUstream_st+0x3b)[0x7f71eace56db]
/vol/test/lib/libopencv_core.so.3.2(+0x29b763)[0x7f71eace6763]
/vol/test/lib/libopencv_core.so.3.2(+0x29bf68)[0x7f71eace6f68]
bin/opencv_test_cudev[0x42fa47]
bin/opencv_test_cudev[0x545813]
bin/opencv_test_cudev[0x5459f5]
bin/opencv_test_cudev[0x545e05]
bin/opencv_test_cudev[0x546175]
bin/opencv_test_cudev(_ZN7testing8internal12UnitTestImpl11RunAllTestsEv+0x3ad)[0x54664d]
bin/opencv_test_cudev[0x546973]
bin/opencv_test_cudev(_ZN7testing8UnitTest3RunEv+0x35)[0x546b05]
bin/opencv_test_cudev[0x417d98]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f71e9e00830]
bin/opencv_test_cudev(_start+0x29)[0x424d59]
======= Memory map: ========
00400000-00778000 r-xp 00000000 08:01 8133566    ...
```

Running the cuda examples from the nvidia toolkit run fine:
```
/tmp/NVIDIA_CUDA-8.0_Samples/0_Simple/simpleStreams$ ./simpleStreams 
[ simpleStreams ]

Device synchronization method set to = 0 (Automatic Blocking)
Setting reps to 100 to demonstrate steady state

> GPU Device 0: "GeForce GTX 660 Ti" with compute capability 3.0

Device: <GeForce GTX 660 Ti> canMapHostMemory: Yes
> CUDA Capable: SM 3.0 hardware
> 7 Multiprocessor(s) x 192 (Cores/Multiprocessor) = 1344 (Cores)
> scale_factor = 1.0000
> array_size   = 16777216

> Using CPU/GPU Device Synchronization method (cudaDeviceScheduleAuto)
> mmap() allocating 64.00 Mbytes (generic page-aligned system memory)
> cudaHostRegister() registering 64.00 Mbytes of generic allocated system memory

Starting Test
memcopy:        5.34
kernel:         2.92
non-streamed:   8.02
4 streams:      5.11
-------------------------------

```
My own opencv code corrupts memory and crashes by a single line like 
```cv::cuda::Stream stream;```

I will test gcc 4.9 tomorrow.

**Comment by fishpepper** [comment]
GCC 4.9 did not help. I trashed my prefix based installation of cuda8 and removed the cuda 7.5 that ubuntu had installed. After installing libcuda1-375, nvidia-375-dev and reinstalling cuda8 and opencv into a clean prefix I got rid of the memory corruption. So it was probably a mix of different cuda libs/headers causing this error.

**Comment by mshabunin** [comment]
Looks like these problems have been caused by CUDA versions mixing.
