### ISSUE TITLE
Opencv2.4.13 Mat push_back coredump

### ISSUE THREAD

**Issue by kakashidan** [opencv/opencv#8720]
##### System information (version)

- OpenCV => 2.4.13
- Operating System / Platform => ubuntu16.04
- Compiler => g++ 5.4.0
- Main Memory=> 64G
##### Detailed description

I extracted sift descriptors of many images and pushed these descriptors into one single mat. But the program coredumped when the loop was not end.

##### Steps to reproduce
```.cpp
    #include <opencv2/opencv.hpp>
    #include <opencv2/nonfree/features2d.hpp>

    using namespace std;
    using namespace cv;

    void extractSiftFeatures(Mat& stImage, vector<KeyPoint>& vKeypoints, Mat& stDescriptors)
    {
        Ptr<SIFT> psift = new SIFT(400);
        (*psift)(stImage, noArray(), vKeypoints, stDescriptors);
    }

    int main()
    {
        Mat test;
        test.reserve(100000000);
        Mat stImage = imread("demo.jpg"); //please replace with your image path
        vector<KeyPoint> vKeypoints;
        Mat stDescriptors;
        extractSiftFeatures(stImage, vKeypoints, stDescriptors);
        for (int i = 0 ; i< 100000000; ++i)
        {
            test.push_back(stDescriptors); //core here
        }
        return 0;
    }
```

```coredump info
        Core was generated by `./test'.
        Program terminated with signal SIGSEGV, Segmentation fault.
        #0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:267
        267	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
        [Current thread is 1 (Thread 0x7f9024dd2740 (LWP 823))]
        (gdb) bt
        #0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:267 
        #1  0x00007f902489c57a in cv::Mat::copyTo(cv::_OutputArray const&) const () from /usr/lib/libopencv_core.so.2.4
        #2  0x00007f90248ecd99 in cv::Mat::reserve(unsigned long) () from /usr/lib/libopencv_core.so.2.4
        #3  0x00007f90248ed971 in cv::Mat::push_back(cv::Mat const&) () from /usr/lib/libopencv_core.so.2.4
        #4  0x000000000040150d in main ()
```

**Comment by kakashidan** [comment]
the code above is just a demo which can reproduce the same problem.

**Comment by alalek** [comment]
Related: #7160
