### ISSUE TITLE
HOG human detection causes process exit without any error stack message after changing padding from (16,16) to (8,8)

### ISSUE THREAD

**Issue by AlexLuya** [opencv/opencv#8793]
My configuration:

Ubuntu 16.04 64bit desktop
Opencv 3.2.0-dev compiled by 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
Python 2.7.12
and I am trying to detect human from a video,and detection will exit when comes to this frame,

Problem frame
![problemframe](https://cloud.githubusercontent.com/assets/303353/26446573/372f6bea-410a-11e7-9ad8-d23386e2420f.png)

detection code is:

```
import cv2

image = cv2.imread('problemFrame.png')

cv2.imshow('Problem frame', image)
cv2.waitKey(30)

hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())
founds, weights = hog.detectMultiScale(image, winStride=(4, 4),
                                                          padding=(8, 8), scale=1.05,
                                                          useMeanshiftGrouping=True)   

print founds, weights
```
and if changing padding from (8,8) to (16,16),detection works,and I have checked api doc:

padding – Mock parameter to keep the CPU interface compatibility. It must be (0,0).
but don't know what it mean,why must be (0,0),and this link gives more detailed description:

http://www.pyimagesearch.com/2015/11/16/hog-detectmultiscale-parameters-explained/
padding (optional)

The padding  parameter is a tuple which indicates the number of pixels in both the x and y direction in which the sliding window ROI is “padded” prior to HOG feature extraction.

As suggested by Dalal and Triggs in their 2005 CVPR paper, Histogram of Oriented Gradients for Human Detection, adding a bit of padding surrounding the image ROI prior to HOG feature extraction and classification can actually increase the accuracy of your detector.

Typical values for padding include (8, 8), (16, 16), (24, 24), and (32, 32).
and still can't figure out why,would you please help solve this problem?Thanks in advance.

**Comment by asmorkalov** [comment]
https://github.com/opencv/opencv/pull/29583 does not fix the problem.
ASAN report with mentioned fix:
```
$ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-fno-omit-frame-pointer -fsanitize=address" -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" -DCMAKE_LINKER_FLAGS_DEBUG="-fno-omit-frame-pointer -fsanitize=address" -DENABLE_PROFILING=ON ../opencv
$ export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.8
$ python3 ./repro.py 
[ INFO:0@0.032] global registry.impl.hpp:118 UIBackendRegistry UI: Enabled backends(2, sorted by priority): GTK(1000); GTK3(990) + BUILTIN(GTK3)
[ INFO:0@0.033] global backend.cpp:90 createUIBackend UI: using backend: GTK (priority=1000)
[ INFO:0@0.033] global window_gtk.cpp:2344 createWindow OpenCV/UI: Creating GTK window: Problem frame (1)
[ INFO:0@0.049] global window_gtk.cpp:577 CvWindow OpenCV/UI: creating GTK window: Problem frame
[ INFO:0@0.176] global ocl.cpp:1185 haveOpenCL Initialize OpenCL runtime...
[ INFO:0@0.416] global ocl.cpp:1191 haveOpenCL OpenCL: found 0 platforms
=================================================================
==29008==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x52a0000717fc at pc 0x7aaec1c7455b bp 0x7ffca4757c00 sp 0x7ffca4757bf0
READ of size 1 at 0x52a0000717fc thread T0
    #0 0x7aaec1c7455a in cv::HOGCache::getBlock(cv::Point_<int>, float*) /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:921
    #1 0x7aaec1c80702 in cv::HOGDescriptor::detect(cv::_InputArray const&, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > >&, std::vector<double, std::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > > const&) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1592
    #2 0x7aaec1c90aed in cv::HOGInvoker::operator()(cv::Range const&) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1681
    #3 0x7aaeb7218b9f in parallel_for_impl /mnt/Projects/Projects/opencv/modules/core/src/parallel.cpp:626
    #4 0x7aaeb7218250 in cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) /mnt/Projects/Projects/opencv/modules/core/src/parallel.cpp:524
    #5 0x7aaec1c85c03 in cv::HOGDescriptor::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, std::vector<double, std::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, double, double, bool) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1934
    #6 0x7aaec2ad2938 in pyopencv_cv_HOGDescriptor_detectMultiScale /mnt/Projects/Projects/opencv-build/modules/python_bindings_generator/pyopencv_generated_types_content.h:15505
    #7 0x551347  (/usr/bin/python3.12+0x551347) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #8 0x549934 in PyObject_Vectorcall (/usr/bin/python3.12+0x549934) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #9 0x5d6f08 in _PyEval_EvalFrameDefault (/usr/bin/python3.12+0x5d6f08) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #10 0x5d544a in PyEval_EvalCode (/usr/bin/python3.12+0x5d544a) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #11 0x6085a1  (/usr/bin/python3.12+0x6085a1) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #12 0x6b5032  (/usr/bin/python3.12+0x6b5032) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #13 0x6b4d99 in _PyRun_SimpleFileObject (/usr/bin/python3.12+0x6b4d99) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #14 0x6b4bce in _PyRun_AnyFileObject (/usr/bin/python3.12+0x6b4bce) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #15 0x6bcc34 in Py_RunMain (/usr/bin/python3.12+0x6bcc34) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #16 0x6bc71c in Py_BytesMain (/usr/bin/python3.12+0x6bc71c) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #17 0x7aaefde2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #18 0x7aaefde2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #19 0x657bc4 in _start (/usr/bin/python3.12+0x657bc4) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)

0x52a0000717fc is located 178 bytes after 21834-byte region [0x52a00006c200,0x52a00007174a)
allocated by thread T0 here:
    #0 0x7aaefe2fd9c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7aaeb69fbc6f in cv::fastMalloc(unsigned long) /mnt/Projects/Projects/opencv/modules/core/src/alloc.cpp:160
    #2 0x7aaeb6f04e4c in cv::StdMatAllocator::allocate(int, int const*, int, void*, unsigned long*, cv::AccessFlag, cv::UMatUsageFlags) const /mnt/Projects/Projects/opencv/modules/core/src/matrix.cpp:147
    #3 0x7aaeb6ef44b4 in cv::Mat::create(int, int const*, int) /mnt/Projects/Projects/opencv/modules/core/src/matrix.cpp:699
    #4 0x7aaeb6ef1706 in cv::Mat::create(int, int, int) /mnt/Projects/Projects/opencv/modules/core/src/matrix.cpp:533
    #5 0x7aaeb6ef189c in cv::Mat::create(cv::Size_<int>, int) /mnt/Projects/Projects/opencv/modules/core/src/matrix.cpp:538
    #6 0x7aaeb7028b2c in cv::_OutputArray::create(cv::Size_<int>, int, int, bool, cv::_OutputArray::DepthMask) const /mnt/Projects/Projects/opencv/modules/core/src/matrix_wrap.cpp:1322
    #7 0x7aaec1c6722e in cv::HOGDescriptor::computeGradient(cv::_InputArray const&, cv::_InputOutputArray const&, cv::_InputOutputArray const&, cv::Size_<int>, cv::Size_<int>) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:249
    #8 0x7aaec1c6fb07 in cv::HOGCache::init(cv::HOGDescriptor const*, cv::Mat const&, cv::Size_<int> const&, cv::Size_<int> const&, bool, cv::Size_<int> const&) /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:664
    #9 0x7aaec1c6f507 in cv::HOGCache::HOGCache(cv::HOGDescriptor const*, cv::Mat const&, cv::Size_<int> const&, cv::Size_<int> const&, bool, cv::Size_<int> const&) /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:653
    #10 0x7aaec1c7fcd6 in cv::HOGDescriptor::detect(cv::_InputArray const&, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > >&, std::vector<double, std::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, std::vector<cv::Point_<int>, std::allocator<cv::Point_<int> > > const&) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1550
    #11 0x7aaec1c90aed in cv::HOGInvoker::operator()(cv::Range const&) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1681
    #12 0x7aaeb7218b9f in parallel_for_impl /mnt/Projects/Projects/opencv/modules/core/src/parallel.cpp:626
    #13 0x7aaeb7218250 in cv::parallel_for_(cv::Range const&, cv::ParallelLoopBody const&, double) /mnt/Projects/Projects/opencv/modules/core/src/parallel.cpp:524
    #14 0x7aaec1c85c03 in cv::HOGDescriptor::detectMultiScale(cv::_InputArray const&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, std::vector<double, std::allocator<double> >&, double, cv::Size_<int>, cv::Size_<int>, double, double, bool) const /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:1934
    #15 0x7aaec2ad2938 in pyopencv_cv_HOGDescriptor_detectMultiScale /mnt/Projects/Projects/opencv-build/modules/python_bindings_generator/pyopencv_generated_types_content.h:15505
    #16 0x551347  (/usr/bin/python3.12+0x551347) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #17 0x549934 in PyObject_Vectorcall (/usr/bin/python3.12+0x549934) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #18 0x5d6f08 in _PyEval_EvalFrameDefault (/usr/bin/python3.12+0x5d6f08) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #19 0x5d544a in PyEval_EvalCode (/usr/bin/python3.12+0x5d544a) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #20 0x6085a1  (/usr/bin/python3.12+0x6085a1) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #21 0x6b5032  (/usr/bin/python3.12+0x6b5032) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #22 0x6b4d99 in _PyRun_SimpleFileObject (/usr/bin/python3.12+0x6b4d99) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #23 0x6b4bce in _PyRun_AnyFileObject (/usr/bin/python3.12+0x6b4bce) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #24 0x6bcc34 in Py_RunMain (/usr/bin/python3.12+0x6bcc34) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #25 0x6bc71c in Py_BytesMain (/usr/bin/python3.12+0x6bc71c) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)
    #26 0x7aaefde2a1c9 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #27 0x7aaefde2a28a in __libc_start_main_impl ../csu/libc-start.c:360
    #28 0x657bc4 in _start (/usr/bin/python3.12+0x657bc4) (BuildId: 04657a7aa3577f9234b186f9a5918f06030389b6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /mnt/Projects/Projects/opencv/modules/objdetect/src/hog.cpp:921 in cv::HOGCache::getBlock(cv::Point_<int>, float*)
Shadow bytes around the buggy address:
  0x52a000071500: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x52a000071580: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x52a000071600: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x52a000071680: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x52a000071700: 00 00 00 00 00 00 00 00 00 02 fa fa fa fa fa fa
=>0x52a000071780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x52a000071800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52a000071880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52a000071900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52a000071980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x52a000071a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==29008==ABORTING
```

**Comment by uditjainstjis** [comment]
The remaining overflow has a different cause than #29583, so that fix could not have covered it.

`HOGCache::windowsInImage()` returns a negative number of window rows when the padded image is smaller than the detection window, and the callers keep `area()` in a `size_t`. For the attached frame (77x101, `padding=(8,8)` -> 93x117, window 64x128) it computes:

```
padded=93x117 win=64x128 stride=4x4 -> windowsInImage=8x-1 area=-8 -> nwindows=18446744073709551608
```

so the window loop in `detect()` walks far past the gradient buffers. `padding=(16,16)` works because 109x133 still holds the window, which is why it looked like a padding problem.

On current 4.x (so with #29583) your repro gives the report you posted:

```
ERROR: AddressSanitizer: heap-buffer-overflow READ of size 1
    #0 cv::HOGCache::getBlock(...) hog.cpp:921
    #1 cv::HOGDescriptor::detect(...) hog.cpp:1592
    #5 cv::HOGDescriptor::detectMultiScale(...) hog.cpp:1934
```

and with #29599 it is ASan clean and returns no detections. That PR just returns an empty `Size` when the window does not fit: `detectMultiScale()` already pushes a pyramid level before checking that the image is still larger than the window, so the last level is expected to produce nothing. `windowsInImage()` is called once per `detect()`/`compute()` call and not per window, so nothing is added to the hot path.
