### ISSUE TITLE
Opencv runnable jar Native Library error

### ISSUE THREAD

**Issue by mnh-aj123** [opencv/opencv#8807]
I was creating runnable jar after executing Opencv Program but when i tried to run the jar file using terminal and Hadoop
it gives error 

 ```
hduser@master:/home/mnh/Desktop$ hadoop jar carCount1.jar /usr/local/hadoop/input/cars.mp4 /usr/local/hadoop/carCount2
Error: No definition for the class found : org.bytedeco.javacpp.opencv_core
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(II)I
	at org.bytedeco.javacpp.opencv_core.CV_MAKETYPE(Native Method)
	at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:746)
	at anotherfyp.AnotherFYP.main(AnotherFYP.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

    ```

Kindly give me some proper way to create exactly working runnable Jar file .

**Comment by alalek** [comment]
> org.bytedeco.javacpp.opencv_core

You found wrong issue tracker, because this package is not developed here (so we can't help).
