### ISSUE TITLE
Non-ASCII symbols in source code files

### ISSUE THREAD

**Issue by alalek** [opencv/opencv#9065]
Example (marked by `--> <--`):
```
202:In the figure below, the Delaunay-->’<<--s triangulation is marked with black lines and the Voronoi
856://! Guil, N., Gonz-->á<--lez-Linares, J.M. and Zapata, E.L. (1999). Bidimensional shape detection using an invariant approach. Pattern Recognition 32 (6): 1025-1038.
958:    @param rect -->–<-- Rectangle that includes all of the 2D points that are to be added to the subdivision.
```

About 68 lines.

Some files has BOM header again (64 files).

**Comment by TonyLianLong** [comment]
I think the BOM appears in the WinRT files and WP files. Actually Microsoft created the BOM and editors on Windows needs those stuffs so it might be okay to have them on those files.

**Comment by mshabunin** [comment]
Looks like this issue can be closed.

**Comment by mshabunin** [comment]
Some issues still left in contrib:
```
[ 73%] Generating gen/tracking+TrackerMedianFlow.java, gen/tracking+Tracking.java, gen/tracking+Tracker.java, gen/tracking+TrackerTLD.java, gen/tracking+TrackerGOTURN.java, gen/tracking+TrackerKCF.java, gen/tracking+MultiTracker.java, gen/tracking+TrackerMIL.java, gen/tracking+TrackerBoosting.java, gen/tracking.cpp
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 478: ordinal not in range(128)
Call stack:
  File "/build/precommit_linux64/opencv/modules/java/generator/gen_java.py", line 1111, in <module>
    generator.gen(srcfiles, module, dstdir, common_headers)
  File "/build/precommit_linux64/opencv/modules/java/generator/gen_java.py", line 519, in gen
    logging.info("\n--- Incoming ---\n%s", pformat(decl, 4))
Message: '\n--- Incoming ---\n%s'
Arguments: ("[   'class cv.TrackerTLD',\n    ': cv::Tracker',\n    [],\n    [],\n    None,\n    '@brief TLD is a novel tracking framework that explicitly decomposes the '\n    'long-term tracking task into\\n'\n    'tracking, learning and detection.\\n'\n    '\\n'\n    'The tracker follows the object from frame to frame. The detector '\n    'localizes all appearances that\\n'\n    'have been observed so far and corrects the tracker if necessary. The '\n    'learning estimates detector\u2019s\\n'\n    'errors and updates it to avoid these errors in the future. The '\n    'implementation is based on @cite TLD .\\n'\n    '\\n'\n    'The Median Flow algorithm (see cv::TrackerMedianFlow) was chosen as a '\n    'tracking component in this\\n'\n    'implementation, following authors. Tracker is supposed to be able to '\n    'handle rapid motions, partial\\n'\n    'occlusions, object absence etc.']",)
```
