### ISSUE TITLE
problem using openface model with opencv dnn torch

### ISSUE THREAD

**Issue by TZVIh** [opencv/opencv#9490]
##### System information (version)

- OpenCV => 3.3.0
- Operating System / Platform => linux 16.04
- Compiler => :grey_question:

##### Detailed description

I work with net from OpenFace: nn4.small2.v1.t7.
when I using opencv dnn torch like this: "dnn::Net net = dnn::readNetFromTorch(modelFile);"
I got error: "OpenCV Error: The function/feature is not implemented (Unknown nn class "nn.SpatialConvolutionMM") in readTorchObject, file opencv-3.3.0/modules/dnn/src/torch/torch_importer.cpp, line 765"

there is no SpatialConvolutionMM layer.

**Comment by dkurt** [comment]
@TZVIh, we've prepared a PR that adds missed layers from OpenFace model: https://github.com/opencv/opencv/pull/9524. May I ask you to test it?

**Comment by TZVIh** [comment]
Sure!

**Comment by TZVIh** [comment]
@dkurt , where can I clone/pull the fix files?

**Comment by dkurt** [comment]
@TZVIh, navigate into OpenCV folder, add a remote repository:
```bash
git remote add dkurt https://github.com/dkurt/opencv.git
```
Fetch the branch:
```bash
git fetch dkurt dnn_torch_openface
```
Then checkout it and build.

**Comment by epratheeban** [comment]
Is it fixed in android version of 3.3? Unfortunately, opencv 3.4  android didn't work for me

**Comment by dkurt** [comment]
@epratheeban, OpenFace model is supported since PR was merged. Can you try it again? Make sure that OpenCV manager is updated on the device. If not please ask a question at http://answers.opencv.org because it's a kind of problem to track conversations at closed issues. Thank you!

**Comment by epratheeban** [comment]
@dkurt  The application is running perfectly with caffe model. When I try to import the torch model, i get 

`OpenCV Error: The function/feature is not implemented (Unknown nn class "nn.SpatialConvolutionMM`

I'm trying now with 3.3.1 version. Will update here if it works.

**Comment by epratheeban** [comment]
I  downloaded opencv 3.3.1 SDK.  I tried loading the Torch model. 
I get this error again :  

```
02-27 13:02:44.596 21625-21625/com.example.pratheeban.facerecognition E/cv::error(): OpenCV Error: The function/feature is not implemented (Unknown nn class "nn.SpatialConvolutionMM") in void cv::dnn::experimental_dnn_v1::TorchImporter::readTorchObject(int), file /build/master_pack-android/opencv/modules/dnn/src/torch/torch_importer.cpp, line 765
02-27 13:02:44.598 21625-21625/com.example.pratheeban.facerecognition E/org.opencv.dnn: dnn::readNetFromTorch_11() caught cv::Exception: /build/master_pack-android/opencv/modules/dnn/src/torch/torch_importer.cpp:765: error: (-213) Unknown nn class "nn.SpatialConvolutionMM" in function void cv::dnn::experimental_dnn_v1::TorchImporter::readTorchObject(int)
02-27 13:02:44.601 21625-21625/com.example.pratheeban.facerecognition E/SurfaceView: Exception configuring surface
                                                                                     CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/dnn/src/torch/torch_importer.cpp:765: error: (-213) Unknown nn class "nn.SpatialConvolutionMM" in function void cv::dnn::experimental_dnn_v1::TorchImporter::readTorchObject(int)
                                                                                     ]
                                                                                         at org.opencv.dnn.Dnn.readNetFromTorch_1(Native Method)
                                                                                         at org.opencv.dnn.Dnn.readNetFromTorch(Dnn.java:179)
                                                                                         at com.example.pratheeban.facerecognition.MainActivity.onCameraViewStarted(MainActivity.java:64)
                                                                                         at org.opencv.android.CameraBridgeViewBase.processEnterState(CameraBridgeViewBase.java:323)
                                                                                         at org.opencv.android.CameraBridgeViewBase.checkCurrentState(CameraBridgeViewBase.java:313)
                                                                                         at org.opencv.android.CameraBridgeViewBase.surfaceChanged(CameraBridgeViewBase.java:198)
                                                                                         at android.view.SurfaceView.updateSurface(SurfaceView.java:676)
                                                                                         at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
                                                                                         at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
                                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2341)
                                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1390)
                                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6754)
                                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
                                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:778)
                                                                                         at android.view.Choreographer.doFrame(Choreographer.java:713)
                                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
                                                                                         at android.os.Handler.handleCallback(Handler.java:789)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:172)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6637)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by dkurt** [comment]
@epratheeban just looking into a source code of OpenCV 3.3.1, there is no assertion at line 765 of this file:
https://github.com/opencv/opencv/blob/a871f9e4f7d83dc5851f965bdba5cd01bb7527fe/modules/dnn/src/torch/torch_importer.cpp#L765
You can install OpenCV manager to your device using adb. In example,
```
adb install OpenCV-android-sdk/apk/OpenCV_3.3.1_Manager_3.31_armeabi-v7a.apk
```
and there is no installation errors are expected. BTW, try to print out [OpenCV version](https://docs.opencv.org/master/d7/dad/version_8hpp.html#a4f050efda432e041621b3af3df140adc). I hope it is in `Core` Java package.

**Comment by epratheeban** [comment]
@dkurt  Thanks after switching the version of opencv. I forgot to update the opencv manager. 
It worked now.
