### ISSUE TITLE
setMouseCallback core dumped

### ISSUE THREAD

**Issue by Fjaviervera** [opencv/opencv#9885]
##### Detailed description

Core dumped when setMouseCallback added.

##### Steps to reproduce

import cv2

point = [0,0]

def on_mouse(event,x,y,flags,params):

    global point

    # get mouse click
    if event == cv2.EVENT_LBUTTONDOWN:

        point[0] = x
        point[1] = y

cap = cv2.VideoCapture('video.mp4')
waitTime = 50

#Reading the first frame
(grabbed, frame) = cap.read()

while(cap.isOpened()):

    # (grabbed, frame) = cap.read()

    cv2.namedWindow('frame')
    cv2.setMouseCallback('frame', on_mouse)

    cv2.imshow('frame',frame)

    key = cv2.waitKey(waitTime)

    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

**Comment by alalek** [comment]
Can't reproduce with your example or with browse.py sample.
```
  GUI: 
    QT:                          NO
    GTK+ 3.x:                    YES (ver 3.22.21)
    GThread :                    YES (ver 2.52.3)
    GtkGlExt:                    NO
    OpenGL support:              NO
    VTK support:                 YES (ver 7.1.1)
```


> Core dumped

Stack trace?

**Comment by Fjaviervera** [comment]
Just find out that the core dumped happens only in release mode, debug mode seems to avoid the problem.

stack trace:

#0  0x00000000004a6f8a in PyErr_Occurred ()
#1  0x000000000049ed69 in _PyObject_GC_Malloc ()
#2  0x00000000004a3a66 in _PyObject_GC_NewVar ()
#3  0x00000000004a37aa in PyTuple_New ()
#4  0x000000000041aee0 in ?? ()
#5  0x00000000004a5d9a in Py_BuildValue ()
#6  0x00007ffff2e844f7 in pycvSetMouseCallback(_object*, _object*, _object*) ()
   from /usr/local/lib/python2.7/dist-packages/cv2.so
#7  0x00000000004c468a in PyEval_EvalFrameEx ()
#8  0x00000000004c2765 in PyEval_EvalCodeEx ()
#9  0x00000000004c2509 in PyEval_EvalCode ()
#10 0x00000000004f1def in ?? ()
#11 0x00000000004ec652 in PyRun_FileExFlags ()
#12 0x00000000004eae31 in PyRun_SimpleFileExFlags ()
#13 0x000000000049e14a in Py_Main ()
#14 0x00007ffff7810830 in __libc_start_main (main=0x49dab0 <main>, argc=2, 
    argv=0x7fffffffde98, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffde88)
    at ../csu/libc-start.c:291
#15 0x000000000049d9d9 in _start ()

**Comment by Fjaviervera** [comment]
Maybe I should said that you have to wait like 5-10 secs and then the core dumped appear. @alalek

**Comment by alalek** [comment]
Looks like memory consumption problem.
